site_name: MetaRPC MT4 Golang Documentation
site_url: https://metarpc.github.io/GoMT4/
repo_name: MetaRPC/GoMT4
repo_url: https://github.com/MetaRPC/GoMT4
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    # Навигация и UX
    - navigation.instant          # мгновенная загрузка страниц
    - navigation.tracking         # подсветка активного пункта
    - navigation.sections         # секции в боковом меню
    - navigation.top              # "Back to top" и заголовок наверху
    - navigation.tabs             # вкладки верхнего уровня (Home/Guides/…)
    - toc.integrate               # оглавление в правой колонке
    # Контент
    - content.code.copy           # кнопка "copy" у кода
    - content.action.edit         # кнопка "Edit this page"
    - content.tabs.link           # связные табы
    - search.highlight            # подсветка совпадений в поиске
    - search.suggest              # подсказки в поиске
    - palette.toggle
    - palette.auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MetaRPC/GoMT4
      name: GitHub
  generator: false
  # Низ страницы
  consent:
    title: Cookies & telemetry
    description: We use GitHub Pages basic analytics only. No tracking cookies.

copyright: >
  © {{ date | strftime("%Y") }} MetaRPC. MT4 is a MetaQuotes software. This site is a community-made documentation.

nav:
  - Home: index.md

  - Guides:
      - Introduction: Introduction.md
      - Your Easy Start: Your_Easy_Start.md
      - Beginner Run Guide: Beginner_Run_Guide.md
      - Setup & Environment: setup.md
      - Architecture & Data Flow: Architecture_DataFlow.md
      - Reliability (Timeouts, Reconnects, Backoff): ReTimeouts_Reconnects_Backoff.md
      - Troubleshooting & FAQ: Troubleshooting_FAQ.md
      - Performance Notes: Performance_Notes.md
      - Security & Secrets: Security_Secrets.md
      - Observability (Logs & Metrics): Observability.md
      - Glossary (MT4 Terms): Glossary.md
      - CLI Usage (Playground): cli_usage.md

  - Account:
      - Show Account Summary: Account/ShowAccountSummary.md

  - Market Info:
      - Overview: Market_Info/Market_Info_Overview.md
      - AllSymbols: Market_Info/ShowAllSymbols.md
      - ShowQuote: Market_Info/ShowQuote.md
      - QuoteHistory: Market_Info/ShowQuoteHistory.md
      - QuotesMany: Market_Info/ShowQuotesMany.md
      - SymbolParams: Market_Info/ShowSymbolParams.md
      - Symbols: Market_Info/ShowSymbols.md
      - TickValues: Market_Info/ShowTickValues.md

  - Order Operations:
      - Overview: Order_Operations/Order_Operations_Overview.md
      - OpenedOrderTickets: Order_Operations/ShowOpenedOrderTickets.md
      - OpenedOrders: Order_Operations/ShowOpenedOrders.md
      - OrderCloseByExample: Order_Operations/ShowOrderCloseByExample.md
      - OrderCloseExample: Order_Operations/ShowOrderCloseExample.md
      - OrderDeleteExample: Order_Operations/ShowOrderDeleteExample.md
      - OrderModifyExample: Order_Operations/ShowOrderModifyExample.md
      - OrderSendExample: Order_Operations/ShowOrderSendExample.md
      - OrdersHistory: Order_Operations/ShowOrdersHistory.md

  - Streaming:
      - Overview: Streaming/Streaming_Overview.md
      - StreamOpenedOrderProfits: Streaming/StreamOpenedOrderProfits.md
      - StreamOpenedOrderTickets: Streaming/StreamOpenedOrderTickets.md
      - StreamQuotes: Streaming/StreamQuotes.md
      - StreamTradeUpdates: Streaming/StreamTradeUpdates.md
      - StreamOrdersHistoryExample: Streaming/StreamOrdersHistoryExample.md
      - StreamQuoteHistoryExample: Streaming/StreamQuoteHistoryExample.md

  - API Reference:
      - Overview: "API Reference/Overview.md"
      - Enums: "API Reference/Enums.md"
      - Messages: "API Reference/Messages.md"
      - Streaming: "API Reference/Streaming.md"

  - Cookbook:
      - Account:
          - Show Account Summary: Cookbook/Account/AccountSummary.md
          - Stream Opened Order Profits: Cookbook/Account/StreamOpenedOrderProfits.md
      - Market Info:
          - Get Quote: Cookbook/Market_Info/GetQuote.md
          - Get Multiple Quotes: Cookbook/Market_Info/GetMultipleQuotes.md
          - Stream Quotes: Cookbook/Market_Info/StreamQuotes.md
          - Symbol Params: Cookbook/Market_Info/SymbolParams.md
          - Quote History: Cookbook/Market_Info/QuoteHistory.md
      - Orders:
          - Place Market Order: Cookbook/Orders/PlaceMarketOrder.md
          - Place Pending Order: Cookbook/Orders/PlacePendingOrder.md
          - Modify Order: Cookbook/Orders/ModifyOrder.md
          - Close Order: Cookbook/Orders/CloseOrder.md
          - Close By Orders: Cookbook/Orders/CloseByOrders.md
          - Delete Pending: Cookbook/Orders/DeletePending.md
          - History Orders: Cookbook/Orders/HistoryOrders.md
      - Reliability & Connection:
          - Handle Reconnect: Cookbook/Reliability_Connection/HandleReconnect.md
          - Unary Retries: Cookbook/Reliability_Connection/UnaryRetries.md
          - Health Check: Cookbook/Reliability_Connection/HealthCheck.md
      - Utils & Helpers:
          - Round Volume/Price: Cookbook/Utils_Helpers/RoundVolumePrice.md
          - Ensure Symbol Visible: Cookbook/Utils_Helpers/EnsureSymbolVisible.md
          - Config Example: Cookbook/Utils_Helpers/ConfigExample.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - toc:
      permalink: true
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - abbr
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.emoji:     
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
