site_name: MetaRPC MT4 Golang Documentation

nav:
  - Home: GoMT4_Documentation_Skeleton.md

  - Guides:
      - Introduction: Introduction.md
      - Your Easy Start: Your_Easy_Start.md
      - Beginner Run Guide: Beginner_Run_Guide.md 
      - Setup & Environment: setup.md
      - Architecture & Data Flow: Architecture_DataFlow.md
      - Reliability (Timeouts, Reconnects, Backoff): ReTimeouts_Reconnects_Backoff.md
      - Troubleshooting & FAQ: Troubleshooting_FAQ.md
      - Performance Notes: Performance_Notes.md
      - Security & Secrets: Security_Secrets.md
      - Observability (Logs & Metrics): Observability.md
      - Glossary (MT4 Terms): Glossary.md
      - CLI Usage (Playground): cli_usage.md

  - Account:
      - Show Account Summary: Account/ShowAccountSummary.md

  - Market Info:
      - Overview: Market_Info/Market_Info_Overview.md
      - AllSymbols: Market_Info/ShowAllSymbols.md
      - ShowQuote: Market_Info/ShowQuote.md
      - QuoteHistory: Market_Info/ShowQuoteHistory.md
      - QuotesMany: Market_Info/ShowQuotesMany.md
      - SymbolParams: Market_Info/ShowSymbolParams.md
      - Symbols: Market_Info/ShowSymbols.md
      - TickValues: Market_Info/ShowTickValues.md

  - Order Operations:
      - Overview: Order_Operations/Order_Operations_Overview.md
      - OpenedOrderTickets: Order_Operations/ShowOpenedOrderTickets.md
      - OpenedOrders: Order_Operations/ShowOpenedOrders.md
      - OrderCloseByExample: Order_Operations/ShowOrderCloseByExample.md
      - OrderCloseExample: Order_Operations/ShowOrderCloseExample.md
      - OrderDeleteExample: Order_Operations/ShowOrderDeleteExample.md
      - OrderModifyExample: Order_Operations/ShowOrderModifyExample.md
      - OrderSendExample: Order_Operations/ShowOrderSendExample.md
      - OrdersHistory: Order_Operations/ShowOrdersHistory.md

  - Streaming:
      - Overview: Streaming/Streaming_Overview.md
      - StreamOpenedOrderProfits: Streaming/StreamOpenedOrderProfits.md
      - StreamOpenedOrderTickets: Streaming/StreamOpenedOrderTickets.md
      - StreamQuotes: Streaming/StreamQuotes.md
      - StreamTradeUpdates: Streaming/StreamTradeUpdates.md
      - StreamOrdersHistoryExample: Streaming/StreamOrdersHistoryExample.md
      - StreamQuoteHistoryExample: Streaming/StreamQuoteHistoryExample.md

  - API Reference:
      - Overview: "API Reference/Overview.md"
      - Enums: "API Reference/Enums.md"
      - Messages: "API Reference/Messages.md"
      - Streaming: "API Reference/Streaming.md"

  - Cookbook:
      - Account:
          - Show Account Summary: Cookbook/Account/AccountSummary.md
          - Stream Opened Order Profits: Cookbook/Account/StreamOpenedOrderProfits.md
      - Market Info:
          - Symbol Params: Cookbook/Market_Info/SymbolParams.md
      - Orders:
          - History Orders: Cookbook/Orders/HistoryOrders.md
      - Reliability & Connection:
          - Health Check: Cookbook/Reliability_Connection/HealthCheck.md
      - Utils & Helpers:
          - Config Example: Cookbook/Utils_Helpers/ConfigExample.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - palette.toggle
    - palette.auto

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

plugins:
  - search
