site_name: MetaRPC MT4 Golang Documentation

nav:
  - Home: index.md
  - Account:
      - ShowAccountSummary: Account/ShowAccountSummary.md
  - MarketInfo:
      - ShowAllSymbols: Market_info/ShowAllSymbols.md
      - ShowQuote: Market_info/ShowQuote.md
      - ShowQuoteHistory: Market_info/ShowQuoteHistory.md
      - ShowQuotesMany: Market_info/ShowQuotesMany.md
      - ShowSymbolParams: Market_info/ShowSymbolParams.md
      - ShowSymbols: Market_info/ShowSymbols.md
      - ShowTickValues: Market_info/ShowTickValues.md
  - OrderOperations:
      - ShowOpenedOrderTickets: Order_operations/ShowOpenedOrderTickets.md
      - ShowOpenedOrders: Order_operations/ShowOpenedOrders.md
      - ShowOrderCloseByExample: Order_operations/ShowOrderCloseByExample.md
      - ShowOrderCloseExample: Order_operations/ShowOrderCloseExample.md
      - ShowOrderDeleteExample: Order_operations/ShowOrderDeleteExample.md
      - ShowOrderModifyExample: Order_operations/ShowOrderModifyExample.md
      - ShowOrderSendExample: Order_operations/ShowOrderSendExample.md
      - ShowOrdersHistory: Order_operations/ShowOrdersHistory.md
  - Streaming:
      - StreamOpenedOrderProfits: Streaming/StreamOpenedOrderProfits.md
      - StreamOpenedOrderTickets: Streaming/StreamOpenedOrderTickets.md
      - StreamQuotes: Streaming/StreamQuotes.md
      - StreamTradeUpdates: Streaming/StreamTradeUpdates.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - palette.toggle
    - palette.auto

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
