site_name: MetaRPC MT4 Golang Documentation

nav:
  - Home: index.md
  - Account:
      - ShowAccountSummary: account/ShowAccountSummary.md
  - MarketInfo:
      - ShowAllSymbols: market_info/ShowAllSymbols.md
      - ShowQuote: market_info/ShowQuote.md
      - ShowQuoteHistory: market_info/ShowQuoteHistory.md
      - ShowQuotesMany: market_info/ShowQuotesMany.md
      - ShowSymbolParams: market_info/ShowSymbolParams.md
      - ShowSymbols: market_info/ShowSymbols.md
      - ShowTickValues: market_info/ShowTickValues.md
  - OrderOperations:
      - ShowOpenedOrderTickets: order_operations/ShowOpenedOrderTickets.md
      - ShowOpenedOrders: order_operations/ShowOpenedOrders.md
      - ShowOrderCloseByExample: order_operations/ShowOrderCloseByExample.md
      - ShowOrderCloseExample: order_operations/ShowOrderCloseExample.md
      - ShowOrderDeleteExample: order_operations/ShowOrderDeleteExample.md
      - ShowOrderModifyExample: order_operations/ShowOrderModifyExample.md
      - ShowOrderSendExample: order_operations/ShowOrderSendExample.md
      - ShowOrdersHistory: order_operations/ShowOrdersHistory.md
  - Streaming:
      - StreamOpenedOrderProfits: streaming/StreamOpenedOrderProfits.md
      - StreamOpenedOrderTickets: streaming/StreamOpenedOrderTickets.md
      - StreamQuotes: streaming/StreamQuotes.md
      - StreamTradeUpdates: streaming/StreamTradeUpdates.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - palette.toggle
    - palette.auto

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
