// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mrpc-mt4-error.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_Global LogType = 0
	LogType_MQL5   LogType = 1
	LogType_MQL4   LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "Global",
		1: "MQL5",
		2: "MQL4",
	}
	LogType_value = map[string]int32{
		"Global": 0,
		"MQL5":   1,
		"MQL4":   2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_mrpc_mt4_error_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_mrpc_mt4_error_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{0}
}

type ErrorType int32

const (
	ErrorType_UNDEFINED               ErrorType = 0
	ErrorType_MRPC                    ErrorType = 1
	ErrorType_MRPC_VALIDATION         ErrorType = 2
	ErrorType_MRPC_TIMEOUT            ErrorType = 3
	ErrorType_TERMINAL_API_TIMEOUT    ErrorType = 4
	ErrorType_TERMINAL_API_GET_PARAMS ErrorType = 5
	ErrorType_TERMINAL_API_SET_RESULT ErrorType = 6
	ErrorType_TERMINAL_API_UNEXPECTED ErrorType = 7
	ErrorType_MQL_EXECUTION           ErrorType = 8
	ErrorType_MQL_CUSTOM_EXECUTION    ErrorType = 9
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "UNDEFINED",
		1: "MRPC",
		2: "MRPC_VALIDATION",
		3: "MRPC_TIMEOUT",
		4: "TERMINAL_API_TIMEOUT",
		5: "TERMINAL_API_GET_PARAMS",
		6: "TERMINAL_API_SET_RESULT",
		7: "TERMINAL_API_UNEXPECTED",
		8: "MQL_EXECUTION",
		9: "MQL_CUSTOM_EXECUTION",
	}
	ErrorType_value = map[string]int32{
		"UNDEFINED":               0,
		"MRPC":                    1,
		"MRPC_VALIDATION":         2,
		"MRPC_TIMEOUT":            3,
		"TERMINAL_API_TIMEOUT":    4,
		"TERMINAL_API_GET_PARAMS": 5,
		"TERMINAL_API_SET_RESULT": 6,
		"TERMINAL_API_UNEXPECTED": 7,
		"MQL_EXECUTION":           8,
		"MQL_CUSTOM_EXECUTION":    9,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_mrpc_mt4_error_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_mrpc_mt4_error_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{1}
}

type MqlErrorCode int32

const (
	MqlErrorCode_ERR_NO_ERROR                        MqlErrorCode = 0    // No error
	MqlErrorCode_ERR_NO_RESULT                       MqlErrorCode = 1    // No result
	MqlErrorCode_ERR_COMMON_ERROR                    MqlErrorCode = 2    // Common error
	MqlErrorCode_ERR_INVALID_TRADE_PARAMETERS        MqlErrorCode = 3    // Invalid trade parameters
	MqlErrorCode_ERR_SERVER_BUSY                     MqlErrorCode = 4    // Server busy
	MqlErrorCode_ERR_OLD_VERSION                     MqlErrorCode = 5    // Old version
	MqlErrorCode_ERR_NO_CONNECTION                   MqlErrorCode = 6    // No connection
	MqlErrorCode_ERR_NOT_ENOUGH_RIGHTS               MqlErrorCode = 7    // Not enough rights
	MqlErrorCode_ERR_TOO_FREQUENT_REQUESTS           MqlErrorCode = 8    // Too frequent requests
	MqlErrorCode_ERR_MALFUNCTIONAL_TRADE             MqlErrorCode = 9    // Malfunctional trade
	MqlErrorCode_ERR_ACCOUNT_DISABLED                MqlErrorCode = 64   // Account disabled
	MqlErrorCode_ERR_INVALID_ACCOUNT                 MqlErrorCode = 65   // Invalid account
	MqlErrorCode_ERR_TRADE_TIMEOUT                   MqlErrorCode = 128  // Trade timeout
	MqlErrorCode_ERR_INVALID_PRICE                   MqlErrorCode = 129  // Invalid price
	MqlErrorCode_ERR_INVALID_STOPS                   MqlErrorCode = 130  // Invalid stops
	MqlErrorCode_ERR_INVALID_TRADE_VOLUME            MqlErrorCode = 131  // Invalid trade volume
	MqlErrorCode_ERR_MARKET_CLOSED                   MqlErrorCode = 132  // Market closed
	MqlErrorCode_ERR_TRADE_DISABLED                  MqlErrorCode = 133  // Trade disabled
	MqlErrorCode_ERR_NOT_ENOUGH_MONEY                MqlErrorCode = 134  // Not enough money
	MqlErrorCode_ERR_PRICE_CHANGED                   MqlErrorCode = 135  // Price changed
	MqlErrorCode_ERR_OFF_QUOTES                      MqlErrorCode = 136  // Off quotes
	MqlErrorCode_ERR_BROKER_BUSY                     MqlErrorCode = 137  // Broker busy
	MqlErrorCode_ERR_REQUOTE                         MqlErrorCode = 138  // Requote
	MqlErrorCode_ERR_ORDER_LOCKED                    MqlErrorCode = 139  // Order locked
	MqlErrorCode_ERR_LONG_POSITIONS_ONLY_ALLOWED     MqlErrorCode = 140  // Long positions only allowed
	MqlErrorCode_ERR_TOO_MANY_REQUESTS               MqlErrorCode = 141  // Too many requests
	MqlErrorCode_ERR_TRADE_MODIFY_DENIED             MqlErrorCode = 145  // Trade modify denied
	MqlErrorCode_ERR_TRADE_CONTEXT_BUSY              MqlErrorCode = 146  // Trade context busy
	MqlErrorCode_ERR_TRADE_EXPIRATION_DENIED         MqlErrorCode = 147  // Trade expiration denied
	MqlErrorCode_ERR_TRADE_TOO_MANY_ORDERS           MqlErrorCode = 148  // Too many trade orders
	MqlErrorCode_ERR_TRADE_HEDGE_PROHIBITED          MqlErrorCode = 149  // Trade hedge prohibited
	MqlErrorCode_ERR_TRADE_PROHIBITED_BY_FIFO        MqlErrorCode = 150  // Trade prohibited by FIFO
	MqlErrorCode_ERR_NO_MQLERROR                     MqlErrorCode = 4000 // No MQL error
	MqlErrorCode_ERR_WRONG_FUNCTION_POINTER          MqlErrorCode = 4001 // Wrong function pointer
	MqlErrorCode_ERR_ARRAY_INDEX_OUT_OF_RANGE        MqlErrorCode = 4002 // Array index out of range
	MqlErrorCode_ERR_NO_MEMORY_FOR_CALL_STACK        MqlErrorCode = 4003 // No memory for call stack
	MqlErrorCode_ERR_RECURSIVE_STACK_OVERFLOW        MqlErrorCode = 4004 // Recursive stack overflow
	MqlErrorCode_ERR_NOT_ENOUGH_STACK_FOR_PARAM      MqlErrorCode = 4005 // Not enough stack for parameter
	MqlErrorCode_ERR_NO_MEMORY_FOR_PARAM_STRING      MqlErrorCode = 4006 // No memory for parameter string
	MqlErrorCode_ERR_NO_MEMORY_FOR_TEMP_STRING       MqlErrorCode = 4007 // No memory for temp string
	MqlErrorCode_ERR_NOT_INITIALIZED_STRING          MqlErrorCode = 4008 // Not initialized string
	MqlErrorCode_ERR_NOT_INITIALIZED_ARRAYSTRING     MqlErrorCode = 4009 // Not initialized array string
	MqlErrorCode_ERR_NO_MEMORY_FOR_ARRAYSTRING       MqlErrorCode = 4010 // No memory for array string
	MqlErrorCode_ERR_TOO_LONG_STRING                 MqlErrorCode = 4011 // Too long string
	MqlErrorCode_ERR_REMAINDER_FROM_ZERO_DIVIDE      MqlErrorCode = 4012 // Remainder from zero divide
	MqlErrorCode_ERR_ZERO_DIVIDE                     MqlErrorCode = 4013 // Zero divide
	MqlErrorCode_ERR_UNKNOWN_COMMAND                 MqlErrorCode = 4014 // Unknown command
	MqlErrorCode_ERR_WRONG_JUMP                      MqlErrorCode = 4015 // Wrong jump
	MqlErrorCode_ERR_NOT_INITIALIZED_ARRAY           MqlErrorCode = 4016 // Not initialized array
	MqlErrorCode_ERR_DLL_CALLS_NOT_ALLOWED           MqlErrorCode = 4017 // DLL calls not allowed
	MqlErrorCode_ERR_CANNOT_LOAD_LIBRARY             MqlErrorCode = 4018 // Cannot load library
	MqlErrorCode_ERR_CANNOT_CALL_FUNCTION            MqlErrorCode = 4019 // Cannot call function
	MqlErrorCode_ERR_EXTERNAL_CALLS_NOT_ALLOWED      MqlErrorCode = 4020 // External calls not allowed
	MqlErrorCode_ERR_NO_MEMORY_FOR_RETURNED_STR      MqlErrorCode = 4021 // No memory for returned string
	MqlErrorCode_ERR_SYSTEM_BUSY                     MqlErrorCode = 4022 // System busy
	MqlErrorCode_ERR_DLLFUNC_CRITICALERROR           MqlErrorCode = 4023 // DLL function critical error
	MqlErrorCode_ERR_INTERNAL_ERROR                  MqlErrorCode = 4024 // Internal error
	MqlErrorCode_ERR_OUT_OF_MEMORY                   MqlErrorCode = 4025 // Out of memory
	MqlErrorCode_ERR_INVALID_POINTER                 MqlErrorCode = 4026 // Invalid pointer
	MqlErrorCode_ERR_FORMAT_TOO_MANY_FORMATTERS      MqlErrorCode = 4027 // Too many formatters
	MqlErrorCode_ERR_FORMAT_TOO_MANY_PARAMETERS      MqlErrorCode = 4028 // Too many parameters
	MqlErrorCode_ERR_ARRAY_INVALID                   MqlErrorCode = 4029 // Invalid array
	MqlErrorCode_ERR_CHART_NOREPLY                   MqlErrorCode = 4030 // Chart no reply
	MqlErrorCode_ERR_INVALID_FUNCTION_PARAMSCNT      MqlErrorCode = 4050 // Invalid function parameters count
	MqlErrorCode_ERR_INVALID_FUNCTION_PARAMVALUE     MqlErrorCode = 4051 // Invalid function parameter value
	MqlErrorCode_ERR_STRING_FUNCTION_INTERNAL        MqlErrorCode = 4052 // String function internal error
	MqlErrorCode_ERR_SOME_ARRAY_ERROR                MqlErrorCode = 4053 // Some array error
	MqlErrorCode_ERR_INCORRECT_SERIESARRAY_USING     MqlErrorCode = 4054 // Incorrect series array usage
	MqlErrorCode_ERR_CUSTOM_INDICATOR_ERROR          MqlErrorCode = 4055 // Custom indicator error
	MqlErrorCode_ERR_INCOMPATIBLE_ARRAYS             MqlErrorCode = 4056 // Incompatible arrays
	MqlErrorCode_ERR_GLOBAL_VARIABLES_PROCESSING     MqlErrorCode = 4057 // Global variables processing error
	MqlErrorCode_ERR_GLOBAL_VARIABLE_NOT_FOUND       MqlErrorCode = 4058 // Global variable not found
	MqlErrorCode_ERR_FUNC_NOT_ALLOWED_IN_TESTING     MqlErrorCode = 4059 // Function not allowed in testing
	MqlErrorCode_ERR_FUNCTION_NOT_CONFIRMED          MqlErrorCode = 4060 // Function not confirmed
	MqlErrorCode_ERR_SEND_MAIL_ERROR                 MqlErrorCode = 4061 // Send mail error
	MqlErrorCode_ERR_STRING_PARAMETER_EXPECTED       MqlErrorCode = 4062 // String parameter expected
	MqlErrorCode_ERR_INTEGER_PARAMETER_EXPECTED      MqlErrorCode = 4063 // Integer parameter expected
	MqlErrorCode_ERR_DOUBLE_PARAMETER_EXPECTED       MqlErrorCode = 4064 // Double parameter expected
	MqlErrorCode_ERR_ARRAY_AS_PARAMETER_EXPECTED     MqlErrorCode = 4065 // Array as parameter expected
	MqlErrorCode_ERR_HISTORY_WILL_UPDATED            MqlErrorCode = 4066 // History will be updated
	MqlErrorCode_ERR_TRADE_ERROR                     MqlErrorCode = 4067 // Trade error
	MqlErrorCode_ERR_RESOURCE_NOT_FOUND              MqlErrorCode = 4068 // Resource not found
	MqlErrorCode_ERR_RESOURCE_NOT_SUPPORTED          MqlErrorCode = 4069 // Resource not supported
	MqlErrorCode_ERR_RESOURCE_DUPLICATED             MqlErrorCode = 4070 // Resource duplicated
	MqlErrorCode_ERR_INDICATOR_CANNOT_INIT           MqlErrorCode = 4071 // Indicator cannot initialize
	MqlErrorCode_ERR_INDICATOR_CANNOT_LOAD           MqlErrorCode = 4072 // Indicator cannot load
	MqlErrorCode_ERR_NO_HISTORY_DATA                 MqlErrorCode = 4073 // No history data
	MqlErrorCode_ERR_NO_MEMORY_FOR_HISTORY           MqlErrorCode = 4074 // No memory for history
	MqlErrorCode_ERR_NO_MEMORY_FOR_INDICATOR         MqlErrorCode = 4075 // No memory for indicator
	MqlErrorCode_ERR_END_OF_FILE                     MqlErrorCode = 4099 // End of file
	MqlErrorCode_ERR_SOME_FILE_ERROR                 MqlErrorCode = 4100 // Some file error
	MqlErrorCode_ERR_WRONG_FILE_NAME                 MqlErrorCode = 4101 // Wrong file name
	MqlErrorCode_ERR_TOO_MANY_OPENED_FILES           MqlErrorCode = 4102 // Too many opened files
	MqlErrorCode_ERR_CANNOT_OPEN_FILE                MqlErrorCode = 4103 // Cannot open file
	MqlErrorCode_ERR_INCOMPATIBLE_FILEACCESS         MqlErrorCode = 4104 // Incompatible file access
	MqlErrorCode_ERR_NO_ORDER_SELECTED               MqlErrorCode = 4105 // No order selected
	MqlErrorCode_ERR_UNKNOWN_SYMBOL                  MqlErrorCode = 4106 // Unknown symbol
	MqlErrorCode_ERR_INVALID_PRICE_PARAM             MqlErrorCode = 4107 // Invalid price parameter
	MqlErrorCode_ERR_INVALID_TICKET                  MqlErrorCode = 4108 // Invalid ticket
	MqlErrorCode_ERR_TRADE_NOT_ALLOWED               MqlErrorCode = 4109 // Trade not allowed
	MqlErrorCode_ERR_LONGS_NOT_ALLOWED               MqlErrorCode = 4110 // Longs not allowed
	MqlErrorCode_ERR_SHORTS_NOT_ALLOWED              MqlErrorCode = 4111 // Shorts not allowed
	MqlErrorCode_ERR_TRADE_EXPERT_DISABLED_BY_SERVER MqlErrorCode = 4112 // Trade expert disabled by server
	MqlErrorCode_ERR_OBJECT_ALREADY_EXISTS           MqlErrorCode = 4200 // Object already exists
	MqlErrorCode_ERR_UNKNOWN_OBJECT_PROPERTY         MqlErrorCode = 4201 // Unknown object property
	MqlErrorCode_ERR_OBJECT_DOES_NOT_EXIST           MqlErrorCode = 4202 // Object does not exist
	MqlErrorCode_ERR_UNKNOWN_OBJECT_TYPE             MqlErrorCode = 4203 // Unknown object type
	MqlErrorCode_ERR_NO_OBJECT_NAME                  MqlErrorCode = 4204 // No object name
	MqlErrorCode_ERR_OBJECT_COORDINATES_ERROR        MqlErrorCode = 4205 // Object coordinates error
	MqlErrorCode_ERR_NO_SPECIFIED_SUBWINDOW          MqlErrorCode = 4206 // No specified subwindow
	MqlErrorCode_ERR_SOME_OBJECT_ERROR               MqlErrorCode = 4207 // Some object error
	MqlErrorCode_ERR_FILE_CANNOT_OPEN                MqlErrorCode = 5004 // Cannot open file
)

// Enum value maps for MqlErrorCode.
var (
	MqlErrorCode_name = map[int32]string{
		0:    "ERR_NO_ERROR",
		1:    "ERR_NO_RESULT",
		2:    "ERR_COMMON_ERROR",
		3:    "ERR_INVALID_TRADE_PARAMETERS",
		4:    "ERR_SERVER_BUSY",
		5:    "ERR_OLD_VERSION",
		6:    "ERR_NO_CONNECTION",
		7:    "ERR_NOT_ENOUGH_RIGHTS",
		8:    "ERR_TOO_FREQUENT_REQUESTS",
		9:    "ERR_MALFUNCTIONAL_TRADE",
		64:   "ERR_ACCOUNT_DISABLED",
		65:   "ERR_INVALID_ACCOUNT",
		128:  "ERR_TRADE_TIMEOUT",
		129:  "ERR_INVALID_PRICE",
		130:  "ERR_INVALID_STOPS",
		131:  "ERR_INVALID_TRADE_VOLUME",
		132:  "ERR_MARKET_CLOSED",
		133:  "ERR_TRADE_DISABLED",
		134:  "ERR_NOT_ENOUGH_MONEY",
		135:  "ERR_PRICE_CHANGED",
		136:  "ERR_OFF_QUOTES",
		137:  "ERR_BROKER_BUSY",
		138:  "ERR_REQUOTE",
		139:  "ERR_ORDER_LOCKED",
		140:  "ERR_LONG_POSITIONS_ONLY_ALLOWED",
		141:  "ERR_TOO_MANY_REQUESTS",
		145:  "ERR_TRADE_MODIFY_DENIED",
		146:  "ERR_TRADE_CONTEXT_BUSY",
		147:  "ERR_TRADE_EXPIRATION_DENIED",
		148:  "ERR_TRADE_TOO_MANY_ORDERS",
		149:  "ERR_TRADE_HEDGE_PROHIBITED",
		150:  "ERR_TRADE_PROHIBITED_BY_FIFO",
		4000: "ERR_NO_MQLERROR",
		4001: "ERR_WRONG_FUNCTION_POINTER",
		4002: "ERR_ARRAY_INDEX_OUT_OF_RANGE",
		4003: "ERR_NO_MEMORY_FOR_CALL_STACK",
		4004: "ERR_RECURSIVE_STACK_OVERFLOW",
		4005: "ERR_NOT_ENOUGH_STACK_FOR_PARAM",
		4006: "ERR_NO_MEMORY_FOR_PARAM_STRING",
		4007: "ERR_NO_MEMORY_FOR_TEMP_STRING",
		4008: "ERR_NOT_INITIALIZED_STRING",
		4009: "ERR_NOT_INITIALIZED_ARRAYSTRING",
		4010: "ERR_NO_MEMORY_FOR_ARRAYSTRING",
		4011: "ERR_TOO_LONG_STRING",
		4012: "ERR_REMAINDER_FROM_ZERO_DIVIDE",
		4013: "ERR_ZERO_DIVIDE",
		4014: "ERR_UNKNOWN_COMMAND",
		4015: "ERR_WRONG_JUMP",
		4016: "ERR_NOT_INITIALIZED_ARRAY",
		4017: "ERR_DLL_CALLS_NOT_ALLOWED",
		4018: "ERR_CANNOT_LOAD_LIBRARY",
		4019: "ERR_CANNOT_CALL_FUNCTION",
		4020: "ERR_EXTERNAL_CALLS_NOT_ALLOWED",
		4021: "ERR_NO_MEMORY_FOR_RETURNED_STR",
		4022: "ERR_SYSTEM_BUSY",
		4023: "ERR_DLLFUNC_CRITICALERROR",
		4024: "ERR_INTERNAL_ERROR",
		4025: "ERR_OUT_OF_MEMORY",
		4026: "ERR_INVALID_POINTER",
		4027: "ERR_FORMAT_TOO_MANY_FORMATTERS",
		4028: "ERR_FORMAT_TOO_MANY_PARAMETERS",
		4029: "ERR_ARRAY_INVALID",
		4030: "ERR_CHART_NOREPLY",
		4050: "ERR_INVALID_FUNCTION_PARAMSCNT",
		4051: "ERR_INVALID_FUNCTION_PARAMVALUE",
		4052: "ERR_STRING_FUNCTION_INTERNAL",
		4053: "ERR_SOME_ARRAY_ERROR",
		4054: "ERR_INCORRECT_SERIESARRAY_USING",
		4055: "ERR_CUSTOM_INDICATOR_ERROR",
		4056: "ERR_INCOMPATIBLE_ARRAYS",
		4057: "ERR_GLOBAL_VARIABLES_PROCESSING",
		4058: "ERR_GLOBAL_VARIABLE_NOT_FOUND",
		4059: "ERR_FUNC_NOT_ALLOWED_IN_TESTING",
		4060: "ERR_FUNCTION_NOT_CONFIRMED",
		4061: "ERR_SEND_MAIL_ERROR",
		4062: "ERR_STRING_PARAMETER_EXPECTED",
		4063: "ERR_INTEGER_PARAMETER_EXPECTED",
		4064: "ERR_DOUBLE_PARAMETER_EXPECTED",
		4065: "ERR_ARRAY_AS_PARAMETER_EXPECTED",
		4066: "ERR_HISTORY_WILL_UPDATED",
		4067: "ERR_TRADE_ERROR",
		4068: "ERR_RESOURCE_NOT_FOUND",
		4069: "ERR_RESOURCE_NOT_SUPPORTED",
		4070: "ERR_RESOURCE_DUPLICATED",
		4071: "ERR_INDICATOR_CANNOT_INIT",
		4072: "ERR_INDICATOR_CANNOT_LOAD",
		4073: "ERR_NO_HISTORY_DATA",
		4074: "ERR_NO_MEMORY_FOR_HISTORY",
		4075: "ERR_NO_MEMORY_FOR_INDICATOR",
		4099: "ERR_END_OF_FILE",
		4100: "ERR_SOME_FILE_ERROR",
		4101: "ERR_WRONG_FILE_NAME",
		4102: "ERR_TOO_MANY_OPENED_FILES",
		4103: "ERR_CANNOT_OPEN_FILE",
		4104: "ERR_INCOMPATIBLE_FILEACCESS",
		4105: "ERR_NO_ORDER_SELECTED",
		4106: "ERR_UNKNOWN_SYMBOL",
		4107: "ERR_INVALID_PRICE_PARAM",
		4108: "ERR_INVALID_TICKET",
		4109: "ERR_TRADE_NOT_ALLOWED",
		4110: "ERR_LONGS_NOT_ALLOWED",
		4111: "ERR_SHORTS_NOT_ALLOWED",
		4112: "ERR_TRADE_EXPERT_DISABLED_BY_SERVER",
		4200: "ERR_OBJECT_ALREADY_EXISTS",
		4201: "ERR_UNKNOWN_OBJECT_PROPERTY",
		4202: "ERR_OBJECT_DOES_NOT_EXIST",
		4203: "ERR_UNKNOWN_OBJECT_TYPE",
		4204: "ERR_NO_OBJECT_NAME",
		4205: "ERR_OBJECT_COORDINATES_ERROR",
		4206: "ERR_NO_SPECIFIED_SUBWINDOW",
		4207: "ERR_SOME_OBJECT_ERROR",
		5004: "ERR_FILE_CANNOT_OPEN",
	}
	MqlErrorCode_value = map[string]int32{
		"ERR_NO_ERROR":                        0,
		"ERR_NO_RESULT":                       1,
		"ERR_COMMON_ERROR":                    2,
		"ERR_INVALID_TRADE_PARAMETERS":        3,
		"ERR_SERVER_BUSY":                     4,
		"ERR_OLD_VERSION":                     5,
		"ERR_NO_CONNECTION":                   6,
		"ERR_NOT_ENOUGH_RIGHTS":               7,
		"ERR_TOO_FREQUENT_REQUESTS":           8,
		"ERR_MALFUNCTIONAL_TRADE":             9,
		"ERR_ACCOUNT_DISABLED":                64,
		"ERR_INVALID_ACCOUNT":                 65,
		"ERR_TRADE_TIMEOUT":                   128,
		"ERR_INVALID_PRICE":                   129,
		"ERR_INVALID_STOPS":                   130,
		"ERR_INVALID_TRADE_VOLUME":            131,
		"ERR_MARKET_CLOSED":                   132,
		"ERR_TRADE_DISABLED":                  133,
		"ERR_NOT_ENOUGH_MONEY":                134,
		"ERR_PRICE_CHANGED":                   135,
		"ERR_OFF_QUOTES":                      136,
		"ERR_BROKER_BUSY":                     137,
		"ERR_REQUOTE":                         138,
		"ERR_ORDER_LOCKED":                    139,
		"ERR_LONG_POSITIONS_ONLY_ALLOWED":     140,
		"ERR_TOO_MANY_REQUESTS":               141,
		"ERR_TRADE_MODIFY_DENIED":             145,
		"ERR_TRADE_CONTEXT_BUSY":              146,
		"ERR_TRADE_EXPIRATION_DENIED":         147,
		"ERR_TRADE_TOO_MANY_ORDERS":           148,
		"ERR_TRADE_HEDGE_PROHIBITED":          149,
		"ERR_TRADE_PROHIBITED_BY_FIFO":        150,
		"ERR_NO_MQLERROR":                     4000,
		"ERR_WRONG_FUNCTION_POINTER":          4001,
		"ERR_ARRAY_INDEX_OUT_OF_RANGE":        4002,
		"ERR_NO_MEMORY_FOR_CALL_STACK":        4003,
		"ERR_RECURSIVE_STACK_OVERFLOW":        4004,
		"ERR_NOT_ENOUGH_STACK_FOR_PARAM":      4005,
		"ERR_NO_MEMORY_FOR_PARAM_STRING":      4006,
		"ERR_NO_MEMORY_FOR_TEMP_STRING":       4007,
		"ERR_NOT_INITIALIZED_STRING":          4008,
		"ERR_NOT_INITIALIZED_ARRAYSTRING":     4009,
		"ERR_NO_MEMORY_FOR_ARRAYSTRING":       4010,
		"ERR_TOO_LONG_STRING":                 4011,
		"ERR_REMAINDER_FROM_ZERO_DIVIDE":      4012,
		"ERR_ZERO_DIVIDE":                     4013,
		"ERR_UNKNOWN_COMMAND":                 4014,
		"ERR_WRONG_JUMP":                      4015,
		"ERR_NOT_INITIALIZED_ARRAY":           4016,
		"ERR_DLL_CALLS_NOT_ALLOWED":           4017,
		"ERR_CANNOT_LOAD_LIBRARY":             4018,
		"ERR_CANNOT_CALL_FUNCTION":            4019,
		"ERR_EXTERNAL_CALLS_NOT_ALLOWED":      4020,
		"ERR_NO_MEMORY_FOR_RETURNED_STR":      4021,
		"ERR_SYSTEM_BUSY":                     4022,
		"ERR_DLLFUNC_CRITICALERROR":           4023,
		"ERR_INTERNAL_ERROR":                  4024,
		"ERR_OUT_OF_MEMORY":                   4025,
		"ERR_INVALID_POINTER":                 4026,
		"ERR_FORMAT_TOO_MANY_FORMATTERS":      4027,
		"ERR_FORMAT_TOO_MANY_PARAMETERS":      4028,
		"ERR_ARRAY_INVALID":                   4029,
		"ERR_CHART_NOREPLY":                   4030,
		"ERR_INVALID_FUNCTION_PARAMSCNT":      4050,
		"ERR_INVALID_FUNCTION_PARAMVALUE":     4051,
		"ERR_STRING_FUNCTION_INTERNAL":        4052,
		"ERR_SOME_ARRAY_ERROR":                4053,
		"ERR_INCORRECT_SERIESARRAY_USING":     4054,
		"ERR_CUSTOM_INDICATOR_ERROR":          4055,
		"ERR_INCOMPATIBLE_ARRAYS":             4056,
		"ERR_GLOBAL_VARIABLES_PROCESSING":     4057,
		"ERR_GLOBAL_VARIABLE_NOT_FOUND":       4058,
		"ERR_FUNC_NOT_ALLOWED_IN_TESTING":     4059,
		"ERR_FUNCTION_NOT_CONFIRMED":          4060,
		"ERR_SEND_MAIL_ERROR":                 4061,
		"ERR_STRING_PARAMETER_EXPECTED":       4062,
		"ERR_INTEGER_PARAMETER_EXPECTED":      4063,
		"ERR_DOUBLE_PARAMETER_EXPECTED":       4064,
		"ERR_ARRAY_AS_PARAMETER_EXPECTED":     4065,
		"ERR_HISTORY_WILL_UPDATED":            4066,
		"ERR_TRADE_ERROR":                     4067,
		"ERR_RESOURCE_NOT_FOUND":              4068,
		"ERR_RESOURCE_NOT_SUPPORTED":          4069,
		"ERR_RESOURCE_DUPLICATED":             4070,
		"ERR_INDICATOR_CANNOT_INIT":           4071,
		"ERR_INDICATOR_CANNOT_LOAD":           4072,
		"ERR_NO_HISTORY_DATA":                 4073,
		"ERR_NO_MEMORY_FOR_HISTORY":           4074,
		"ERR_NO_MEMORY_FOR_INDICATOR":         4075,
		"ERR_END_OF_FILE":                     4099,
		"ERR_SOME_FILE_ERROR":                 4100,
		"ERR_WRONG_FILE_NAME":                 4101,
		"ERR_TOO_MANY_OPENED_FILES":           4102,
		"ERR_CANNOT_OPEN_FILE":                4103,
		"ERR_INCOMPATIBLE_FILEACCESS":         4104,
		"ERR_NO_ORDER_SELECTED":               4105,
		"ERR_UNKNOWN_SYMBOL":                  4106,
		"ERR_INVALID_PRICE_PARAM":             4107,
		"ERR_INVALID_TICKET":                  4108,
		"ERR_TRADE_NOT_ALLOWED":               4109,
		"ERR_LONGS_NOT_ALLOWED":               4110,
		"ERR_SHORTS_NOT_ALLOWED":              4111,
		"ERR_TRADE_EXPERT_DISABLED_BY_SERVER": 4112,
		"ERR_OBJECT_ALREADY_EXISTS":           4200,
		"ERR_UNKNOWN_OBJECT_PROPERTY":         4201,
		"ERR_OBJECT_DOES_NOT_EXIST":           4202,
		"ERR_UNKNOWN_OBJECT_TYPE":             4203,
		"ERR_NO_OBJECT_NAME":                  4204,
		"ERR_OBJECT_COORDINATES_ERROR":        4205,
		"ERR_NO_SPECIFIED_SUBWINDOW":          4206,
		"ERR_SOME_OBJECT_ERROR":               4207,
		"ERR_FILE_CANNOT_OPEN":                5004,
	}
)

func (x MqlErrorCode) Enum() *MqlErrorCode {
	p := new(MqlErrorCode)
	*p = x
	return p
}

func (x MqlErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MqlErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_mrpc_mt4_error_proto_enumTypes[2].Descriptor()
}

func (MqlErrorCode) Type() protoreflect.EnumType {
	return &file_mrpc_mt4_error_proto_enumTypes[2]
}

func (x MqlErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MqlErrorCode.Descriptor instead.
func (MqlErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{2}
}

type Error struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                ErrorType              `protobuf:"varint,1,opt,name=type,proto3,enum=mt4_term_api.ErrorType" json:"type,omitempty"`
	ErrorCode           string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	MqlErrorCode        MqlErrorCode           `protobuf:"varint,4,opt,name=mql_error_code,json=mqlErrorCode,proto3,enum=mt4_term_api.MqlErrorCode" json:"mql_error_code,omitempty"`
	MqlErrorIntCode     int32                  `protobuf:"varint,5,opt,name=mql_error_int_code,json=mqlErrorIntCode,proto3" json:"mql_error_int_code,omitempty"`
	MqlErrorDescription string                 `protobuf:"bytes,6,opt,name=mql_error_description,json=mqlErrorDescription,proto3" json:"mql_error_description,omitempty"`
	StackTrace          string                 `protobuf:"bytes,10,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	CommandTypeName     string                 `protobuf:"bytes,11,opt,name=command_type_name,json=commandTypeName,proto3" json:"command_type_name,omitempty"`
	CommandId           int64                  `protobuf:"varint,12,opt,name=commandId,proto3" json:"commandId,omitempty"`
	Properties          []*ErrorProperty       `protobuf:"bytes,13,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_mrpc_mt4_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_mrpc_mt4_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_UNDEFINED
}

func (x *Error) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Error) GetMqlErrorCode() MqlErrorCode {
	if x != nil {
		return x.MqlErrorCode
	}
	return MqlErrorCode_ERR_NO_ERROR
}

func (x *Error) GetMqlErrorIntCode() int32 {
	if x != nil {
		return x.MqlErrorIntCode
	}
	return 0
}

func (x *Error) GetMqlErrorDescription() string {
	if x != nil {
		return x.MqlErrorDescription
	}
	return ""
}

func (x *Error) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *Error) GetCommandTypeName() string {
	if x != nil {
		return x.CommandTypeName
	}
	return ""
}

func (x *Error) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *Error) GetProperties() []*ErrorProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ErrorProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorArgKey   string                 `protobuf:"bytes,1,opt,name=error_arg_key,json=errorArgKey,proto3" json:"error_arg_key,omitempty"`
	ErrorArgValue string                 `protobuf:"bytes,2,opt,name=error_arg_value,json=errorArgValue,proto3" json:"error_arg_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorProperty) Reset() {
	*x = ErrorProperty{}
	mi := &file_mrpc_mt4_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorProperty) ProtoMessage() {}

func (x *ErrorProperty) ProtoReflect() protoreflect.Message {
	mi := &file_mrpc_mt4_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorProperty.ProtoReflect.Descriptor instead.
func (*ErrorProperty) Descriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorProperty) GetErrorArgKey() string {
	if x != nil {
		return x.ErrorArgKey
	}
	return ""
}

func (x *ErrorProperty) GetErrorArgValue() string {
	if x != nil {
		return x.ErrorArgValue
	}
	return ""
}

type LogFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogType       LogType                `protobuf:"varint,1,opt,name=log_type,json=logType,proto3,enum=mt4_term_api.LogType" json:"log_type,omitempty"`
	FullPath      string                 `protobuf:"bytes,2,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFileInfo) Reset() {
	*x = LogFileInfo{}
	mi := &file_mrpc_mt4_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFileInfo) ProtoMessage() {}

func (x *LogFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mrpc_mt4_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFileInfo.ProtoReflect.Descriptor instead.
func (*LogFileInfo) Descriptor() ([]byte, []int) {
	return file_mrpc_mt4_error_proto_rawDescGZIP(), []int{2}
}

func (x *LogFileInfo) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_Global
}

func (x *LogFileInfo) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *LogFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogFileInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_mrpc_mt4_error_proto protoreflect.FileDescriptor

const file_mrpc_mt4_error_proto_rawDesc = "" +
	"\n" +
	"\x14mrpc-mt4-error.proto\x12\fmt4_term_api\"\xc3\x03\n" +
	"\x05Error\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.mt4_term_api.ErrorTypeR\x04type\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12@\n" +
	"\x0emql_error_code\x18\x04 \x01(\x0e2\x1a.mt4_term_api.MqlErrorCodeR\fmqlErrorCode\x12+\n" +
	"\x12mql_error_int_code\x18\x05 \x01(\x05R\x0fmqlErrorIntCode\x122\n" +
	"\x15mql_error_description\x18\x06 \x01(\tR\x13mqlErrorDescription\x12\x1f\n" +
	"\vstack_trace\x18\n" +
	" \x01(\tR\n" +
	"stackTrace\x12*\n" +
	"\x11command_type_name\x18\v \x01(\tR\x0fcommandTypeName\x12\x1c\n" +
	"\tcommandId\x18\f \x01(\x03R\tcommandId\x12;\n" +
	"\n" +
	"properties\x18\r \x03(\v2\x1b.mt4_term_api.ErrorPropertyR\n" +
	"properties\"[\n" +
	"\rErrorProperty\x12\"\n" +
	"\rerror_arg_key\x18\x01 \x01(\tR\verrorArgKey\x12&\n" +
	"\x0ferror_arg_value\x18\x02 \x01(\tR\rerrorArgValue\"\x8a\x01\n" +
	"\vLogFileInfo\x120\n" +
	"\blog_type\x18\x01 \x01(\x0e2\x15.mt4_term_api.LogTypeR\alogType\x12\x1b\n" +
	"\tfull_path\x18\x02 \x01(\tR\bfullPath\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent*)\n" +
	"\aLogType\x12\n" +
	"\n" +
	"\x06Global\x10\x00\x12\b\n" +
	"\x04MQL5\x10\x01\x12\b\n" +
	"\x04MQL4\x10\x02*\xe9\x01\n" +
	"\tErrorType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\b\n" +
	"\x04MRPC\x10\x01\x12\x13\n" +
	"\x0fMRPC_VALIDATION\x10\x02\x12\x10\n" +
	"\fMRPC_TIMEOUT\x10\x03\x12\x18\n" +
	"\x14TERMINAL_API_TIMEOUT\x10\x04\x12\x1b\n" +
	"\x17TERMINAL_API_GET_PARAMS\x10\x05\x12\x1b\n" +
	"\x17TERMINAL_API_SET_RESULT\x10\x06\x12\x1b\n" +
	"\x17TERMINAL_API_UNEXPECTED\x10\a\x12\x11\n" +
	"\rMQL_EXECUTION\x10\b\x12\x18\n" +
	"\x14MQL_CUSTOM_EXECUTION\x10\t*\x96\x1a\n" +
	"\fMqlErrorCode\x12\x10\n" +
	"\fERR_NO_ERROR\x10\x00\x12\x11\n" +
	"\rERR_NO_RESULT\x10\x01\x12\x14\n" +
	"\x10ERR_COMMON_ERROR\x10\x02\x12 \n" +
	"\x1cERR_INVALID_TRADE_PARAMETERS\x10\x03\x12\x13\n" +
	"\x0fERR_SERVER_BUSY\x10\x04\x12\x13\n" +
	"\x0fERR_OLD_VERSION\x10\x05\x12\x15\n" +
	"\x11ERR_NO_CONNECTION\x10\x06\x12\x19\n" +
	"\x15ERR_NOT_ENOUGH_RIGHTS\x10\a\x12\x1d\n" +
	"\x19ERR_TOO_FREQUENT_REQUESTS\x10\b\x12\x1b\n" +
	"\x17ERR_MALFUNCTIONAL_TRADE\x10\t\x12\x18\n" +
	"\x14ERR_ACCOUNT_DISABLED\x10@\x12\x17\n" +
	"\x13ERR_INVALID_ACCOUNT\x10A\x12\x16\n" +
	"\x11ERR_TRADE_TIMEOUT\x10\x80\x01\x12\x16\n" +
	"\x11ERR_INVALID_PRICE\x10\x81\x01\x12\x16\n" +
	"\x11ERR_INVALID_STOPS\x10\x82\x01\x12\x1d\n" +
	"\x18ERR_INVALID_TRADE_VOLUME\x10\x83\x01\x12\x16\n" +
	"\x11ERR_MARKET_CLOSED\x10\x84\x01\x12\x17\n" +
	"\x12ERR_TRADE_DISABLED\x10\x85\x01\x12\x19\n" +
	"\x14ERR_NOT_ENOUGH_MONEY\x10\x86\x01\x12\x16\n" +
	"\x11ERR_PRICE_CHANGED\x10\x87\x01\x12\x13\n" +
	"\x0eERR_OFF_QUOTES\x10\x88\x01\x12\x14\n" +
	"\x0fERR_BROKER_BUSY\x10\x89\x01\x12\x10\n" +
	"\vERR_REQUOTE\x10\x8a\x01\x12\x15\n" +
	"\x10ERR_ORDER_LOCKED\x10\x8b\x01\x12$\n" +
	"\x1fERR_LONG_POSITIONS_ONLY_ALLOWED\x10\x8c\x01\x12\x1a\n" +
	"\x15ERR_TOO_MANY_REQUESTS\x10\x8d\x01\x12\x1c\n" +
	"\x17ERR_TRADE_MODIFY_DENIED\x10\x91\x01\x12\x1b\n" +
	"\x16ERR_TRADE_CONTEXT_BUSY\x10\x92\x01\x12 \n" +
	"\x1bERR_TRADE_EXPIRATION_DENIED\x10\x93\x01\x12\x1e\n" +
	"\x19ERR_TRADE_TOO_MANY_ORDERS\x10\x94\x01\x12\x1f\n" +
	"\x1aERR_TRADE_HEDGE_PROHIBITED\x10\x95\x01\x12!\n" +
	"\x1cERR_TRADE_PROHIBITED_BY_FIFO\x10\x96\x01\x12\x14\n" +
	"\x0fERR_NO_MQLERROR\x10\xa0\x1f\x12\x1f\n" +
	"\x1aERR_WRONG_FUNCTION_POINTER\x10\xa1\x1f\x12!\n" +
	"\x1cERR_ARRAY_INDEX_OUT_OF_RANGE\x10\xa2\x1f\x12!\n" +
	"\x1cERR_NO_MEMORY_FOR_CALL_STACK\x10\xa3\x1f\x12!\n" +
	"\x1cERR_RECURSIVE_STACK_OVERFLOW\x10\xa4\x1f\x12#\n" +
	"\x1eERR_NOT_ENOUGH_STACK_FOR_PARAM\x10\xa5\x1f\x12#\n" +
	"\x1eERR_NO_MEMORY_FOR_PARAM_STRING\x10\xa6\x1f\x12\"\n" +
	"\x1dERR_NO_MEMORY_FOR_TEMP_STRING\x10\xa7\x1f\x12\x1f\n" +
	"\x1aERR_NOT_INITIALIZED_STRING\x10\xa8\x1f\x12$\n" +
	"\x1fERR_NOT_INITIALIZED_ARRAYSTRING\x10\xa9\x1f\x12\"\n" +
	"\x1dERR_NO_MEMORY_FOR_ARRAYSTRING\x10\xaa\x1f\x12\x18\n" +
	"\x13ERR_TOO_LONG_STRING\x10\xab\x1f\x12#\n" +
	"\x1eERR_REMAINDER_FROM_ZERO_DIVIDE\x10\xac\x1f\x12\x14\n" +
	"\x0fERR_ZERO_DIVIDE\x10\xad\x1f\x12\x18\n" +
	"\x13ERR_UNKNOWN_COMMAND\x10\xae\x1f\x12\x13\n" +
	"\x0eERR_WRONG_JUMP\x10\xaf\x1f\x12\x1e\n" +
	"\x19ERR_NOT_INITIALIZED_ARRAY\x10\xb0\x1f\x12\x1e\n" +
	"\x19ERR_DLL_CALLS_NOT_ALLOWED\x10\xb1\x1f\x12\x1c\n" +
	"\x17ERR_CANNOT_LOAD_LIBRARY\x10\xb2\x1f\x12\x1d\n" +
	"\x18ERR_CANNOT_CALL_FUNCTION\x10\xb3\x1f\x12#\n" +
	"\x1eERR_EXTERNAL_CALLS_NOT_ALLOWED\x10\xb4\x1f\x12#\n" +
	"\x1eERR_NO_MEMORY_FOR_RETURNED_STR\x10\xb5\x1f\x12\x14\n" +
	"\x0fERR_SYSTEM_BUSY\x10\xb6\x1f\x12\x1e\n" +
	"\x19ERR_DLLFUNC_CRITICALERROR\x10\xb7\x1f\x12\x17\n" +
	"\x12ERR_INTERNAL_ERROR\x10\xb8\x1f\x12\x16\n" +
	"\x11ERR_OUT_OF_MEMORY\x10\xb9\x1f\x12\x18\n" +
	"\x13ERR_INVALID_POINTER\x10\xba\x1f\x12#\n" +
	"\x1eERR_FORMAT_TOO_MANY_FORMATTERS\x10\xbb\x1f\x12#\n" +
	"\x1eERR_FORMAT_TOO_MANY_PARAMETERS\x10\xbc\x1f\x12\x16\n" +
	"\x11ERR_ARRAY_INVALID\x10\xbd\x1f\x12\x16\n" +
	"\x11ERR_CHART_NOREPLY\x10\xbe\x1f\x12#\n" +
	"\x1eERR_INVALID_FUNCTION_PARAMSCNT\x10\xd2\x1f\x12$\n" +
	"\x1fERR_INVALID_FUNCTION_PARAMVALUE\x10\xd3\x1f\x12!\n" +
	"\x1cERR_STRING_FUNCTION_INTERNAL\x10\xd4\x1f\x12\x19\n" +
	"\x14ERR_SOME_ARRAY_ERROR\x10\xd5\x1f\x12$\n" +
	"\x1fERR_INCORRECT_SERIESARRAY_USING\x10\xd6\x1f\x12\x1f\n" +
	"\x1aERR_CUSTOM_INDICATOR_ERROR\x10\xd7\x1f\x12\x1c\n" +
	"\x17ERR_INCOMPATIBLE_ARRAYS\x10\xd8\x1f\x12$\n" +
	"\x1fERR_GLOBAL_VARIABLES_PROCESSING\x10\xd9\x1f\x12\"\n" +
	"\x1dERR_GLOBAL_VARIABLE_NOT_FOUND\x10\xda\x1f\x12$\n" +
	"\x1fERR_FUNC_NOT_ALLOWED_IN_TESTING\x10\xdb\x1f\x12\x1f\n" +
	"\x1aERR_FUNCTION_NOT_CONFIRMED\x10\xdc\x1f\x12\x18\n" +
	"\x13ERR_SEND_MAIL_ERROR\x10\xdd\x1f\x12\"\n" +
	"\x1dERR_STRING_PARAMETER_EXPECTED\x10\xde\x1f\x12#\n" +
	"\x1eERR_INTEGER_PARAMETER_EXPECTED\x10\xdf\x1f\x12\"\n" +
	"\x1dERR_DOUBLE_PARAMETER_EXPECTED\x10\xe0\x1f\x12$\n" +
	"\x1fERR_ARRAY_AS_PARAMETER_EXPECTED\x10\xe1\x1f\x12\x1d\n" +
	"\x18ERR_HISTORY_WILL_UPDATED\x10\xe2\x1f\x12\x14\n" +
	"\x0fERR_TRADE_ERROR\x10\xe3\x1f\x12\x1b\n" +
	"\x16ERR_RESOURCE_NOT_FOUND\x10\xe4\x1f\x12\x1f\n" +
	"\x1aERR_RESOURCE_NOT_SUPPORTED\x10\xe5\x1f\x12\x1c\n" +
	"\x17ERR_RESOURCE_DUPLICATED\x10\xe6\x1f\x12\x1e\n" +
	"\x19ERR_INDICATOR_CANNOT_INIT\x10\xe7\x1f\x12\x1e\n" +
	"\x19ERR_INDICATOR_CANNOT_LOAD\x10\xe8\x1f\x12\x18\n" +
	"\x13ERR_NO_HISTORY_DATA\x10\xe9\x1f\x12\x1e\n" +
	"\x19ERR_NO_MEMORY_FOR_HISTORY\x10\xea\x1f\x12 \n" +
	"\x1bERR_NO_MEMORY_FOR_INDICATOR\x10\xeb\x1f\x12\x14\n" +
	"\x0fERR_END_OF_FILE\x10\x83 \x12\x18\n" +
	"\x13ERR_SOME_FILE_ERROR\x10\x84 \x12\x18\n" +
	"\x13ERR_WRONG_FILE_NAME\x10\x85 \x12\x1e\n" +
	"\x19ERR_TOO_MANY_OPENED_FILES\x10\x86 \x12\x19\n" +
	"\x14ERR_CANNOT_OPEN_FILE\x10\x87 \x12 \n" +
	"\x1bERR_INCOMPATIBLE_FILEACCESS\x10\x88 \x12\x1a\n" +
	"\x15ERR_NO_ORDER_SELECTED\x10\x89 \x12\x17\n" +
	"\x12ERR_UNKNOWN_SYMBOL\x10\x8a \x12\x1c\n" +
	"\x17ERR_INVALID_PRICE_PARAM\x10\x8b \x12\x17\n" +
	"\x12ERR_INVALID_TICKET\x10\x8c \x12\x1a\n" +
	"\x15ERR_TRADE_NOT_ALLOWED\x10\x8d \x12\x1a\n" +
	"\x15ERR_LONGS_NOT_ALLOWED\x10\x8e \x12\x1b\n" +
	"\x16ERR_SHORTS_NOT_ALLOWED\x10\x8f \x12(\n" +
	"#ERR_TRADE_EXPERT_DISABLED_BY_SERVER\x10\x90 \x12\x1e\n" +
	"\x19ERR_OBJECT_ALREADY_EXISTS\x10\xe8 \x12 \n" +
	"\x1bERR_UNKNOWN_OBJECT_PROPERTY\x10\xe9 \x12\x1e\n" +
	"\x19ERR_OBJECT_DOES_NOT_EXIST\x10\xea \x12\x1c\n" +
	"\x17ERR_UNKNOWN_OBJECT_TYPE\x10\xeb \x12\x17\n" +
	"\x12ERR_NO_OBJECT_NAME\x10\xec \x12!\n" +
	"\x1cERR_OBJECT_COORDINATES_ERROR\x10\xed \x12\x1f\n" +
	"\x1aERR_NO_SPECIFIED_SUBWINDOW\x10\xee \x12\x1a\n" +
	"\x15ERR_SOME_OBJECT_ERROR\x10\xef \x12\x19\n" +
	"\x14ERR_FILE_CANNOT_OPEN\x10\x8c'B Z\x1egithub.com/MetaRPC/GoMT4/pb;pbb\x06proto3"

var (
	file_mrpc_mt4_error_proto_rawDescOnce sync.Once
	file_mrpc_mt4_error_proto_rawDescData []byte
)

func file_mrpc_mt4_error_proto_rawDescGZIP() []byte {
	file_mrpc_mt4_error_proto_rawDescOnce.Do(func() {
		file_mrpc_mt4_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mrpc_mt4_error_proto_rawDesc), len(file_mrpc_mt4_error_proto_rawDesc)))
	})
	return file_mrpc_mt4_error_proto_rawDescData
}

var file_mrpc_mt4_error_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mrpc_mt4_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mrpc_mt4_error_proto_goTypes = []any{
	(LogType)(0),          // 0: mt4_term_api.LogType
	(ErrorType)(0),        // 1: mt4_term_api.ErrorType
	(MqlErrorCode)(0),     // 2: mt4_term_api.MqlErrorCode
	(*Error)(nil),         // 3: mt4_term_api.Error
	(*ErrorProperty)(nil), // 4: mt4_term_api.ErrorProperty
	(*LogFileInfo)(nil),   // 5: mt4_term_api.LogFileInfo
}
var file_mrpc_mt4_error_proto_depIdxs = []int32{
	1, // 0: mt4_term_api.Error.type:type_name -> mt4_term_api.ErrorType
	2, // 1: mt4_term_api.Error.mql_error_code:type_name -> mt4_term_api.MqlErrorCode
	4, // 2: mt4_term_api.Error.properties:type_name -> mt4_term_api.ErrorProperty
	0, // 3: mt4_term_api.LogFileInfo.log_type:type_name -> mt4_term_api.LogType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mrpc_mt4_error_proto_init() }
func file_mrpc_mt4_error_proto_init() {
	if File_mrpc_mt4_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mrpc_mt4_error_proto_rawDesc), len(file_mrpc_mt4_error_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mrpc_mt4_error_proto_goTypes,
		DependencyIndexes: file_mrpc_mt4_error_proto_depIdxs,
		EnumInfos:         file_mrpc_mt4_error_proto_enumTypes,
		MessageInfos:      file_mrpc_mt4_error_proto_msgTypes,
	}.Build()
	File_mrpc_mt4_error_proto = out.File
	file_mrpc_mt4_error_proto_goTypes = nil
	file_mrpc_mt4_error_proto_depIdxs = nil
}
