// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mt4-term-api-connection.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies the type of proxy servers that an instance of the ProxySocket class can use.
type ProxyTypes int32

const (
	// No proxy server; the ProxySocket object behaves exactly like an ordinary Socket object.
	ProxyTypes_None ProxyTypes = 0
	// A HTTPS (CONNECT) proxy server.
	ProxyTypes_Https ProxyTypes = 1
	// A SOCKS4[A] proxy server.
	ProxyTypes_Socks4 ProxyTypes = 2
	// A SOCKS5 proxy server.
	ProxyTypes_Socks5 ProxyTypes = 3
)

// Enum value maps for ProxyTypes.
var (
	ProxyTypes_name = map[int32]string{
		0: "None",
		1: "Https",
		2: "Socks4",
		3: "Socks5",
	}
	ProxyTypes_value = map[string]int32{
		"None":   0,
		"Https":  1,
		"Socks4": 2,
		"Socks5": 3,
	}
)

func (x ProxyTypes) Enum() *ProxyTypes {
	p := new(ProxyTypes)
	*p = x
	return p
}

func (x ProxyTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_connection_proto_enumTypes[0].Descriptor()
}

func (ProxyTypes) Type() protoreflect.EnumType {
	return &file_mt4_term_api_connection_proto_enumTypes[0]
}

func (x ProxyTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyTypes.Descriptor instead.
func (ProxyTypes) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{0}
}

type TerminalType int32

const (
	TerminalType_MT4 TerminalType = 0
	TerminalType_MT5 TerminalType = 1
)

// Enum value maps for TerminalType.
var (
	TerminalType_name = map[int32]string{
		0: "MT4",
		1: "MT5",
	}
	TerminalType_value = map[string]int32{
		"MT4": 0,
		"MT5": 1,
	}
)

func (x TerminalType) Enum() *TerminalType {
	p := new(TerminalType)
	*p = x
	return p
}

func (x TerminalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_connection_proto_enumTypes[1].Descriptor()
}

func (TerminalType) Type() protoreflect.EnumType {
	return &file_mt4_term_api_connection_proto_enumTypes[1]
}

func (x TerminalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalType.Descriptor instead.
func (TerminalType) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{1}
}

type ConnectExRequest struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	User                                   uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`                                                                                                                               // Account number. [Required]
	Password                               string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                                                                                                        // Password. [Required]
	MtClusterName                          string                 `protobuf:"bytes,3,opt,name=mt_cluster_name,json=mtClusterName,proto3" json:"mt_cluster_name,omitempty"`                                                                                       // MT cluster name. [Required]
	BaseChartSymbol                        *string                `protobuf:"bytes,4,opt,name=base_chart_symbol,json=baseChartSymbol,proto3,oneof" json:"base_chart_symbol,omitempty"`                                                                           // Base chart symbol [Optional]
	TerminalReadinessWaitingTimeoutSeconds *int32                 `protobuf:"varint,5,opt,name=terminal_readiness_waiting_timeout_seconds,json=terminalReadinessWaitingTimeoutSeconds,proto3,oneof" json:"terminal_readiness_waiting_timeout_seconds,omitempty"` // Readiness timeout seconds. Default = 100 seconds [Optional]
	ExpertsToAdd                           []*ExpertAdviser       `protobuf:"bytes,6,rep,name=experts_to_add,json=expertsToAdd,proto3" json:"experts_to_add,omitempty"`                                                                                          // EA files to add to terminal instance [Optional]
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *ConnectExRequest) Reset() {
	*x = ConnectExRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectExRequest) ProtoMessage() {}

func (x *ConnectExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectExRequest.ProtoReflect.Descriptor instead.
func (*ConnectExRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectExRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *ConnectExRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectExRequest) GetMtClusterName() string {
	if x != nil {
		return x.MtClusterName
	}
	return ""
}

func (x *ConnectExRequest) GetBaseChartSymbol() string {
	if x != nil && x.BaseChartSymbol != nil {
		return *x.BaseChartSymbol
	}
	return ""
}

func (x *ConnectExRequest) GetTerminalReadinessWaitingTimeoutSeconds() int32 {
	if x != nil && x.TerminalReadinessWaitingTimeoutSeconds != nil {
		return *x.TerminalReadinessWaitingTimeoutSeconds
	}
	return 0
}

func (x *ConnectExRequest) GetExpertsToAdd() []*ExpertAdviser {
	if x != nil {
		return x.ExpertsToAdd
	}
	return nil
}

type ConnectExReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ConnectExReply_Data
	//	*ConnectExReply_Error
	Response      isConnectExReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectExReply) Reset() {
	*x = ConnectExReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectExReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectExReply) ProtoMessage() {}

func (x *ConnectExReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectExReply.ProtoReflect.Descriptor instead.
func (*ConnectExReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectExReply) GetResponse() isConnectExReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ConnectExReply) GetData() *ConnectData {
	if x != nil {
		if x, ok := x.Response.(*ConnectExReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ConnectExReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ConnectExReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConnectExReply_Response interface {
	isConnectExReply_Response()
}

type ConnectExReply_Data struct {
	Data *ConnectData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ConnectExReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ConnectExReply_Data) isConnectExReply_Response() {}

func (*ConnectExReply_Error) isConnectExReply_Response() {}

type ReconnectRequest struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	ForceReconnection                      *bool                  `protobuf:"varint,1,opt,name=force_reconnection,json=forceReconnection,proto3,oneof" json:"force_reconnection,omitempty"`                                                                      // Recreate a terminal instance even if current instance is alive
	TerminalReadinessWaitingTimeoutSeconds *int32                 `protobuf:"varint,2,opt,name=terminal_readiness_waiting_timeout_seconds,json=terminalReadinessWaitingTimeoutSeconds,proto3,oneof" json:"terminal_readiness_waiting_timeout_seconds,omitempty"` // optional waiting getting alive for terminal
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *ReconnectRequest) Reset() {
	*x = ReconnectRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRequest) ProtoMessage() {}

func (x *ReconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRequest.ProtoReflect.Descriptor instead.
func (*ReconnectRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ReconnectRequest) GetForceReconnection() bool {
	if x != nil && x.ForceReconnection != nil {
		return *x.ForceReconnection
	}
	return false
}

func (x *ReconnectRequest) GetTerminalReadinessWaitingTimeoutSeconds() int32 {
	if x != nil && x.TerminalReadinessWaitingTimeoutSeconds != nil {
		return *x.TerminalReadinessWaitingTimeoutSeconds
	}
	return 0
}

type ReconnectReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ReconnectReply_Data
	//	*ReconnectReply_Error
	Response      isReconnectReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectReply) Reset() {
	*x = ReconnectReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReply) ProtoMessage() {}

func (x *ReconnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReply.ProtoReflect.Descriptor instead.
func (*ReconnectReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{3}
}

func (x *ReconnectReply) GetResponse() isReconnectReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ReconnectReply) GetData() *ReconnectData {
	if x != nil {
		if x, ok := x.Response.(*ReconnectReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ReconnectReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ReconnectReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isReconnectReply_Response interface {
	isReconnectReply_Response()
}

type ReconnectReply_Data struct {
	Data *ReconnectData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ReconnectReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ReconnectReply_Data) isReconnectReply_Response() {}

func (*ReconnectReply_Error) isReconnectReply_Response() {}

type ReconnectData struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	TerminalWasRecreated           bool                   `protobuf:"varint,1,opt,name=terminal_was_recreated,json=terminalWasRecreated,proto3" json:"terminal_was_recreated,omitempty"`
	TerminalType                   TerminalType           `protobuf:"varint,2,opt,name=terminal_type,json=terminalType,proto3,enum=mt4_term_api.TerminalType" json:"terminal_type,omitempty"`
	TerminalInstanceGuid           string                 `protobuf:"bytes,3,opt,name=terminal_instance_guid,json=terminalInstanceGuid,proto3" json:"terminal_instance_guid,omitempty"`
	OldTerminalFullLiveTimeSeconds int64                  `protobuf:"varint,4,opt,name=old_terminal_full_live_time_seconds,json=oldTerminalFullLiveTimeSeconds,proto3" json:"old_terminal_full_live_time_seconds,omitempty"`
	OldLogFiles                    []*LogFileInfo         `protobuf:"bytes,5,rep,name=old_log_files,json=oldLogFiles,proto3" json:"old_log_files,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ReconnectData) Reset() {
	*x = ReconnectData{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectData) ProtoMessage() {}

func (x *ReconnectData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectData.ProtoReflect.Descriptor instead.
func (*ReconnectData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{4}
}

func (x *ReconnectData) GetTerminalWasRecreated() bool {
	if x != nil {
		return x.TerminalWasRecreated
	}
	return false
}

func (x *ReconnectData) GetTerminalType() TerminalType {
	if x != nil {
		return x.TerminalType
	}
	return TerminalType_MT4
}

func (x *ReconnectData) GetTerminalInstanceGuid() string {
	if x != nil {
		return x.TerminalInstanceGuid
	}
	return ""
}

func (x *ReconnectData) GetOldTerminalFullLiveTimeSeconds() int64 {
	if x != nil {
		return x.OldTerminalFullLiveTimeSeconds
	}
	return 0
}

func (x *ReconnectData) GetOldLogFiles() []*LogFileInfo {
	if x != nil {
		return x.OldLogFiles
	}
	return nil
}

type ConnectRequest struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	User                                   uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`        // Account number. [Required]
	Password                               string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Password. [Required]
	Host                                   string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`         // Host - ip address or dns name. [Required]
	Port                                   int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`        // Port. [Required]
	BaseChartSymbol                        *string                `protobuf:"bytes,5,opt,name=base_chart_symbol,json=baseChartSymbol,proto3,oneof" json:"base_chart_symbol,omitempty"`
	WaitForTerminalIsAlive                 *bool                  `protobuf:"varint,6,opt,name=wait_for_terminal_is_alive,json=waitForTerminalIsAlive,proto3,oneof" json:"wait_for_terminal_is_alive,omitempty"`
	TerminalReadinessWaitingTimeoutSeconds *int32                 `protobuf:"varint,7,opt,name=terminal_readiness_waiting_timeout_seconds,json=terminalReadinessWaitingTimeoutSeconds,proto3,oneof" json:"terminal_readiness_waiting_timeout_seconds,omitempty"`
	ExpertsToAdd                           []*ExpertAdviser       `protobuf:"bytes,8,rep,name=experts_to_add,json=expertsToAdd,proto3" json:"experts_to_add,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *ConnectRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectRequest) GetBaseChartSymbol() string {
	if x != nil && x.BaseChartSymbol != nil {
		return *x.BaseChartSymbol
	}
	return ""
}

func (x *ConnectRequest) GetWaitForTerminalIsAlive() bool {
	if x != nil && x.WaitForTerminalIsAlive != nil {
		return *x.WaitForTerminalIsAlive
	}
	return false
}

func (x *ConnectRequest) GetTerminalReadinessWaitingTimeoutSeconds() int32 {
	if x != nil && x.TerminalReadinessWaitingTimeoutSeconds != nil {
		return *x.TerminalReadinessWaitingTimeoutSeconds
	}
	return 0
}

func (x *ConnectRequest) GetExpertsToAdd() []*ExpertAdviser {
	if x != nil {
		return x.ExpertsToAdd
	}
	return nil
}

type ExpertAdviser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // File content as a byte array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertAdviser) Reset() {
	*x = ExpertAdviser{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertAdviser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertAdviser) ProtoMessage() {}

func (x *ExpertAdviser) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertAdviser.ProtoReflect.Descriptor instead.
func (*ExpertAdviser) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{6}
}

func (x *ExpertAdviser) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExpertAdviser) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type ConnectReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ConnectReply_Data
	//	*ConnectReply_Error
	Response      isConnectReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReply) Reset() {
	*x = ConnectReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReply) ProtoMessage() {}

func (x *ConnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReply.ProtoReflect.Descriptor instead.
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectReply) GetResponse() isConnectReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ConnectReply) GetData() *ConnectData {
	if x != nil {
		if x, ok := x.Response.(*ConnectReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ConnectReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ConnectReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConnectReply_Response interface {
	isConnectReply_Response()
}

type ConnectReply_Data struct {
	Data *ConnectData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ConnectReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ConnectReply_Data) isConnectReply_Response() {}

func (*ConnectReply_Error) isConnectReply_Response() {}

type ConnectData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection unique identifier - use this in the 'mt-sticky-session-header' value
	TerminalInstanceGuid string `protobuf:"bytes,1,opt,name=terminal_instance_guid,json=terminalInstanceGuid,proto3" json:"terminal_instance_guid,omitempty"`
	// Terminal type MT5 or MT4 (Temporary only MT5)
	TerminalType  TerminalType `protobuf:"varint,3,opt,name=terminal_type,json=terminalType,proto3,enum=mt4_term_api.TerminalType" json:"terminal_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectData) Reset() {
	*x = ConnectData{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectData) ProtoMessage() {}

func (x *ConnectData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectData.ProtoReflect.Descriptor instead.
func (*ConnectData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectData) GetTerminalInstanceGuid() string {
	if x != nil {
		return x.TerminalInstanceGuid
	}
	return ""
}

func (x *ConnectData) GetTerminalType() TerminalType {
	if x != nil {
		return x.TerminalType
	}
	return TerminalType_MT4
}

// [DefaultValues]
//
//	{
//	 "user": "21455",
//	 "password": "1nJeS+Ae",
//	 "host": "95.217.147.61",
//	 "port": "443",
//	 "proxyUser": "ProxyUser123",
//	 "proxyPassword": "qwerty123",
//	 "proxyHost": "65.108.126.217",
//	 "proxyPort": "1080",
//	 "proxyType": "Socks5"
//	}
type ConnectProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account number. [Required]
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// Password. [Required]
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Host - ip adddress or dns name. [Required]
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// Port. [Required]
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// Proxy user [Required]
	ProxyUser string `protobuf:"bytes,5,opt,name=proxyUser,proto3" json:"proxyUser,omitempty"`
	// Proxy password [Required]
	ProxyPassword string `protobuf:"bytes,6,opt,name=proxyPassword,proto3" json:"proxyPassword,omitempty"`
	// Proxy server ip adddress [Required]
	ProxyHost string `protobuf:"bytes,7,opt,name=proxyHost,proto3" json:"proxyHost,omitempty"`
	// Proxy port [Required]
	ProxyPort uint32 `protobuf:"varint,8,opt,name=proxyPort,proto3" json:"proxyPort,omitempty"`
	// Proxy type. Put 'Socks5' for default parameters [Required]
	ProxyType                              ProxyTypes       `protobuf:"varint,9,opt,name=proxyType,proto3,enum=mt4_term_api.ProxyTypes" json:"proxyType,omitempty"`
	BaseChartSymbol                        *string          `protobuf:"bytes,10,opt,name=base_chart_symbol,json=baseChartSymbol,proto3,oneof" json:"base_chart_symbol,omitempty"`
	WaitForTerminalIsAlive                 *bool            `protobuf:"varint,11,opt,name=wait_for_terminal_is_alive,json=waitForTerminalIsAlive,proto3,oneof" json:"wait_for_terminal_is_alive,omitempty"`
	TerminalReadinessWaitingTimeoutSeconds *int32           `protobuf:"varint,12,opt,name=terminal_readiness_waiting_timeout_seconds,json=terminalReadinessWaitingTimeoutSeconds,proto3,oneof" json:"terminal_readiness_waiting_timeout_seconds,omitempty"`
	ExpertsToAdd                           []*ExpertAdviser `protobuf:"bytes,13,rep,name=experts_to_add,json=expertsToAdd,proto3" json:"experts_to_add,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *ConnectProxyRequest) Reset() {
	*x = ConnectProxyRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectProxyRequest) ProtoMessage() {}

func (x *ConnectProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectProxyRequest.ProtoReflect.Descriptor instead.
func (*ConnectProxyRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectProxyRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *ConnectProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectProxyRequest) GetProxyUser() string {
	if x != nil {
		return x.ProxyUser
	}
	return ""
}

func (x *ConnectProxyRequest) GetProxyPassword() string {
	if x != nil {
		return x.ProxyPassword
	}
	return ""
}

func (x *ConnectProxyRequest) GetProxyHost() string {
	if x != nil {
		return x.ProxyHost
	}
	return ""
}

func (x *ConnectProxyRequest) GetProxyPort() uint32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

func (x *ConnectProxyRequest) GetProxyType() ProxyTypes {
	if x != nil {
		return x.ProxyType
	}
	return ProxyTypes_None
}

func (x *ConnectProxyRequest) GetBaseChartSymbol() string {
	if x != nil && x.BaseChartSymbol != nil {
		return *x.BaseChartSymbol
	}
	return ""
}

func (x *ConnectProxyRequest) GetWaitForTerminalIsAlive() bool {
	if x != nil && x.WaitForTerminalIsAlive != nil {
		return *x.WaitForTerminalIsAlive
	}
	return false
}

func (x *ConnectProxyRequest) GetTerminalReadinessWaitingTimeoutSeconds() int32 {
	if x != nil && x.TerminalReadinessWaitingTimeoutSeconds != nil {
		return *x.TerminalReadinessWaitingTimeoutSeconds
	}
	return 0
}

func (x *ConnectProxyRequest) GetExpertsToAdd() []*ExpertAdviser {
	if x != nil {
		return x.ExpertsToAdd
	}
	return nil
}

type ConnectProxyReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ConnectProxyReply_Data
	//	*ConnectProxyReply_Error
	Response      isConnectProxyReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectProxyReply) Reset() {
	*x = ConnectProxyReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectProxyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectProxyReply) ProtoMessage() {}

func (x *ConnectProxyReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectProxyReply.ProtoReflect.Descriptor instead.
func (*ConnectProxyReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectProxyReply) GetResponse() isConnectProxyReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ConnectProxyReply) GetData() *ConnectProxyData {
	if x != nil {
		if x, ok := x.Response.(*ConnectProxyReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ConnectProxyReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ConnectProxyReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConnectProxyReply_Response interface {
	isConnectProxyReply_Response()
}

type ConnectProxyReply_Data struct {
	Data *ConnectProxyData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ConnectProxyReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ConnectProxyReply_Data) isConnectProxyReply_Response() {}

func (*ConnectProxyReply_Error) isConnectProxyReply_Response() {}

type ConnectProxyData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection unique identifier - use this in the header 'mrpc-terminal-guid' value
	UniqueIdentifier string `protobuf:"bytes,1,opt,name=unique_identifier,json=uniqueIdentifier,proto3" json:"unique_identifier,omitempty"`
	// Terminal type MT5 or MT4 (Temporary only MT5)
	TerminalType  TerminalType `protobuf:"varint,2,opt,name=terminal_type,json=terminalType,proto3,enum=mt4_term_api.TerminalType" json:"terminal_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectProxyData) Reset() {
	*x = ConnectProxyData{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectProxyData) ProtoMessage() {}

func (x *ConnectProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectProxyData.ProtoReflect.Descriptor instead.
func (*ConnectProxyData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectProxyData) GetUniqueIdentifier() string {
	if x != nil {
		return x.UniqueIdentifier
	}
	return ""
}

func (x *ConnectProxyData) GetTerminalType() TerminalType {
	if x != nil {
		return x.TerminalType
	}
	return TerminalType_MT4
}

// Do not forget to add header 'mt-sticky-session-header' with a Connection unique identifier value
type CheckConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectRequest) Reset() {
	*x = CheckConnectRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectRequest) ProtoMessage() {}

func (x *CheckConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectRequest.ProtoReflect.Descriptor instead.
func (*CheckConnectRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{12}
}

type CheckConnectReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CheckConnectReply_Data
	//	*CheckConnectReply_Error
	Response      isCheckConnectReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectReply) Reset() {
	*x = CheckConnectReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectReply) ProtoMessage() {}

func (x *CheckConnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectReply.ProtoReflect.Descriptor instead.
func (*CheckConnectReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{13}
}

func (x *CheckConnectReply) GetResponse() isCheckConnectReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CheckConnectReply) GetData() *CheckConnectData {
	if x != nil {
		if x, ok := x.Response.(*CheckConnectReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CheckConnectReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*CheckConnectReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCheckConnectReply_Response interface {
	isCheckConnectReply_Response()
}

type CheckConnectReply_Data struct {
	Data *CheckConnectData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type CheckConnectReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CheckConnectReply_Data) isCheckConnectReply_Response() {}

func (*CheckConnectReply_Error) isCheckConnectReply_Response() {}

type CheckConnectData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection unique identifier. Reflects value from header 'mt-sticky-session-header'
	UniqueIdentifier string `protobuf:"bytes,1,opt,name=unique_identifier,json=uniqueIdentifier,proto3" json:"unique_identifier,omitempty"`
	// Connection health status
	HealthCheck   *TerminalHealthCheck `protobuf:"bytes,2,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectData) Reset() {
	*x = CheckConnectData{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectData) ProtoMessage() {}

func (x *CheckConnectData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectData.ProtoReflect.Descriptor instead.
func (*CheckConnectData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{14}
}

func (x *CheckConnectData) GetUniqueIdentifier() string {
	if x != nil {
		return x.UniqueIdentifier
	}
	return ""
}

func (x *CheckConnectData) GetHealthCheck() *TerminalHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

type TerminalHealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection is alive
	IsAlive bool `protobuf:"varint,1,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	// Error message
	ErrorMessage *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	// Error code
	ErrorCode *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	// Stack trace
	StackTrace                    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=StackTrace,proto3" json:"StackTrace,omitempty"`
	HasAuthorizationError         bool                    `protobuf:"varint,5,opt,name=has_authorization_error,json=hasAuthorizationError,proto3" json:"has_authorization_error,omitempty"`
	ApiIsAlive                    bool                    `protobuf:"varint,6,opt,name=api_is_alive,json=apiIsAlive,proto3" json:"api_is_alive,omitempty"`
	TerminalIsConnectedToMtServer bool                    `protobuf:"varint,7,opt,name=terminal_is_connected_to_mt_server,json=terminalIsConnectedToMtServer,proto3" json:"terminal_is_connected_to_mt_server,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *TerminalHealthCheck) Reset() {
	*x = TerminalHealthCheck{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalHealthCheck) ProtoMessage() {}

func (x *TerminalHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalHealthCheck.ProtoReflect.Descriptor instead.
func (*TerminalHealthCheck) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{15}
}

func (x *TerminalHealthCheck) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *TerminalHealthCheck) GetErrorMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *TerminalHealthCheck) GetErrorCode() *wrapperspb.StringValue {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

func (x *TerminalHealthCheck) GetStackTrace() *wrapperspb.StringValue {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

func (x *TerminalHealthCheck) GetHasAuthorizationError() bool {
	if x != nil {
		return x.HasAuthorizationError
	}
	return false
}

func (x *TerminalHealthCheck) GetApiIsAlive() bool {
	if x != nil {
		return x.ApiIsAlive
	}
	return false
}

func (x *TerminalHealthCheck) GetTerminalIsConnectedToMtServer() bool {
	if x != nil {
		return x.TerminalIsConnectedToMtServer
	}
	return false
}

// Do not forget to add header 'mt-sticky-session-header' with a Connection unique identifier value
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{16}
}

type DisconnectReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*DisconnectReply_Data
	//	*DisconnectReply_Error
	Response      isDisconnectReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectReply) Reset() {
	*x = DisconnectReply{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectReply) ProtoMessage() {}

func (x *DisconnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectReply.ProtoReflect.Descriptor instead.
func (*DisconnectReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{17}
}

func (x *DisconnectReply) GetResponse() isDisconnectReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DisconnectReply) GetData() *DisconnectData {
	if x != nil {
		if x, ok := x.Response.(*DisconnectReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *DisconnectReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*DisconnectReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDisconnectReply_Response interface {
	isDisconnectReply_Response()
}

type DisconnectReply_Data struct {
	Data *DisconnectData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type DisconnectReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DisconnectReply_Data) isDisconnectReply_Response() {}

func (*DisconnectReply_Error) isDisconnectReply_Response() {}

type DisconnectData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of closed connection. Reflects value from header 'mt-sticky-session-header'
	UniqueIdentifier    string `protobuf:"bytes,1,opt,name=unique_identifier,json=uniqueIdentifier,proto3" json:"unique_identifier,omitempty"`
	FullLifeTimeSeconds int64  `protobuf:"varint,2,opt,name=full_life_time_seconds,json=fullLifeTimeSeconds,proto3" json:"full_life_time_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DisconnectData) Reset() {
	*x = DisconnectData{}
	mi := &file_mt4_term_api_connection_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectData) ProtoMessage() {}

func (x *DisconnectData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_connection_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectData.ProtoReflect.Descriptor instead.
func (*DisconnectData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_connection_proto_rawDescGZIP(), []int{18}
}

func (x *DisconnectData) GetUniqueIdentifier() string {
	if x != nil {
		return x.UniqueIdentifier
	}
	return ""
}

func (x *DisconnectData) GetFullLifeTimeSeconds() int64 {
	if x != nil {
		return x.FullLifeTimeSeconds
	}
	return 0
}

var File_mt4_term_api_connection_proto protoreflect.FileDescriptor

const file_mt4_term_api_connection_proto_rawDesc = "" +
	"\n" +
	"\x1dmt4-term-api-connection.proto\x12\fmt4_term_api\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14mrpc-mt4-error.proto\"\x84\x03\n" +
	"\x10ConnectExRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12&\n" +
	"\x0fmt_cluster_name\x18\x03 \x01(\tR\rmtClusterName\x12/\n" +
	"\x11base_chart_symbol\x18\x04 \x01(\tH\x00R\x0fbaseChartSymbol\x88\x01\x01\x12_\n" +
	"*terminal_readiness_waiting_timeout_seconds\x18\x05 \x01(\x05H\x01R&terminalReadinessWaitingTimeoutSeconds\x88\x01\x01\x12A\n" +
	"\x0eexperts_to_add\x18\x06 \x03(\v2\x1b.mt4_term_api.ExpertAdviserR\fexpertsToAddB\x14\n" +
	"\x12_base_chart_symbolB-\n" +
	"+_terminal_readiness_waiting_timeout_seconds\"z\n" +
	"\x0eConnectExReply\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x19.mt4_term_api.ConnectDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xed\x01\n" +
	"\x10ReconnectRequest\x122\n" +
	"\x12force_reconnection\x18\x01 \x01(\bH\x00R\x11forceReconnection\x88\x01\x01\x12_\n" +
	"*terminal_readiness_waiting_timeout_seconds\x18\x02 \x01(\x05H\x01R&terminalReadinessWaitingTimeoutSeconds\x88\x01\x01B\x15\n" +
	"\x13_force_reconnectionB-\n" +
	"+_terminal_readiness_waiting_timeout_seconds\"|\n" +
	"\x0eReconnectReply\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.mt4_term_api.ReconnectDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xc8\x02\n" +
	"\rReconnectData\x124\n" +
	"\x16terminal_was_recreated\x18\x01 \x01(\bR\x14terminalWasRecreated\x12?\n" +
	"\rterminal_type\x18\x02 \x01(\x0e2\x1a.mt4_term_api.TerminalTypeR\fterminalType\x124\n" +
	"\x16terminal_instance_guid\x18\x03 \x01(\tR\x14terminalInstanceGuid\x12K\n" +
	"#old_terminal_full_live_time_seconds\x18\x04 \x01(\x03R\x1eoldTerminalFullLiveTimeSeconds\x12=\n" +
	"\rold_log_files\x18\x05 \x03(\v2\x19.mt4_term_api.LogFileInfoR\voldLogFiles\"\xe2\x03\n" +
	"\x0eConnectRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12/\n" +
	"\x11base_chart_symbol\x18\x05 \x01(\tH\x00R\x0fbaseChartSymbol\x88\x01\x01\x12?\n" +
	"\x1await_for_terminal_is_alive\x18\x06 \x01(\bH\x01R\x16waitForTerminalIsAlive\x88\x01\x01\x12_\n" +
	"*terminal_readiness_waiting_timeout_seconds\x18\a \x01(\x05H\x02R&terminalReadinessWaitingTimeoutSeconds\x88\x01\x01\x12A\n" +
	"\x0eexperts_to_add\x18\b \x03(\v2\x1b.mt4_term_api.ExpertAdviserR\fexpertsToAddB\x14\n" +
	"\x12_base_chart_symbolB\x1d\n" +
	"\x1b_wait_for_terminal_is_aliveB-\n" +
	"+_terminal_readiness_waiting_timeout_seconds\"O\n" +
	"\rExpertAdviser\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"x\n" +
	"\fConnectReply\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x19.mt4_term_api.ConnectDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x84\x01\n" +
	"\vConnectData\x124\n" +
	"\x16terminal_instance_guid\x18\x01 \x01(\tR\x14terminalInstanceGuid\x12?\n" +
	"\rterminal_type\x18\x03 \x01(\x0e2\x1a.mt4_term_api.TerminalTypeR\fterminalType\"\x9f\x05\n" +
	"\x13ConnectProxyRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1c\n" +
	"\tproxyUser\x18\x05 \x01(\tR\tproxyUser\x12$\n" +
	"\rproxyPassword\x18\x06 \x01(\tR\rproxyPassword\x12\x1c\n" +
	"\tproxyHost\x18\a \x01(\tR\tproxyHost\x12\x1c\n" +
	"\tproxyPort\x18\b \x01(\rR\tproxyPort\x126\n" +
	"\tproxyType\x18\t \x01(\x0e2\x18.mt4_term_api.ProxyTypesR\tproxyType\x12/\n" +
	"\x11base_chart_symbol\x18\n" +
	" \x01(\tH\x00R\x0fbaseChartSymbol\x88\x01\x01\x12?\n" +
	"\x1await_for_terminal_is_alive\x18\v \x01(\bH\x01R\x16waitForTerminalIsAlive\x88\x01\x01\x12_\n" +
	"*terminal_readiness_waiting_timeout_seconds\x18\f \x01(\x05H\x02R&terminalReadinessWaitingTimeoutSeconds\x88\x01\x01\x12A\n" +
	"\x0eexperts_to_add\x18\r \x03(\v2\x1b.mt4_term_api.ExpertAdviserR\fexpertsToAddB\x14\n" +
	"\x12_base_chart_symbolB\x1d\n" +
	"\x1b_wait_for_terminal_is_aliveB-\n" +
	"+_terminal_readiness_waiting_timeout_seconds\"\x82\x01\n" +
	"\x11ConnectProxyReply\x124\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.mt4_term_api.ConnectProxyDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x80\x01\n" +
	"\x10ConnectProxyData\x12+\n" +
	"\x11unique_identifier\x18\x01 \x01(\tR\x10uniqueIdentifier\x12?\n" +
	"\rterminal_type\x18\x02 \x01(\x0e2\x1a.mt4_term_api.TerminalTypeR\fterminalType\"\x15\n" +
	"\x13CheckConnectRequest\"\x82\x01\n" +
	"\x11CheckConnectReply\x124\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.mt4_term_api.CheckConnectDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x85\x01\n" +
	"\x10CheckConnectData\x12+\n" +
	"\x11unique_identifier\x18\x01 \x01(\tR\x10uniqueIdentifier\x12D\n" +
	"\fhealth_check\x18\x02 \x01(\v2!.mt4_term_api.TerminalHealthCheckR\vhealthCheck\"\x91\x03\n" +
	"\x13TerminalHealthCheck\x12\x19\n" +
	"\bis_alive\x18\x01 \x01(\bR\aisAlive\x12@\n" +
	"\fErrorMessage\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\fErrorMessage\x12:\n" +
	"\tErrorCode\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\tErrorCode\x12<\n" +
	"\n" +
	"StackTrace\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"StackTrace\x126\n" +
	"\x17has_authorization_error\x18\x05 \x01(\bR\x15hasAuthorizationError\x12 \n" +
	"\fapi_is_alive\x18\x06 \x01(\bR\n" +
	"apiIsAlive\x12I\n" +
	"\"terminal_is_connected_to_mt_server\x18\a \x01(\bR\x1dterminalIsConnectedToMtServer\"\x13\n" +
	"\x11DisconnectRequest\"~\n" +
	"\x0fDisconnectReply\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.mt4_term_api.DisconnectDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"r\n" +
	"\x0eDisconnectData\x12+\n" +
	"\x11unique_identifier\x18\x01 \x01(\tR\x10uniqueIdentifier\x123\n" +
	"\x16full_life_time_seconds\x18\x02 \x01(\x03R\x13fullLifeTimeSeconds*9\n" +
	"\n" +
	"ProxyTypes\x12\b\n" +
	"\x04None\x10\x00\x12\t\n" +
	"\x05Https\x10\x01\x12\n" +
	"\n" +
	"\x06Socks4\x10\x02\x12\n" +
	"\n" +
	"\x06Socks5\x10\x03* \n" +
	"\fTerminalType\x12\a\n" +
	"\x03MT4\x10\x00\x12\a\n" +
	"\x03MT5\x10\x012\xda\x04\n" +
	"\n" +
	"Connection\x12]\n" +
	"\tConnectEx\x12\x1e.mt4_term_api.ConnectExRequest\x1a\x1c.mt4_term_api.ConnectExReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/ConnectEx\x12U\n" +
	"\aConnect\x12\x1c.mt4_term_api.ConnectRequest\x1a\x1a.mt4_term_api.ConnectReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/Connect\x12i\n" +
	"\fConnectProxy\x12!.mt4_term_api.ConnectProxyRequest\x1a\x1f.mt4_term_api.ConnectProxyReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/ConnectProxy\x12i\n" +
	"\fCheckConnect\x12!.mt4_term_api.CheckConnectRequest\x1a\x1f.mt4_term_api.CheckConnectReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/CheckConnect\x12a\n" +
	"\n" +
	"Disconnect\x12\x1f.mt4_term_api.DisconnectRequest\x1a\x1d.mt4_term_api.DisconnectReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/Disconnect\x12]\n" +
	"\tReconnect\x12\x1e.mt4_term_api.ReconnectRequest\x1a\x1c.mt4_term_api.ReconnectReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/ReconnectB/Z\x1egithub.com/MetaRPC/GoMT4/pb;pb\xaa\x02\fmt4_term_apib\x06proto3"

var (
	file_mt4_term_api_connection_proto_rawDescOnce sync.Once
	file_mt4_term_api_connection_proto_rawDescData []byte
)

func file_mt4_term_api_connection_proto_rawDescGZIP() []byte {
	file_mt4_term_api_connection_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mt4_term_api_connection_proto_rawDesc), len(file_mt4_term_api_connection_proto_rawDesc)))
	})
	return file_mt4_term_api_connection_proto_rawDescData
}

var file_mt4_term_api_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mt4_term_api_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_mt4_term_api_connection_proto_goTypes = []any{
	(ProxyTypes)(0),                // 0: mt4_term_api.ProxyTypes
	(TerminalType)(0),              // 1: mt4_term_api.TerminalType
	(*ConnectExRequest)(nil),       // 2: mt4_term_api.ConnectExRequest
	(*ConnectExReply)(nil),         // 3: mt4_term_api.ConnectExReply
	(*ReconnectRequest)(nil),       // 4: mt4_term_api.ReconnectRequest
	(*ReconnectReply)(nil),         // 5: mt4_term_api.ReconnectReply
	(*ReconnectData)(nil),          // 6: mt4_term_api.ReconnectData
	(*ConnectRequest)(nil),         // 7: mt4_term_api.ConnectRequest
	(*ExpertAdviser)(nil),          // 8: mt4_term_api.ExpertAdviser
	(*ConnectReply)(nil),           // 9: mt4_term_api.ConnectReply
	(*ConnectData)(nil),            // 10: mt4_term_api.ConnectData
	(*ConnectProxyRequest)(nil),    // 11: mt4_term_api.ConnectProxyRequest
	(*ConnectProxyReply)(nil),      // 12: mt4_term_api.ConnectProxyReply
	(*ConnectProxyData)(nil),       // 13: mt4_term_api.ConnectProxyData
	(*CheckConnectRequest)(nil),    // 14: mt4_term_api.CheckConnectRequest
	(*CheckConnectReply)(nil),      // 15: mt4_term_api.CheckConnectReply
	(*CheckConnectData)(nil),       // 16: mt4_term_api.CheckConnectData
	(*TerminalHealthCheck)(nil),    // 17: mt4_term_api.TerminalHealthCheck
	(*DisconnectRequest)(nil),      // 18: mt4_term_api.DisconnectRequest
	(*DisconnectReply)(nil),        // 19: mt4_term_api.DisconnectReply
	(*DisconnectData)(nil),         // 20: mt4_term_api.DisconnectData
	(*Error)(nil),                  // 21: mt4_term_api.Error
	(*LogFileInfo)(nil),            // 22: mt4_term_api.LogFileInfo
	(*wrapperspb.StringValue)(nil), // 23: google.protobuf.StringValue
}
var file_mt4_term_api_connection_proto_depIdxs = []int32{
	8,  // 0: mt4_term_api.ConnectExRequest.experts_to_add:type_name -> mt4_term_api.ExpertAdviser
	10, // 1: mt4_term_api.ConnectExReply.data:type_name -> mt4_term_api.ConnectData
	21, // 2: mt4_term_api.ConnectExReply.error:type_name -> mt4_term_api.Error
	6,  // 3: mt4_term_api.ReconnectReply.data:type_name -> mt4_term_api.ReconnectData
	21, // 4: mt4_term_api.ReconnectReply.error:type_name -> mt4_term_api.Error
	1,  // 5: mt4_term_api.ReconnectData.terminal_type:type_name -> mt4_term_api.TerminalType
	22, // 6: mt4_term_api.ReconnectData.old_log_files:type_name -> mt4_term_api.LogFileInfo
	8,  // 7: mt4_term_api.ConnectRequest.experts_to_add:type_name -> mt4_term_api.ExpertAdviser
	10, // 8: mt4_term_api.ConnectReply.data:type_name -> mt4_term_api.ConnectData
	21, // 9: mt4_term_api.ConnectReply.error:type_name -> mt4_term_api.Error
	1,  // 10: mt4_term_api.ConnectData.terminal_type:type_name -> mt4_term_api.TerminalType
	0,  // 11: mt4_term_api.ConnectProxyRequest.proxyType:type_name -> mt4_term_api.ProxyTypes
	8,  // 12: mt4_term_api.ConnectProxyRequest.experts_to_add:type_name -> mt4_term_api.ExpertAdviser
	13, // 13: mt4_term_api.ConnectProxyReply.data:type_name -> mt4_term_api.ConnectProxyData
	21, // 14: mt4_term_api.ConnectProxyReply.error:type_name -> mt4_term_api.Error
	1,  // 15: mt4_term_api.ConnectProxyData.terminal_type:type_name -> mt4_term_api.TerminalType
	16, // 16: mt4_term_api.CheckConnectReply.data:type_name -> mt4_term_api.CheckConnectData
	21, // 17: mt4_term_api.CheckConnectReply.error:type_name -> mt4_term_api.Error
	17, // 18: mt4_term_api.CheckConnectData.health_check:type_name -> mt4_term_api.TerminalHealthCheck
	23, // 19: mt4_term_api.TerminalHealthCheck.ErrorMessage:type_name -> google.protobuf.StringValue
	23, // 20: mt4_term_api.TerminalHealthCheck.ErrorCode:type_name -> google.protobuf.StringValue
	23, // 21: mt4_term_api.TerminalHealthCheck.StackTrace:type_name -> google.protobuf.StringValue
	20, // 22: mt4_term_api.DisconnectReply.data:type_name -> mt4_term_api.DisconnectData
	21, // 23: mt4_term_api.DisconnectReply.error:type_name -> mt4_term_api.Error
	2,  // 24: mt4_term_api.Connection.ConnectEx:input_type -> mt4_term_api.ConnectExRequest
	7,  // 25: mt4_term_api.Connection.Connect:input_type -> mt4_term_api.ConnectRequest
	11, // 26: mt4_term_api.Connection.ConnectProxy:input_type -> mt4_term_api.ConnectProxyRequest
	14, // 27: mt4_term_api.Connection.CheckConnect:input_type -> mt4_term_api.CheckConnectRequest
	18, // 28: mt4_term_api.Connection.Disconnect:input_type -> mt4_term_api.DisconnectRequest
	4,  // 29: mt4_term_api.Connection.Reconnect:input_type -> mt4_term_api.ReconnectRequest
	3,  // 30: mt4_term_api.Connection.ConnectEx:output_type -> mt4_term_api.ConnectExReply
	9,  // 31: mt4_term_api.Connection.Connect:output_type -> mt4_term_api.ConnectReply
	12, // 32: mt4_term_api.Connection.ConnectProxy:output_type -> mt4_term_api.ConnectProxyReply
	15, // 33: mt4_term_api.Connection.CheckConnect:output_type -> mt4_term_api.CheckConnectReply
	19, // 34: mt4_term_api.Connection.Disconnect:output_type -> mt4_term_api.DisconnectReply
	5,  // 35: mt4_term_api.Connection.Reconnect:output_type -> mt4_term_api.ReconnectReply
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_mt4_term_api_connection_proto_init() }
func file_mt4_term_api_connection_proto_init() {
	if File_mt4_term_api_connection_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	file_mt4_term_api_connection_proto_msgTypes[0].OneofWrappers = []any{}
	file_mt4_term_api_connection_proto_msgTypes[1].OneofWrappers = []any{
		(*ConnectExReply_Data)(nil),
		(*ConnectExReply_Error)(nil),
	}
	file_mt4_term_api_connection_proto_msgTypes[2].OneofWrappers = []any{}
	file_mt4_term_api_connection_proto_msgTypes[3].OneofWrappers = []any{
		(*ReconnectReply_Data)(nil),
		(*ReconnectReply_Error)(nil),
	}
	file_mt4_term_api_connection_proto_msgTypes[5].OneofWrappers = []any{}
	file_mt4_term_api_connection_proto_msgTypes[7].OneofWrappers = []any{
		(*ConnectReply_Data)(nil),
		(*ConnectReply_Error)(nil),
	}
	file_mt4_term_api_connection_proto_msgTypes[9].OneofWrappers = []any{}
	file_mt4_term_api_connection_proto_msgTypes[10].OneofWrappers = []any{
		(*ConnectProxyReply_Data)(nil),
		(*ConnectProxyReply_Error)(nil),
	}
	file_mt4_term_api_connection_proto_msgTypes[13].OneofWrappers = []any{
		(*CheckConnectReply_Data)(nil),
		(*CheckConnectReply_Error)(nil),
	}
	file_mt4_term_api_connection_proto_msgTypes[17].OneofWrappers = []any{
		(*DisconnectReply_Data)(nil),
		(*DisconnectReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mt4_term_api_connection_proto_rawDesc), len(file_mt4_term_api_connection_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_connection_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_connection_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_connection_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_connection_proto_msgTypes,
	}.Build()
	File_mt4_term_api_connection_proto = out.File
	file_mt4_term_api_connection_proto_goTypes = nil
	file_mt4_term_api_connection_proto_depIdxs = nil
}
