// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: mt4-term-api-subscriptions.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionService_OnTrade_FullMethodName               = "/mt4_term_api.SubscriptionService/OnTrade"
	SubscriptionService_OnOpenedOrdersTickets_FullMethodName = "/mt4_term_api.SubscriptionService/OnOpenedOrdersTickets"
	SubscriptionService_OnOpenedOrdersProfit_FullMethodName  = "/mt4_term_api.SubscriptionService/OnOpenedOrdersProfit"
	SubscriptionService_OnSymbolTick_FullMethodName          = "/mt4_term_api.SubscriptionService/OnSymbolTick"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnTradeReply], error)
	OnOpenedOrdersTickets(ctx context.Context, in *OnOpenedOrdersTicketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnOpenedOrdersTicketsReply], error)
	OnOpenedOrdersProfit(ctx context.Context, in *OnOpenedOrdersProfitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnOpenedOrdersProfitReply], error)
	OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnSymbolTickReply], error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnTradeReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], SubscriptionService_OnTrade_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnTradeRequest, OnTradeReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnTradeClient = grpc.ServerStreamingClient[OnTradeReply]

func (c *subscriptionServiceClient) OnOpenedOrdersTickets(ctx context.Context, in *OnOpenedOrdersTicketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnOpenedOrdersTicketsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[1], SubscriptionService_OnOpenedOrdersTickets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnOpenedOrdersTicketsRequest, OnOpenedOrdersTicketsReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnOpenedOrdersTicketsClient = grpc.ServerStreamingClient[OnOpenedOrdersTicketsReply]

func (c *subscriptionServiceClient) OnOpenedOrdersProfit(ctx context.Context, in *OnOpenedOrdersProfitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnOpenedOrdersProfitReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[2], SubscriptionService_OnOpenedOrdersProfit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnOpenedOrdersProfitRequest, OnOpenedOrdersProfitReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnOpenedOrdersProfitClient = grpc.ServerStreamingClient[OnOpenedOrdersProfitReply]

func (c *subscriptionServiceClient) OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OnSymbolTickReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[3], SubscriptionService_OnSymbolTick_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnSymbolTickRequest, OnSymbolTickReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnSymbolTickClient = grpc.ServerStreamingClient[OnSymbolTickReply]

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility.
type SubscriptionServiceServer interface {
	OnTrade(*OnTradeRequest, grpc.ServerStreamingServer[OnTradeReply]) error
	OnOpenedOrdersTickets(*OnOpenedOrdersTicketsRequest, grpc.ServerStreamingServer[OnOpenedOrdersTicketsReply]) error
	OnOpenedOrdersProfit(*OnOpenedOrdersProfitRequest, grpc.ServerStreamingServer[OnOpenedOrdersProfitReply]) error
	OnSymbolTick(*OnSymbolTickRequest, grpc.ServerStreamingServer[OnSymbolTickReply]) error
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServiceServer struct{}

func (UnimplementedSubscriptionServiceServer) OnTrade(*OnTradeRequest, grpc.ServerStreamingServer[OnTradeReply]) error {
	return status.Errorf(codes.Unimplemented, "method OnTrade not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnOpenedOrdersTickets(*OnOpenedOrdersTicketsRequest, grpc.ServerStreamingServer[OnOpenedOrdersTicketsReply]) error {
	return status.Errorf(codes.Unimplemented, "method OnOpenedOrdersTickets not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnOpenedOrdersProfit(*OnOpenedOrdersProfitRequest, grpc.ServerStreamingServer[OnOpenedOrdersProfitReply]) error {
	return status.Errorf(codes.Unimplemented, "method OnOpenedOrdersProfit not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnSymbolTick(*OnSymbolTickRequest, grpc.ServerStreamingServer[OnSymbolTickReply]) error {
	return status.Errorf(codes.Unimplemented, "method OnSymbolTick not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}
func (UnimplementedSubscriptionServiceServer) testEmbeddedByValue()                             {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_OnTrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnTradeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnTrade(m, &grpc.GenericServerStream[OnTradeRequest, OnTradeReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnTradeServer = grpc.ServerStreamingServer[OnTradeReply]

func _SubscriptionService_OnOpenedOrdersTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnOpenedOrdersTicketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnOpenedOrdersTickets(m, &grpc.GenericServerStream[OnOpenedOrdersTicketsRequest, OnOpenedOrdersTicketsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnOpenedOrdersTicketsServer = grpc.ServerStreamingServer[OnOpenedOrdersTicketsReply]

func _SubscriptionService_OnOpenedOrdersProfit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnOpenedOrdersProfitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnOpenedOrdersProfit(m, &grpc.GenericServerStream[OnOpenedOrdersProfitRequest, OnOpenedOrdersProfitReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnOpenedOrdersProfitServer = grpc.ServerStreamingServer[OnOpenedOrdersProfitReply]

func _SubscriptionService_OnSymbolTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnSymbolTickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnSymbolTick(m, &grpc.GenericServerStream[OnSymbolTickRequest, OnSymbolTickReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_OnSymbolTickServer = grpc.ServerStreamingServer[OnSymbolTickReply]

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnTrade",
			Handler:       _SubscriptionService_OnTrade_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnOpenedOrdersTickets",
			Handler:       _SubscriptionService_OnOpenedOrdersTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnOpenedOrdersProfit",
			Handler:       _SubscriptionService_OnOpenedOrdersProfit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnSymbolTick",
			Handler:       _SubscriptionService_OnSymbolTick_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mt4-term-api-subscriptions.proto",
}
