// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mt4-term-api-trading-helper.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSendOperationType int32

const (
	OrderSendOperationType_OC_OP_BUY       OrderSendOperationType = 0 // Buy operation
	OrderSendOperationType_OC_OP_SELL      OrderSendOperationType = 1 // Sell operation
	OrderSendOperationType_OC_OP_BUYLIMIT  OrderSendOperationType = 2 // Buy limit pending order
	OrderSendOperationType_OC_OP_SELLLIMIT OrderSendOperationType = 3 // Sell limit pending order
	OrderSendOperationType_OC_OP_BUYSTOP   OrderSendOperationType = 4 // Buy stop pending order
	OrderSendOperationType_OC_OP_SELLSTOP  OrderSendOperationType = 5 // Sell stop pending order
)

// Enum value maps for OrderSendOperationType.
var (
	OrderSendOperationType_name = map[int32]string{
		0: "OC_OP_BUY",
		1: "OC_OP_SELL",
		2: "OC_OP_BUYLIMIT",
		3: "OC_OP_SELLLIMIT",
		4: "OC_OP_BUYSTOP",
		5: "OC_OP_SELLSTOP",
	}
	OrderSendOperationType_value = map[string]int32{
		"OC_OP_BUY":       0,
		"OC_OP_SELL":      1,
		"OC_OP_BUYLIMIT":  2,
		"OC_OP_SELLLIMIT": 3,
		"OC_OP_BUYSTOP":   4,
		"OC_OP_SELLSTOP":  5,
	}
)

func (x OrderSendOperationType) Enum() *OrderSendOperationType {
	p := new(OrderSendOperationType)
	*p = x
	return p
}

func (x OrderSendOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSendOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_trading_helper_proto_enumTypes[0].Descriptor()
}

func (OrderSendOperationType) Type() protoreflect.EnumType {
	return &file_mt4_term_api_trading_helper_proto_enumTypes[0]
}

func (x OrderSendOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSendOperationType.Descriptor instead.
func (OrderSendOperationType) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{0}
}

type OrderCloseDeleteMode int32

const (
	OrderCloseDeleteMode_OCD_MARKET_ORDER  OrderCloseDeleteMode = 0
	OrderCloseDeleteMode_OCD_PENDING_ORDER OrderCloseDeleteMode = 1
)

// Enum value maps for OrderCloseDeleteMode.
var (
	OrderCloseDeleteMode_name = map[int32]string{
		0: "OCD_MARKET_ORDER",
		1: "OCD_PENDING_ORDER",
	}
	OrderCloseDeleteMode_value = map[string]int32{
		"OCD_MARKET_ORDER":  0,
		"OCD_PENDING_ORDER": 1,
	}
)

func (x OrderCloseDeleteMode) Enum() *OrderCloseDeleteMode {
	p := new(OrderCloseDeleteMode)
	*p = x
	return p
}

func (x OrderCloseDeleteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCloseDeleteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_trading_helper_proto_enumTypes[1].Descriptor()
}

func (OrderCloseDeleteMode) Type() protoreflect.EnumType {
	return &file_mt4_term_api_trading_helper_proto_enumTypes[1]
}

func (x OrderCloseDeleteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCloseDeleteMode.Descriptor instead.
func (OrderCloseDeleteMode) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{1}
}

type OrderCloseByRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TicketToClose           int32                  `protobuf:"varint,1,opt,name=ticket_to_close,json=ticketToClose,proto3" json:"ticket_to_close,omitempty"`
	OppositeTicketClosingBy int32                  `protobuf:"varint,2,opt,name=opposite_ticket_closing_by,json=oppositeTicketClosingBy,proto3" json:"opposite_ticket_closing_by,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrderCloseByRequest) Reset() {
	*x = OrderCloseByRequest{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseByRequest) ProtoMessage() {}

func (x *OrderCloseByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseByRequest.ProtoReflect.Descriptor instead.
func (*OrderCloseByRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCloseByRequest) GetTicketToClose() int32 {
	if x != nil {
		return x.TicketToClose
	}
	return 0
}

func (x *OrderCloseByRequest) GetOppositeTicketClosingBy() int32 {
	if x != nil {
		return x.OppositeTicketClosingBy
	}
	return 0
}

type OrderCloseByReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OrderCloseByReply_Data
	//	*OrderCloseByReply_Error
	Response      isOrderCloseByReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCloseByReply) Reset() {
	*x = OrderCloseByReply{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseByReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseByReply) ProtoMessage() {}

func (x *OrderCloseByReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseByReply.ProtoReflect.Descriptor instead.
func (*OrderCloseByReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCloseByReply) GetResponse() isOrderCloseByReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OrderCloseByReply) GetData() *OrderCloseByData {
	if x != nil {
		if x, ok := x.Response.(*OrderCloseByReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OrderCloseByReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OrderCloseByReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOrderCloseByReply_Response interface {
	isOrderCloseByReply_Response()
}

type OrderCloseByReply_Data struct {
	Data *OrderCloseByData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderCloseByReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderCloseByReply_Data) isOrderCloseByReply_Response() {}

func (*OrderCloseByReply_Error) isOrderCloseByReply_Response() {}

type OrderCloseByData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClosePrice    float64                `protobuf:"fixed64,1,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	Profit        float64                `protobuf:"fixed64,2,opt,name=profit,proto3" json:"profit,omitempty"`
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCloseByData) Reset() {
	*x = OrderCloseByData{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseByData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseByData) ProtoMessage() {}

func (x *OrderCloseByData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseByData.ProtoReflect.Descriptor instead.
func (*OrderCloseByData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCloseByData) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *OrderCloseByData) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *OrderCloseByData) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

type OrderSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                                              // Required, NOT EMPTY string
	OperationType OrderSendOperationType `protobuf:"varint,2,opt,name=operation_type,json=operationType,proto3,enum=mt4_term_api.OrderSendOperationType" json:"operation_type,omitempty"` // required
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`                                                                            //Required
	Price         *float64               `protobuf:"fixed64,4,opt,name=price,proto3,oneof" json:"price,omitempty"`                                                                        // NOT required in case of Mt4_OP_BUY = 0; Mt4_OP_SELL = 1;
	Slippage      *int32                 `protobuf:"varint,5,opt,name=slippage,proto3,oneof" json:"slippage,omitempty"`                                                                   // not required default 0
	Stoploss      *float64               `protobuf:"fixed64,6,opt,name=stoploss,proto3,oneof" json:"stoploss,omitempty"`                                                                  // not required default 0
	Takeprofit    *float64               `protobuf:"fixed64,7,opt,name=takeprofit,proto3,oneof" json:"takeprofit,omitempty"`                                                              // not required default 0
	Comment       *string                `protobuf:"bytes,8,opt,name=comment,proto3,oneof" json:"comment,omitempty"`                                                                      // not required default null
	MagicNumber   *int32                 `protobuf:"varint,9,opt,name=magic_number,json=magicNumber,proto3,oneof" json:"magic_number,omitempty"`                                          // not required default 0
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`                                                               // not required default null
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSendRequest) Reset() {
	*x = OrderSendRequest{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSendRequest) ProtoMessage() {}

func (x *OrderSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSendRequest.ProtoReflect.Descriptor instead.
func (*OrderSendRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{3}
}

func (x *OrderSendRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderSendRequest) GetOperationType() OrderSendOperationType {
	if x != nil {
		return x.OperationType
	}
	return OrderSendOperationType_OC_OP_BUY
}

func (x *OrderSendRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OrderSendRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *OrderSendRequest) GetSlippage() int32 {
	if x != nil && x.Slippage != nil {
		return *x.Slippage
	}
	return 0
}

func (x *OrderSendRequest) GetStoploss() float64 {
	if x != nil && x.Stoploss != nil {
		return *x.Stoploss
	}
	return 0
}

func (x *OrderSendRequest) GetTakeprofit() float64 {
	if x != nil && x.Takeprofit != nil {
		return *x.Takeprofit
	}
	return 0
}

func (x *OrderSendRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *OrderSendRequest) GetMagicNumber() int32 {
	if x != nil && x.MagicNumber != nil {
		return *x.MagicNumber
	}
	return 0
}

func (x *OrderSendRequest) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type OrderSendReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OrderSendReply_Data
	//	*OrderSendReply_Error
	Response      isOrderSendReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSendReply) Reset() {
	*x = OrderSendReply{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSendReply) ProtoMessage() {}

func (x *OrderSendReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSendReply.ProtoReflect.Descriptor instead.
func (*OrderSendReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{4}
}

func (x *OrderSendReply) GetResponse() isOrderSendReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OrderSendReply) GetData() *OrderSendData {
	if x != nil {
		if x, ok := x.Response.(*OrderSendReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OrderSendReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OrderSendReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOrderSendReply_Response interface {
	isOrderSendReply_Response()
}

type OrderSendReply_Data struct {
	Data *OrderSendData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderSendReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderSendReply_Data) isOrderSendReply_Response() {}

func (*OrderSendReply_Error) isOrderSendReply_Response() {}

type OrderSendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        int32                  `protobuf:"varint,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Volume        float64                `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSendData) Reset() {
	*x = OrderSendData{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSendData) ProtoMessage() {}

func (x *OrderSendData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSendData.ProtoReflect.Descriptor instead.
func (*OrderSendData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{5}
}

func (x *OrderSendData) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *OrderSendData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OrderSendData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderSendData) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

type OrderModifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderTicket   int32                  `protobuf:"varint,1,opt,name=order_ticket,json=orderTicket,proto3" json:"order_ticket,omitempty"`
	NewPrice      *float64               `protobuf:"fixed64,2,opt,name=new_price,json=newPrice,proto3,oneof" json:"new_price,omitempty"`
	NewStopLoss   *float64               `protobuf:"fixed64,3,opt,name=new_stop_loss,json=newStopLoss,proto3,oneof" json:"new_stop_loss,omitempty"`
	NewTakeProfit *float64               `protobuf:"fixed64,4,opt,name=new_take_profit,json=newTakeProfit,proto3,oneof" json:"new_take_profit,omitempty"`
	NewExpiration *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=new_expiration,json=newExpiration,proto3,oneof" json:"new_expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderModifyRequest) Reset() {
	*x = OrderModifyRequest{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderModifyRequest) ProtoMessage() {}

func (x *OrderModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderModifyRequest.ProtoReflect.Descriptor instead.
func (*OrderModifyRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{6}
}

func (x *OrderModifyRequest) GetOrderTicket() int32 {
	if x != nil {
		return x.OrderTicket
	}
	return 0
}

func (x *OrderModifyRequest) GetNewPrice() float64 {
	if x != nil && x.NewPrice != nil {
		return *x.NewPrice
	}
	return 0
}

func (x *OrderModifyRequest) GetNewStopLoss() float64 {
	if x != nil && x.NewStopLoss != nil {
		return *x.NewStopLoss
	}
	return 0
}

func (x *OrderModifyRequest) GetNewTakeProfit() float64 {
	if x != nil && x.NewTakeProfit != nil {
		return *x.NewTakeProfit
	}
	return 0
}

func (x *OrderModifyRequest) GetNewExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiration
	}
	return nil
}

type OrderModifyReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OrderModifyReply_Data
	//	*OrderModifyReply_Error
	Response      isOrderModifyReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderModifyReply) Reset() {
	*x = OrderModifyReply{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderModifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderModifyReply) ProtoMessage() {}

func (x *OrderModifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderModifyReply.ProtoReflect.Descriptor instead.
func (*OrderModifyReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{7}
}

func (x *OrderModifyReply) GetResponse() isOrderModifyReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OrderModifyReply) GetData() *OrderModifyData {
	if x != nil {
		if x, ok := x.Response.(*OrderModifyReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OrderModifyReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OrderModifyReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOrderModifyReply_Response interface {
	isOrderModifyReply_Response()
}

type OrderModifyReply_Data struct {
	Data *OrderModifyData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderModifyReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderModifyReply_Data) isOrderModifyReply_Response() {}

func (*OrderModifyReply_Error) isOrderModifyReply_Response() {}

type OrderModifyData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderWasModified bool                   `protobuf:"varint,1,opt,name=order_was_modified,json=orderWasModified,proto3" json:"order_was_modified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderModifyData) Reset() {
	*x = OrderModifyData{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderModifyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderModifyData) ProtoMessage() {}

func (x *OrderModifyData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderModifyData.ProtoReflect.Descriptor instead.
func (*OrderModifyData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{8}
}

func (x *OrderModifyData) GetOrderWasModified() bool {
	if x != nil {
		return x.OrderWasModified
	}
	return false
}

type OrderCloseDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderTicket   int32                  `protobuf:"varint,1,opt,name=order_ticket,json=orderTicket,proto3" json:"order_ticket,omitempty"`
	Lots          *float64               `protobuf:"fixed64,2,opt,name=lots,proto3,oneof" json:"lots,omitempty"`
	ClosingPrice  *float64               `protobuf:"fixed64,3,opt,name=closing_price,json=closingPrice,proto3,oneof" json:"closing_price,omitempty"`
	Slippage      *int32                 `protobuf:"varint,4,opt,name=slippage,proto3,oneof" json:"slippage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCloseDeleteRequest) Reset() {
	*x = OrderCloseDeleteRequest{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseDeleteRequest) ProtoMessage() {}

func (x *OrderCloseDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseDeleteRequest.ProtoReflect.Descriptor instead.
func (*OrderCloseDeleteRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{9}
}

func (x *OrderCloseDeleteRequest) GetOrderTicket() int32 {
	if x != nil {
		return x.OrderTicket
	}
	return 0
}

func (x *OrderCloseDeleteRequest) GetLots() float64 {
	if x != nil && x.Lots != nil {
		return *x.Lots
	}
	return 0
}

func (x *OrderCloseDeleteRequest) GetClosingPrice() float64 {
	if x != nil && x.ClosingPrice != nil {
		return *x.ClosingPrice
	}
	return 0
}

func (x *OrderCloseDeleteRequest) GetSlippage() int32 {
	if x != nil && x.Slippage != nil {
		return *x.Slippage
	}
	return 0
}

type OrderCloseDeleteReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OrderCloseDeleteReply_Data
	//	*OrderCloseDeleteReply_Error
	Response      isOrderCloseDeleteReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCloseDeleteReply) Reset() {
	*x = OrderCloseDeleteReply{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseDeleteReply) ProtoMessage() {}

func (x *OrderCloseDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseDeleteReply.ProtoReflect.Descriptor instead.
func (*OrderCloseDeleteReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{10}
}

func (x *OrderCloseDeleteReply) GetResponse() isOrderCloseDeleteReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OrderCloseDeleteReply) GetData() *OrderCloseDeleteData {
	if x != nil {
		if x, ok := x.Response.(*OrderCloseDeleteReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OrderCloseDeleteReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OrderCloseDeleteReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOrderCloseDeleteReply_Response interface {
	isOrderCloseDeleteReply_Response()
}

type OrderCloseDeleteReply_Data struct {
	Data *OrderCloseDeleteData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderCloseDeleteReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderCloseDeleteReply_Data) isOrderCloseDeleteReply_Response() {}

func (*OrderCloseDeleteReply_Error) isOrderCloseDeleteReply_Response() {}

type OrderCloseDeleteData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Mode                OrderCloseDeleteMode   `protobuf:"varint,1,opt,name=mode,proto3,enum=mt4_term_api.OrderCloseDeleteMode" json:"mode,omitempty"`
	HistoryOrderComment *string                `protobuf:"bytes,2,opt,name=history_order_comment,json=historyOrderComment,proto3,oneof" json:"history_order_comment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderCloseDeleteData) Reset() {
	*x = OrderCloseDeleteData{}
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCloseDeleteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCloseDeleteData) ProtoMessage() {}

func (x *OrderCloseDeleteData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_trading_helper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCloseDeleteData.ProtoReflect.Descriptor instead.
func (*OrderCloseDeleteData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_trading_helper_proto_rawDescGZIP(), []int{11}
}

func (x *OrderCloseDeleteData) GetMode() OrderCloseDeleteMode {
	if x != nil {
		return x.Mode
	}
	return OrderCloseDeleteMode_OCD_MARKET_ORDER
}

func (x *OrderCloseDeleteData) GetHistoryOrderComment() string {
	if x != nil && x.HistoryOrderComment != nil {
		return *x.HistoryOrderComment
	}
	return ""
}

var File_mt4_term_api_trading_helper_proto protoreflect.FileDescriptor

const file_mt4_term_api_trading_helper_proto_rawDesc = "" +
	"\n" +
	"!mt4-term-api-trading-helper.proto\x12\fmt4_term_api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14mrpc-mt4-error.proto\"z\n" +
	"\x13OrderCloseByRequest\x12&\n" +
	"\x0fticket_to_close\x18\x01 \x01(\x05R\rticketToClose\x12;\n" +
	"\x1aopposite_ticket_closing_by\x18\x02 \x01(\x05R\x17oppositeTicketClosingBy\"\x82\x01\n" +
	"\x11OrderCloseByReply\x124\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.mt4_term_api.OrderCloseByDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x86\x01\n" +
	"\x10OrderCloseByData\x12\x1f\n" +
	"\vclose_price\x18\x01 \x01(\x01R\n" +
	"closePrice\x12\x16\n" +
	"\x06profit\x18\x02 \x01(\x01R\x06profit\x129\n" +
	"\n" +
	"close_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\"\xf8\x03\n" +
	"\x10OrderSendRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12K\n" +
	"\x0eoperation_type\x18\x02 \x01(\x0e2$.mt4_term_api.OrderSendOperationTypeR\roperationType\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x01H\x00R\x05price\x88\x01\x01\x12\x1f\n" +
	"\bslippage\x18\x05 \x01(\x05H\x01R\bslippage\x88\x01\x01\x12\x1f\n" +
	"\bstoploss\x18\x06 \x01(\x01H\x02R\bstoploss\x88\x01\x01\x12#\n" +
	"\n" +
	"takeprofit\x18\a \x01(\x01H\x03R\n" +
	"takeprofit\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\b \x01(\tH\x04R\acomment\x88\x01\x01\x12&\n" +
	"\fmagic_number\x18\t \x01(\x05H\x05R\vmagicNumber\x88\x01\x01\x12?\n" +
	"\n" +
	"expiration\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x06R\n" +
	"expiration\x88\x01\x01B\b\n" +
	"\x06_priceB\v\n" +
	"\t_slippageB\v\n" +
	"\t_stoplossB\r\n" +
	"\v_takeprofitB\n" +
	"\n" +
	"\b_commentB\x0f\n" +
	"\r_magic_numberB\r\n" +
	"\v_expiration\"|\n" +
	"\x0eOrderSendReply\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.mt4_term_api.OrderSendDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x8e\x01\n" +
	"\rOrderSendData\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\x05R\x06ticket\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x127\n" +
	"\topen_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\"\xbe\x02\n" +
	"\x12OrderModifyRequest\x12!\n" +
	"\forder_ticket\x18\x01 \x01(\x05R\vorderTicket\x12 \n" +
	"\tnew_price\x18\x02 \x01(\x01H\x00R\bnewPrice\x88\x01\x01\x12'\n" +
	"\rnew_stop_loss\x18\x03 \x01(\x01H\x01R\vnewStopLoss\x88\x01\x01\x12+\n" +
	"\x0fnew_take_profit\x18\x04 \x01(\x01H\x02R\rnewTakeProfit\x88\x01\x01\x12F\n" +
	"\x0enew_expiration\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rnewExpiration\x88\x01\x01B\f\n" +
	"\n" +
	"_new_priceB\x10\n" +
	"\x0e_new_stop_lossB\x12\n" +
	"\x10_new_take_profitB\x11\n" +
	"\x0f_new_expiration\"\x80\x01\n" +
	"\x10OrderModifyReply\x123\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.mt4_term_api.OrderModifyDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"?\n" +
	"\x0fOrderModifyData\x12,\n" +
	"\x12order_was_modified\x18\x01 \x01(\bR\x10orderWasModified\"\xc8\x01\n" +
	"\x17OrderCloseDeleteRequest\x12!\n" +
	"\forder_ticket\x18\x01 \x01(\x05R\vorderTicket\x12\x17\n" +
	"\x04lots\x18\x02 \x01(\x01H\x00R\x04lots\x88\x01\x01\x12(\n" +
	"\rclosing_price\x18\x03 \x01(\x01H\x01R\fclosingPrice\x88\x01\x01\x12\x1f\n" +
	"\bslippage\x18\x04 \x01(\x05H\x02R\bslippage\x88\x01\x01B\a\n" +
	"\x05_lotsB\x10\n" +
	"\x0e_closing_priceB\v\n" +
	"\t_slippage\"\x8a\x01\n" +
	"\x15OrderCloseDeleteReply\x128\n" +
	"\x04data\x18\x01 \x01(\v2\".mt4_term_api.OrderCloseDeleteDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xa1\x01\n" +
	"\x14OrderCloseDeleteData\x126\n" +
	"\x04mode\x18\x01 \x01(\x0e2\".mt4_term_api.OrderCloseDeleteModeR\x04mode\x127\n" +
	"\x15history_order_comment\x18\x02 \x01(\tH\x00R\x13historyOrderComment\x88\x01\x01B\x18\n" +
	"\x16_history_order_comment*\x87\x01\n" +
	"\x16OrderSendOperationType\x12\r\n" +
	"\tOC_OP_BUY\x10\x00\x12\x0e\n" +
	"\n" +
	"OC_OP_SELL\x10\x01\x12\x12\n" +
	"\x0eOC_OP_BUYLIMIT\x10\x02\x12\x13\n" +
	"\x0fOC_OP_SELLLIMIT\x10\x03\x12\x11\n" +
	"\rOC_OP_BUYSTOP\x10\x04\x12\x12\n" +
	"\x0eOC_OP_SELLSTOP\x10\x05*C\n" +
	"\x14OrderCloseDeleteMode\x12\x14\n" +
	"\x10OCD_MARKET_ORDER\x10\x00\x12\x15\n" +
	"\x11OCD_PENDING_ORDER\x10\x012\xbb\x03\n" +
	"\rTradingHelper\x12]\n" +
	"\tOrderSend\x12\x1e.mt4_term_api.OrderSendRequest\x1a\x1c.mt4_term_api.OrderSendReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/OrderSend\x12e\n" +
	"\vOrderModify\x12 .mt4_term_api.OrderModifyRequest\x1a\x1e.mt4_term_api.OrderModifyReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/OrderModify\x12y\n" +
	"\x10OrderCloseDelete\x12%.mt4_term_api.OrderCloseDeleteRequest\x1a#.mt4_term_api.OrderCloseDeleteReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/OrderCloseDelete\x12i\n" +
	"\fOrderCloseBy\x12!.mt4_term_api.OrderCloseByRequest\x1a\x1f.mt4_term_api.OrderCloseByReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/OrderCloseByB/Z\x1egithub.com/MetaRPC/GoMT4/pb;pb\xaa\x02\fmt4_term_apib\x06proto3"

var (
	file_mt4_term_api_trading_helper_proto_rawDescOnce sync.Once
	file_mt4_term_api_trading_helper_proto_rawDescData []byte
)

func file_mt4_term_api_trading_helper_proto_rawDescGZIP() []byte {
	file_mt4_term_api_trading_helper_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_trading_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mt4_term_api_trading_helper_proto_rawDesc), len(file_mt4_term_api_trading_helper_proto_rawDesc)))
	})
	return file_mt4_term_api_trading_helper_proto_rawDescData
}

var file_mt4_term_api_trading_helper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mt4_term_api_trading_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mt4_term_api_trading_helper_proto_goTypes = []any{
	(OrderSendOperationType)(0),     // 0: mt4_term_api.OrderSendOperationType
	(OrderCloseDeleteMode)(0),       // 1: mt4_term_api.OrderCloseDeleteMode
	(*OrderCloseByRequest)(nil),     // 2: mt4_term_api.OrderCloseByRequest
	(*OrderCloseByReply)(nil),       // 3: mt4_term_api.OrderCloseByReply
	(*OrderCloseByData)(nil),        // 4: mt4_term_api.OrderCloseByData
	(*OrderSendRequest)(nil),        // 5: mt4_term_api.OrderSendRequest
	(*OrderSendReply)(nil),          // 6: mt4_term_api.OrderSendReply
	(*OrderSendData)(nil),           // 7: mt4_term_api.OrderSendData
	(*OrderModifyRequest)(nil),      // 8: mt4_term_api.OrderModifyRequest
	(*OrderModifyReply)(nil),        // 9: mt4_term_api.OrderModifyReply
	(*OrderModifyData)(nil),         // 10: mt4_term_api.OrderModifyData
	(*OrderCloseDeleteRequest)(nil), // 11: mt4_term_api.OrderCloseDeleteRequest
	(*OrderCloseDeleteReply)(nil),   // 12: mt4_term_api.OrderCloseDeleteReply
	(*OrderCloseDeleteData)(nil),    // 13: mt4_term_api.OrderCloseDeleteData
	(*Error)(nil),                   // 14: mt4_term_api.Error
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_mt4_term_api_trading_helper_proto_depIdxs = []int32{
	4,  // 0: mt4_term_api.OrderCloseByReply.data:type_name -> mt4_term_api.OrderCloseByData
	14, // 1: mt4_term_api.OrderCloseByReply.error:type_name -> mt4_term_api.Error
	15, // 2: mt4_term_api.OrderCloseByData.close_time:type_name -> google.protobuf.Timestamp
	0,  // 3: mt4_term_api.OrderSendRequest.operation_type:type_name -> mt4_term_api.OrderSendOperationType
	15, // 4: mt4_term_api.OrderSendRequest.expiration:type_name -> google.protobuf.Timestamp
	7,  // 5: mt4_term_api.OrderSendReply.data:type_name -> mt4_term_api.OrderSendData
	14, // 6: mt4_term_api.OrderSendReply.error:type_name -> mt4_term_api.Error
	15, // 7: mt4_term_api.OrderSendData.open_time:type_name -> google.protobuf.Timestamp
	15, // 8: mt4_term_api.OrderModifyRequest.new_expiration:type_name -> google.protobuf.Timestamp
	10, // 9: mt4_term_api.OrderModifyReply.data:type_name -> mt4_term_api.OrderModifyData
	14, // 10: mt4_term_api.OrderModifyReply.error:type_name -> mt4_term_api.Error
	13, // 11: mt4_term_api.OrderCloseDeleteReply.data:type_name -> mt4_term_api.OrderCloseDeleteData
	14, // 12: mt4_term_api.OrderCloseDeleteReply.error:type_name -> mt4_term_api.Error
	1,  // 13: mt4_term_api.OrderCloseDeleteData.mode:type_name -> mt4_term_api.OrderCloseDeleteMode
	5,  // 14: mt4_term_api.TradingHelper.OrderSend:input_type -> mt4_term_api.OrderSendRequest
	8,  // 15: mt4_term_api.TradingHelper.OrderModify:input_type -> mt4_term_api.OrderModifyRequest
	11, // 16: mt4_term_api.TradingHelper.OrderCloseDelete:input_type -> mt4_term_api.OrderCloseDeleteRequest
	2,  // 17: mt4_term_api.TradingHelper.OrderCloseBy:input_type -> mt4_term_api.OrderCloseByRequest
	6,  // 18: mt4_term_api.TradingHelper.OrderSend:output_type -> mt4_term_api.OrderSendReply
	9,  // 19: mt4_term_api.TradingHelper.OrderModify:output_type -> mt4_term_api.OrderModifyReply
	12, // 20: mt4_term_api.TradingHelper.OrderCloseDelete:output_type -> mt4_term_api.OrderCloseDeleteReply
	3,  // 21: mt4_term_api.TradingHelper.OrderCloseBy:output_type -> mt4_term_api.OrderCloseByReply
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_mt4_term_api_trading_helper_proto_init() }
func file_mt4_term_api_trading_helper_proto_init() {
	if File_mt4_term_api_trading_helper_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	file_mt4_term_api_trading_helper_proto_msgTypes[1].OneofWrappers = []any{
		(*OrderCloseByReply_Data)(nil),
		(*OrderCloseByReply_Error)(nil),
	}
	file_mt4_term_api_trading_helper_proto_msgTypes[3].OneofWrappers = []any{}
	file_mt4_term_api_trading_helper_proto_msgTypes[4].OneofWrappers = []any{
		(*OrderSendReply_Data)(nil),
		(*OrderSendReply_Error)(nil),
	}
	file_mt4_term_api_trading_helper_proto_msgTypes[6].OneofWrappers = []any{}
	file_mt4_term_api_trading_helper_proto_msgTypes[7].OneofWrappers = []any{
		(*OrderModifyReply_Data)(nil),
		(*OrderModifyReply_Error)(nil),
	}
	file_mt4_term_api_trading_helper_proto_msgTypes[9].OneofWrappers = []any{}
	file_mt4_term_api_trading_helper_proto_msgTypes[10].OneofWrappers = []any{
		(*OrderCloseDeleteReply_Data)(nil),
		(*OrderCloseDeleteReply_Error)(nil),
	}
	file_mt4_term_api_trading_helper_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mt4_term_api_trading_helper_proto_rawDesc), len(file_mt4_term_api_trading_helper_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_trading_helper_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_trading_helper_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_trading_helper_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_trading_helper_proto_msgTypes,
	}.Build()
	File_mt4_term_api_trading_helper_proto = out.File
	file_mt4_term_api_trading_helper_proto_goTypes = nil
	file_mt4_term_api_trading_helper_proto_depIdxs = nil
}
