// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: mt4-term-api-market-info.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketInfo_Quote_FullMethodName        = "/mt4_term_api.MarketInfo/Quote"
	MarketInfo_QuoteMany_FullMethodName    = "/mt4_term_api.MarketInfo/QuoteMany"
	MarketInfo_Symbols_FullMethodName      = "/mt4_term_api.MarketInfo/Symbols"
	MarketInfo_QuoteHistory_FullMethodName = "/mt4_term_api.MarketInfo/QuoteHistory"
)

// MarketInfoClient is the client API for MarketInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketInfoClient interface {
	// Get quote
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error)
	// Latest quote for the specified symbol
	QuoteMany(ctx context.Context, in *QuoteManyRequest, opts ...grpc.CallOption) (*QuoteManyReply, error)
	Symbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsReply, error)
	QuoteHistory(ctx context.Context, in *QuoteHistoryRequest, opts ...grpc.CallOption) (*QuoteHistoryReply, error)
}

type marketInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketInfoClient(cc grpc.ClientConnInterface) MarketInfoClient {
	return &marketInfoClient{cc}
}

func (c *marketInfoClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteReply)
	err := c.cc.Invoke(ctx, MarketInfo_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) QuoteMany(ctx context.Context, in *QuoteManyRequest, opts ...grpc.CallOption) (*QuoteManyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteManyReply)
	err := c.cc.Invoke(ctx, MarketInfo_QuoteMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) Symbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymbolsReply)
	err := c.cc.Invoke(ctx, MarketInfo_Symbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) QuoteHistory(ctx context.Context, in *QuoteHistoryRequest, opts ...grpc.CallOption) (*QuoteHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteHistoryReply)
	err := c.cc.Invoke(ctx, MarketInfo_QuoteHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketInfoServer is the server API for MarketInfo service.
// All implementations must embed UnimplementedMarketInfoServer
// for forward compatibility.
type MarketInfoServer interface {
	// Get quote
	Quote(context.Context, *QuoteRequest) (*QuoteReply, error)
	// Latest quote for the specified symbol
	QuoteMany(context.Context, *QuoteManyRequest) (*QuoteManyReply, error)
	Symbols(context.Context, *SymbolsRequest) (*SymbolsReply, error)
	QuoteHistory(context.Context, *QuoteHistoryRequest) (*QuoteHistoryReply, error)
	mustEmbedUnimplementedMarketInfoServer()
}

// UnimplementedMarketInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketInfoServer struct{}

func (UnimplementedMarketInfoServer) Quote(context.Context, *QuoteRequest) (*QuoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedMarketInfoServer) QuoteMany(context.Context, *QuoteManyRequest) (*QuoteManyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteMany not implemented")
}
func (UnimplementedMarketInfoServer) Symbols(context.Context, *SymbolsRequest) (*SymbolsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Symbols not implemented")
}
func (UnimplementedMarketInfoServer) QuoteHistory(context.Context, *QuoteHistoryRequest) (*QuoteHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteHistory not implemented")
}
func (UnimplementedMarketInfoServer) mustEmbedUnimplementedMarketInfoServer() {}
func (UnimplementedMarketInfoServer) testEmbeddedByValue()                    {}

// UnsafeMarketInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketInfoServer will
// result in compilation errors.
type UnsafeMarketInfoServer interface {
	mustEmbedUnimplementedMarketInfoServer()
}

func RegisterMarketInfoServer(s grpc.ServiceRegistrar, srv MarketInfoServer) {
	// If the following call pancis, it indicates UnimplementedMarketInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketInfo_ServiceDesc, srv)
}

func _MarketInfo_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketInfo_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_QuoteMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).QuoteMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketInfo_QuoteMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).QuoteMany(ctx, req.(*QuoteManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_Symbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).Symbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketInfo_Symbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).Symbols(ctx, req.(*SymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_QuoteHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).QuoteHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketInfo_QuoteHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).QuoteHistory(ctx, req.(*QuoteHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketInfo_ServiceDesc is the grpc.ServiceDesc for MarketInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.MarketInfo",
	HandlerType: (*MarketInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quote",
			Handler:    _MarketInfo_Quote_Handler,
		},
		{
			MethodName: "QuoteMany",
			Handler:    _MarketInfo_QuoteMany_Handler,
		},
		{
			MethodName: "Symbols",
			Handler:    _MarketInfo_Symbols_Handler,
		},
		{
			MethodName: "QuoteHistory",
			Handler:    _MarketInfo_QuoteHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt4-term-api-market-info.proto",
}
