// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mt4-term-api-charts.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EA_PARAM_TYPE int32

const (
	EA_PARAM_TYPE_EA_PARAM_TYPE_UNDEFINED EA_PARAM_TYPE = 0
	EA_PARAM_TYPE_EA_PARAM_TYPE_STRING    EA_PARAM_TYPE = 1
	EA_PARAM_TYPE_EA_PARAM_TYPE_INTEGER   EA_PARAM_TYPE = 2
	EA_PARAM_TYPE_EA_PARAM_TYPE_DOUBLE    EA_PARAM_TYPE = 3
	EA_PARAM_TYPE_EA_PARAM_TYPE_BOOLEAN   EA_PARAM_TYPE = 4
)

// Enum value maps for EA_PARAM_TYPE.
var (
	EA_PARAM_TYPE_name = map[int32]string{
		0: "EA_PARAM_TYPE_UNDEFINED",
		1: "EA_PARAM_TYPE_STRING",
		2: "EA_PARAM_TYPE_INTEGER",
		3: "EA_PARAM_TYPE_DOUBLE",
		4: "EA_PARAM_TYPE_BOOLEAN",
	}
	EA_PARAM_TYPE_value = map[string]int32{
		"EA_PARAM_TYPE_UNDEFINED": 0,
		"EA_PARAM_TYPE_STRING":    1,
		"EA_PARAM_TYPE_INTEGER":   2,
		"EA_PARAM_TYPE_DOUBLE":    3,
		"EA_PARAM_TYPE_BOOLEAN":   4,
	}
)

func (x EA_PARAM_TYPE) Enum() *EA_PARAM_TYPE {
	p := new(EA_PARAM_TYPE)
	*p = x
	return p
}

func (x EA_PARAM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EA_PARAM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_charts_proto_enumTypes[0].Descriptor()
}

func (EA_PARAM_TYPE) Type() protoreflect.EnumType {
	return &file_mt4_term_api_charts_proto_enumTypes[0]
}

func (x EA_PARAM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EA_PARAM_TYPE.Descriptor instead.
func (EA_PARAM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{0}
}

type EnumOpenTerminalChartWithEaParameterType int32

const (
	EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_INT    EnumOpenTerminalChartWithEaParameterType = 0
	EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_LONG   EnumOpenTerminalChartWithEaParameterType = 1
	EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_BOOL   EnumOpenTerminalChartWithEaParameterType = 2
	EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_STRING EnumOpenTerminalChartWithEaParameterType = 3
	EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_DOUBLE EnumOpenTerminalChartWithEaParameterType = 4
)

// Enum value maps for EnumOpenTerminalChartWithEaParameterType.
var (
	EnumOpenTerminalChartWithEaParameterType_name = map[int32]string{
		0: "MRPC_EA_PARAM_INT",
		1: "MRPC_EA_PARAM_LONG",
		2: "MRPC_EA_PARAM_BOOL",
		3: "MRPC_EA_PARAM_STRING",
		4: "MRPC_EA_PARAM_DOUBLE",
	}
	EnumOpenTerminalChartWithEaParameterType_value = map[string]int32{
		"MRPC_EA_PARAM_INT":    0,
		"MRPC_EA_PARAM_LONG":   1,
		"MRPC_EA_PARAM_BOOL":   2,
		"MRPC_EA_PARAM_STRING": 3,
		"MRPC_EA_PARAM_DOUBLE": 4,
	}
)

func (x EnumOpenTerminalChartWithEaParameterType) Enum() *EnumOpenTerminalChartWithEaParameterType {
	p := new(EnumOpenTerminalChartWithEaParameterType)
	*p = x
	return p
}

func (x EnumOpenTerminalChartWithEaParameterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumOpenTerminalChartWithEaParameterType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_charts_proto_enumTypes[1].Descriptor()
}

func (EnumOpenTerminalChartWithEaParameterType) Type() protoreflect.EnumType {
	return &file_mt4_term_api_charts_proto_enumTypes[1]
}

func (x EnumOpenTerminalChartWithEaParameterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumOpenTerminalChartWithEaParameterType.Descriptor instead.
func (EnumOpenTerminalChartWithEaParameterType) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{1}
}

type EnumOpenTerminalChartWithEaChatPeriod int32

const (
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_CURRENT EnumOpenTerminalChartWithEaChatPeriod = 0
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M1      EnumOpenTerminalChartWithEaChatPeriod = 1
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M2      EnumOpenTerminalChartWithEaChatPeriod = 2
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M3      EnumOpenTerminalChartWithEaChatPeriod = 3
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M4      EnumOpenTerminalChartWithEaChatPeriod = 4
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M5      EnumOpenTerminalChartWithEaChatPeriod = 5
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M6      EnumOpenTerminalChartWithEaChatPeriod = 6
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M10     EnumOpenTerminalChartWithEaChatPeriod = 7
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M12     EnumOpenTerminalChartWithEaChatPeriod = 8
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M15     EnumOpenTerminalChartWithEaChatPeriod = 9
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M20     EnumOpenTerminalChartWithEaChatPeriod = 10
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_M30     EnumOpenTerminalChartWithEaChatPeriod = 11
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H1      EnumOpenTerminalChartWithEaChatPeriod = 12
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H2      EnumOpenTerminalChartWithEaChatPeriod = 13
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H3      EnumOpenTerminalChartWithEaChatPeriod = 14
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H4      EnumOpenTerminalChartWithEaChatPeriod = 15
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H6      EnumOpenTerminalChartWithEaChatPeriod = 16
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H8      EnumOpenTerminalChartWithEaChatPeriod = 17
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_H12     EnumOpenTerminalChartWithEaChatPeriod = 18
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_D1      EnumOpenTerminalChartWithEaChatPeriod = 19
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_W1      EnumOpenTerminalChartWithEaChatPeriod = 20
	EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_MN1     EnumOpenTerminalChartWithEaChatPeriod = 21
)

// Enum value maps for EnumOpenTerminalChartWithEaChatPeriod.
var (
	EnumOpenTerminalChartWithEaChatPeriod_name = map[int32]string{
		0:  "MRPC_EA_CHART_PERIOD_CURRENT",
		1:  "MRPC_EA_CHART_PERIOD_M1",
		2:  "MRPC_EA_CHART_PERIOD_M2",
		3:  "MRPC_EA_CHART_PERIOD_M3",
		4:  "MRPC_EA_CHART_PERIOD_M4",
		5:  "MRPC_EA_CHART_PERIOD_M5",
		6:  "MRPC_EA_CHART_PERIOD_M6",
		7:  "MRPC_EA_CHART_PERIOD_M10",
		8:  "MRPC_EA_CHART_PERIOD_M12",
		9:  "MRPC_EA_CHART_PERIOD_M15",
		10: "MRPC_EA_CHART_PERIOD_M20",
		11: "MRPC_EA_CHART_PERIOD_M30",
		12: "MRPC_EA_CHART_PERIOD_H1",
		13: "MRPC_EA_CHART_PERIOD_H2",
		14: "MRPC_EA_CHART_PERIOD_H3",
		15: "MRPC_EA_CHART_PERIOD_H4",
		16: "MRPC_EA_CHART_PERIOD_H6",
		17: "MRPC_EA_CHART_PERIOD_H8",
		18: "MRPC_EA_CHART_PERIOD_H12",
		19: "MRPC_EA_CHART_PERIOD_D1",
		20: "MRPC_EA_CHART_PERIOD_W1",
		21: "MRPC_EA_CHART_PERIOD_MN1",
	}
	EnumOpenTerminalChartWithEaChatPeriod_value = map[string]int32{
		"MRPC_EA_CHART_PERIOD_CURRENT": 0,
		"MRPC_EA_CHART_PERIOD_M1":      1,
		"MRPC_EA_CHART_PERIOD_M2":      2,
		"MRPC_EA_CHART_PERIOD_M3":      3,
		"MRPC_EA_CHART_PERIOD_M4":      4,
		"MRPC_EA_CHART_PERIOD_M5":      5,
		"MRPC_EA_CHART_PERIOD_M6":      6,
		"MRPC_EA_CHART_PERIOD_M10":     7,
		"MRPC_EA_CHART_PERIOD_M12":     8,
		"MRPC_EA_CHART_PERIOD_M15":     9,
		"MRPC_EA_CHART_PERIOD_M20":     10,
		"MRPC_EA_CHART_PERIOD_M30":     11,
		"MRPC_EA_CHART_PERIOD_H1":      12,
		"MRPC_EA_CHART_PERIOD_H2":      13,
		"MRPC_EA_CHART_PERIOD_H3":      14,
		"MRPC_EA_CHART_PERIOD_H4":      15,
		"MRPC_EA_CHART_PERIOD_H6":      16,
		"MRPC_EA_CHART_PERIOD_H8":      17,
		"MRPC_EA_CHART_PERIOD_H12":     18,
		"MRPC_EA_CHART_PERIOD_D1":      19,
		"MRPC_EA_CHART_PERIOD_W1":      20,
		"MRPC_EA_CHART_PERIOD_MN1":     21,
	}
)

func (x EnumOpenTerminalChartWithEaChatPeriod) Enum() *EnumOpenTerminalChartWithEaChatPeriod {
	p := new(EnumOpenTerminalChartWithEaChatPeriod)
	*p = x
	return p
}

func (x EnumOpenTerminalChartWithEaChatPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumOpenTerminalChartWithEaChatPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_charts_proto_enumTypes[2].Descriptor()
}

func (EnumOpenTerminalChartWithEaChatPeriod) Type() protoreflect.EnumType {
	return &file_mt4_term_api_charts_proto_enumTypes[2]
}

func (x EnumOpenTerminalChartWithEaChatPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumOpenTerminalChartWithEaChatPeriod.Descriptor instead.
func (EnumOpenTerminalChartWithEaChatPeriod) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{2}
}

type GetEaParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EaFileName    string                 `protobuf:"bytes,1,opt,name=ea_file_name,json=eaFileName,proto3" json:"ea_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEaParamsRequest) Reset() {
	*x = GetEaParamsRequest{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEaParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEaParamsRequest) ProtoMessage() {}

func (x *GetEaParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEaParamsRequest.ProtoReflect.Descriptor instead.
func (*GetEaParamsRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{0}
}

func (x *GetEaParamsRequest) GetEaFileName() string {
	if x != nil {
		return x.EaFileName
	}
	return ""
}

type GetEaParamsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetEaParamsReply_Data
	//	*GetEaParamsReply_Error
	Response      isGetEaParamsReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEaParamsReply) Reset() {
	*x = GetEaParamsReply{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEaParamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEaParamsReply) ProtoMessage() {}

func (x *GetEaParamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEaParamsReply.ProtoReflect.Descriptor instead.
func (*GetEaParamsReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{1}
}

func (x *GetEaParamsReply) GetResponse() isGetEaParamsReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetEaParamsReply) GetData() *GetEaParamsData {
	if x != nil {
		if x, ok := x.Response.(*GetEaParamsReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *GetEaParamsReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*GetEaParamsReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetEaParamsReply_Response interface {
	isGetEaParamsReply_Response()
}

type GetEaParamsReply_Data struct {
	Data *GetEaParamsData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GetEaParamsReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetEaParamsReply_Data) isGetEaParamsReply_Response() {}

func (*GetEaParamsReply_Error) isGetEaParamsReply_Response() {}

type GetEaParamsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EaName        string                 `protobuf:"bytes,1,opt,name=ea_name,json=eaName,proto3" json:"ea_name,omitempty"`
	EaFound       bool                   `protobuf:"varint,2,opt,name=ea_found,json=eaFound,proto3" json:"ea_found,omitempty"`
	EaHasParams   bool                   `protobuf:"varint,3,opt,name=ea_has_params,json=eaHasParams,proto3" json:"ea_has_params,omitempty"`
	Parameters    []*EaParam             `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEaParamsData) Reset() {
	*x = GetEaParamsData{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEaParamsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEaParamsData) ProtoMessage() {}

func (x *GetEaParamsData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEaParamsData.ProtoReflect.Descriptor instead.
func (*GetEaParamsData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{2}
}

func (x *GetEaParamsData) GetEaName() string {
	if x != nil {
		return x.EaName
	}
	return ""
}

func (x *GetEaParamsData) GetEaFound() bool {
	if x != nil {
		return x.EaFound
	}
	return false
}

func (x *GetEaParamsData) GetEaHasParams() bool {
	if x != nil {
		return x.EaHasParams
	}
	return false
}

func (x *GetEaParamsData) GetParameters() []*EaParam {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EaParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          EA_PARAM_TYPE          `protobuf:"varint,2,opt,name=type,proto3,enum=mt4_term_api.EA_PARAM_TYPE" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EaParam) Reset() {
	*x = EaParam{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EaParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EaParam) ProtoMessage() {}

func (x *EaParam) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EaParam.ProtoReflect.Descriptor instead.
func (*EaParam) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{3}
}

func (x *EaParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EaParam) GetType() EA_PARAM_TYPE {
	if x != nil {
		return x.Type
	}
	return EA_PARAM_TYPE_EA_PARAM_TYPE_UNDEFINED
}

type OpenTerminalChartWithEaRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	SymbolName    string                                `protobuf:"bytes,1,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	EaFileName    string                                `protobuf:"bytes,2,opt,name=ea_file_name,json=eaFileName,proto3" json:"ea_file_name,omitempty"`
	ChartPeriod   EnumOpenTerminalChartWithEaChatPeriod `protobuf:"varint,3,opt,name=chart_period,json=chartPeriod,proto3,enum=mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod" json:"chart_period,omitempty"`
	EaParameters  []*OpenTerminalChartWithEaParameter   `protobuf:"bytes,4,rep,name=ea_parameters,json=eaParameters,proto3" json:"ea_parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTerminalChartWithEaRequest) Reset() {
	*x = OpenTerminalChartWithEaRequest{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalChartWithEaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalChartWithEaRequest) ProtoMessage() {}

func (x *OpenTerminalChartWithEaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalChartWithEaRequest.ProtoReflect.Descriptor instead.
func (*OpenTerminalChartWithEaRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{4}
}

func (x *OpenTerminalChartWithEaRequest) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *OpenTerminalChartWithEaRequest) GetEaFileName() string {
	if x != nil {
		return x.EaFileName
	}
	return ""
}

func (x *OpenTerminalChartWithEaRequest) GetChartPeriod() EnumOpenTerminalChartWithEaChatPeriod {
	if x != nil {
		return x.ChartPeriod
	}
	return EnumOpenTerminalChartWithEaChatPeriod_MRPC_EA_CHART_PERIOD_CURRENT
}

func (x *OpenTerminalChartWithEaRequest) GetEaParameters() []*OpenTerminalChartWithEaParameter {
	if x != nil {
		return x.EaParameters
	}
	return nil
}

type OpenTerminalChartWithEaParameter struct {
	state            protoimpl.MessageState                   `protogen:"open.v1"`
	Index            int32                                    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Type             EnumOpenTerminalChartWithEaParameterType `protobuf:"varint,2,opt,name=type,proto3,enum=mt4_term_api.EnumOpenTerminalChartWithEaParameterType" json:"type,omitempty"`
	IntParamValue    *int32                                   `protobuf:"varint,3,opt,name=int_param_value,json=intParamValue,proto3,oneof" json:"int_param_value,omitempty"`
	LongParamValue   *int64                                   `protobuf:"varint,4,opt,name=long_param_value,json=longParamValue,proto3,oneof" json:"long_param_value,omitempty"`
	BoolParamValue   *bool                                    `protobuf:"varint,5,opt,name=bool_param_value,json=boolParamValue,proto3,oneof" json:"bool_param_value,omitempty"`
	StringParamValue *string                                  `protobuf:"bytes,6,opt,name=string_param_value,json=stringParamValue,proto3,oneof" json:"string_param_value,omitempty"`
	DoubleParamValue *float64                                 `protobuf:"fixed64,7,opt,name=double_param_value,json=doubleParamValue,proto3,oneof" json:"double_param_value,omitempty"`
	Name             string                                   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenTerminalChartWithEaParameter) Reset() {
	*x = OpenTerminalChartWithEaParameter{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalChartWithEaParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalChartWithEaParameter) ProtoMessage() {}

func (x *OpenTerminalChartWithEaParameter) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalChartWithEaParameter.ProtoReflect.Descriptor instead.
func (*OpenTerminalChartWithEaParameter) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{5}
}

func (x *OpenTerminalChartWithEaParameter) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OpenTerminalChartWithEaParameter) GetType() EnumOpenTerminalChartWithEaParameterType {
	if x != nil {
		return x.Type
	}
	return EnumOpenTerminalChartWithEaParameterType_MRPC_EA_PARAM_INT
}

func (x *OpenTerminalChartWithEaParameter) GetIntParamValue() int32 {
	if x != nil && x.IntParamValue != nil {
		return *x.IntParamValue
	}
	return 0
}

func (x *OpenTerminalChartWithEaParameter) GetLongParamValue() int64 {
	if x != nil && x.LongParamValue != nil {
		return *x.LongParamValue
	}
	return 0
}

func (x *OpenTerminalChartWithEaParameter) GetBoolParamValue() bool {
	if x != nil && x.BoolParamValue != nil {
		return *x.BoolParamValue
	}
	return false
}

func (x *OpenTerminalChartWithEaParameter) GetStringParamValue() string {
	if x != nil && x.StringParamValue != nil {
		return *x.StringParamValue
	}
	return ""
}

func (x *OpenTerminalChartWithEaParameter) GetDoubleParamValue() float64 {
	if x != nil && x.DoubleParamValue != nil {
		return *x.DoubleParamValue
	}
	return 0
}

func (x *OpenTerminalChartWithEaParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OpenTerminalChartWithEaReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OpenTerminalChartWithEaReply_Data
	//	*OpenTerminalChartWithEaReply_Error
	Response      isOpenTerminalChartWithEaReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTerminalChartWithEaReply) Reset() {
	*x = OpenTerminalChartWithEaReply{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalChartWithEaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalChartWithEaReply) ProtoMessage() {}

func (x *OpenTerminalChartWithEaReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalChartWithEaReply.ProtoReflect.Descriptor instead.
func (*OpenTerminalChartWithEaReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{6}
}

func (x *OpenTerminalChartWithEaReply) GetResponse() isOpenTerminalChartWithEaReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OpenTerminalChartWithEaReply) GetData() *OpenTerminalChartWithEaData {
	if x != nil {
		if x, ok := x.Response.(*OpenTerminalChartWithEaReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OpenTerminalChartWithEaReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OpenTerminalChartWithEaReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOpenTerminalChartWithEaReply_Response interface {
	isOpenTerminalChartWithEaReply_Response()
}

type OpenTerminalChartWithEaReply_Data struct {
	Data *OpenTerminalChartWithEaData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OpenTerminalChartWithEaReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OpenTerminalChartWithEaReply_Data) isOpenTerminalChartWithEaReply_Response() {}

func (*OpenTerminalChartWithEaReply_Error) isOpenTerminalChartWithEaReply_Response() {}

type OpenTerminalChartWithEaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChartId       int64                  `protobuf:"varint,1,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTerminalChartWithEaData) Reset() {
	*x = OpenTerminalChartWithEaData{}
	mi := &file_mt4_term_api_charts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalChartWithEaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalChartWithEaData) ProtoMessage() {}

func (x *OpenTerminalChartWithEaData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_charts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalChartWithEaData.ProtoReflect.Descriptor instead.
func (*OpenTerminalChartWithEaData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_charts_proto_rawDescGZIP(), []int{7}
}

func (x *OpenTerminalChartWithEaData) GetChartId() int64 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

var File_mt4_term_api_charts_proto protoreflect.FileDescriptor

const file_mt4_term_api_charts_proto_rawDesc = "" +
	"\n" +
	"\x19mt4-term-api-charts.proto\x12\fmt4_term_api\x1a\x1cgoogle/api/annotations.proto\x1a\x14mrpc-mt4-error.proto\"6\n" +
	"\x12GetEaParamsRequest\x12 \n" +
	"\fea_file_name\x18\x01 \x01(\tR\n" +
	"eaFileName\"\x80\x01\n" +
	"\x10GetEaParamsReply\x123\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.mt4_term_api.GetEaParamsDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xa0\x01\n" +
	"\x0fGetEaParamsData\x12\x17\n" +
	"\aea_name\x18\x01 \x01(\tR\x06eaName\x12\x19\n" +
	"\bea_found\x18\x02 \x01(\bR\aeaFound\x12\"\n" +
	"\rea_has_params\x18\x03 \x01(\bR\veaHasParams\x125\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x15.mt4_term_api.EaParamR\n" +
	"parameters\"N\n" +
	"\aEaParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.mt4_term_api.EA_PARAM_TYPER\x04type\"\x90\x02\n" +
	"\x1eOpenTerminalChartWithEaRequest\x12\x1f\n" +
	"\vsymbol_name\x18\x01 \x01(\tR\n" +
	"symbolName\x12 \n" +
	"\fea_file_name\x18\x02 \x01(\tR\n" +
	"eaFileName\x12V\n" +
	"\fchart_period\x18\x03 \x01(\x0e23.mt4_term_api.EnumOpenTerminalChartWithEaChatPeriodR\vchartPeriod\x12S\n" +
	"\rea_parameters\x18\x04 \x03(\v2..mt4_term_api.OpenTerminalChartWithEaParameterR\feaParameters\"\xf5\x03\n" +
	" OpenTerminalChartWithEaParameter\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12J\n" +
	"\x04type\x18\x02 \x01(\x0e26.mt4_term_api.EnumOpenTerminalChartWithEaParameterTypeR\x04type\x12+\n" +
	"\x0fint_param_value\x18\x03 \x01(\x05H\x00R\rintParamValue\x88\x01\x01\x12-\n" +
	"\x10long_param_value\x18\x04 \x01(\x03H\x01R\x0elongParamValue\x88\x01\x01\x12-\n" +
	"\x10bool_param_value\x18\x05 \x01(\bH\x02R\x0eboolParamValue\x88\x01\x01\x121\n" +
	"\x12string_param_value\x18\x06 \x01(\tH\x03R\x10stringParamValue\x88\x01\x01\x121\n" +
	"\x12double_param_value\x18\a \x01(\x01H\x04R\x10doubleParamValue\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04nameB\x12\n" +
	"\x10_int_param_valueB\x13\n" +
	"\x11_long_param_valueB\x13\n" +
	"\x11_bool_param_valueB\x15\n" +
	"\x13_string_param_valueB\x15\n" +
	"\x13_double_param_value\"\x98\x01\n" +
	"\x1cOpenTerminalChartWithEaReply\x12?\n" +
	"\x04data\x18\x01 \x01(\v2).mt4_term_api.OpenTerminalChartWithEaDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"8\n" +
	"\x1bOpenTerminalChartWithEaData\x12\x19\n" +
	"\bchart_id\x18\x01 \x01(\x03R\achartId*\x96\x01\n" +
	"\rEA_PARAM_TYPE\x12\x1b\n" +
	"\x17EA_PARAM_TYPE_UNDEFINED\x10\x00\x12\x18\n" +
	"\x14EA_PARAM_TYPE_STRING\x10\x01\x12\x19\n" +
	"\x15EA_PARAM_TYPE_INTEGER\x10\x02\x12\x18\n" +
	"\x14EA_PARAM_TYPE_DOUBLE\x10\x03\x12\x19\n" +
	"\x15EA_PARAM_TYPE_BOOLEAN\x10\x04*\xa5\x01\n" +
	"(EnumOpenTerminalChartWithEaParameterType\x12\x15\n" +
	"\x11MRPC_EA_PARAM_INT\x10\x00\x12\x16\n" +
	"\x12MRPC_EA_PARAM_LONG\x10\x01\x12\x16\n" +
	"\x12MRPC_EA_PARAM_BOOL\x10\x02\x12\x18\n" +
	"\x14MRPC_EA_PARAM_STRING\x10\x03\x12\x18\n" +
	"\x14MRPC_EA_PARAM_DOUBLE\x10\x04*\xb1\x05\n" +
	"%EnumOpenTerminalChartWithEaChatPeriod\x12 \n" +
	"\x1cMRPC_EA_CHART_PERIOD_CURRENT\x10\x00\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M1\x10\x01\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M2\x10\x02\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M3\x10\x03\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M4\x10\x04\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M5\x10\x05\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_M6\x10\x06\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_M10\x10\a\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_M12\x10\b\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_M15\x10\t\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_M20\x10\n" +
	"\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_M30\x10\v\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H1\x10\f\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H2\x10\r\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H3\x10\x0e\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H4\x10\x0f\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H6\x10\x10\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_H8\x10\x11\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_H12\x10\x12\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_D1\x10\x13\x12\x1b\n" +
	"\x17MRPC_EA_CHART_PERIOD_W1\x10\x14\x12\x1c\n" +
	"\x18MRPC_EA_CHART_PERIOD_MN1\x10\x152\x87\x02\n" +
	"\x06Charts\x12e\n" +
	"\vGetEaParams\x12 .mt4_term_api.GetEaParamsRequest\x1a\x1e.mt4_term_api.GetEaParamsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/GetEaParams\x12\x95\x01\n" +
	"\x17OpenTerminalChartWithEa\x12,.mt4_term_api.OpenTerminalChartWithEaRequest\x1a*.mt4_term_api.OpenTerminalChartWithEaReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/OpenTerminalChartWithEaB/Z\x1egithub.com/MetaRPC/GoMT4/pb;pb\xaa\x02\fmt4_term_apib\x06proto3"

var (
	file_mt4_term_api_charts_proto_rawDescOnce sync.Once
	file_mt4_term_api_charts_proto_rawDescData []byte
)

func file_mt4_term_api_charts_proto_rawDescGZIP() []byte {
	file_mt4_term_api_charts_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_charts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mt4_term_api_charts_proto_rawDesc), len(file_mt4_term_api_charts_proto_rawDesc)))
	})
	return file_mt4_term_api_charts_proto_rawDescData
}

var file_mt4_term_api_charts_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mt4_term_api_charts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mt4_term_api_charts_proto_goTypes = []any{
	(EA_PARAM_TYPE)(0), // 0: mt4_term_api.EA_PARAM_TYPE
	(EnumOpenTerminalChartWithEaParameterType)(0), // 1: mt4_term_api.EnumOpenTerminalChartWithEaParameterType
	(EnumOpenTerminalChartWithEaChatPeriod)(0),    // 2: mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod
	(*GetEaParamsRequest)(nil),                    // 3: mt4_term_api.GetEaParamsRequest
	(*GetEaParamsReply)(nil),                      // 4: mt4_term_api.GetEaParamsReply
	(*GetEaParamsData)(nil),                       // 5: mt4_term_api.GetEaParamsData
	(*EaParam)(nil),                               // 6: mt4_term_api.EaParam
	(*OpenTerminalChartWithEaRequest)(nil),        // 7: mt4_term_api.OpenTerminalChartWithEaRequest
	(*OpenTerminalChartWithEaParameter)(nil),      // 8: mt4_term_api.OpenTerminalChartWithEaParameter
	(*OpenTerminalChartWithEaReply)(nil),          // 9: mt4_term_api.OpenTerminalChartWithEaReply
	(*OpenTerminalChartWithEaData)(nil),           // 10: mt4_term_api.OpenTerminalChartWithEaData
	(*Error)(nil),                                 // 11: mt4_term_api.Error
}
var file_mt4_term_api_charts_proto_depIdxs = []int32{
	5,  // 0: mt4_term_api.GetEaParamsReply.data:type_name -> mt4_term_api.GetEaParamsData
	11, // 1: mt4_term_api.GetEaParamsReply.error:type_name -> mt4_term_api.Error
	6,  // 2: mt4_term_api.GetEaParamsData.parameters:type_name -> mt4_term_api.EaParam
	0,  // 3: mt4_term_api.EaParam.type:type_name -> mt4_term_api.EA_PARAM_TYPE
	2,  // 4: mt4_term_api.OpenTerminalChartWithEaRequest.chart_period:type_name -> mt4_term_api.EnumOpenTerminalChartWithEaChatPeriod
	8,  // 5: mt4_term_api.OpenTerminalChartWithEaRequest.ea_parameters:type_name -> mt4_term_api.OpenTerminalChartWithEaParameter
	1,  // 6: mt4_term_api.OpenTerminalChartWithEaParameter.type:type_name -> mt4_term_api.EnumOpenTerminalChartWithEaParameterType
	10, // 7: mt4_term_api.OpenTerminalChartWithEaReply.data:type_name -> mt4_term_api.OpenTerminalChartWithEaData
	11, // 8: mt4_term_api.OpenTerminalChartWithEaReply.error:type_name -> mt4_term_api.Error
	3,  // 9: mt4_term_api.Charts.GetEaParams:input_type -> mt4_term_api.GetEaParamsRequest
	7,  // 10: mt4_term_api.Charts.OpenTerminalChartWithEa:input_type -> mt4_term_api.OpenTerminalChartWithEaRequest
	4,  // 11: mt4_term_api.Charts.GetEaParams:output_type -> mt4_term_api.GetEaParamsReply
	9,  // 12: mt4_term_api.Charts.OpenTerminalChartWithEa:output_type -> mt4_term_api.OpenTerminalChartWithEaReply
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mt4_term_api_charts_proto_init() }
func file_mt4_term_api_charts_proto_init() {
	if File_mt4_term_api_charts_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	file_mt4_term_api_charts_proto_msgTypes[1].OneofWrappers = []any{
		(*GetEaParamsReply_Data)(nil),
		(*GetEaParamsReply_Error)(nil),
	}
	file_mt4_term_api_charts_proto_msgTypes[5].OneofWrappers = []any{}
	file_mt4_term_api_charts_proto_msgTypes[6].OneofWrappers = []any{
		(*OpenTerminalChartWithEaReply_Data)(nil),
		(*OpenTerminalChartWithEaReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mt4_term_api_charts_proto_rawDesc), len(file_mt4_term_api_charts_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_charts_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_charts_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_charts_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_charts_proto_msgTypes,
	}.Build()
	File_mt4_term_api_charts_proto = out.File
	file_mt4_term_api_charts_proto_goTypes = nil
	file_mt4_term_api_charts_proto_depIdxs = nil
}
