// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mt4-term-api-market-info.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ENUM_QUOTE_HISTORY_TIMEFRAME int32

const (
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M1  ENUM_QUOTE_HISTORY_TIMEFRAME = 0 // 1 minute
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M5  ENUM_QUOTE_HISTORY_TIMEFRAME = 1 // 5 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M15 ENUM_QUOTE_HISTORY_TIMEFRAME = 2 //15 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M30 ENUM_QUOTE_HISTORY_TIMEFRAME = 3 //30 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_H1  ENUM_QUOTE_HISTORY_TIMEFRAME = 4 // 1 hour
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_H4  ENUM_QUOTE_HISTORY_TIMEFRAME = 5 //4 hours
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_D1  ENUM_QUOTE_HISTORY_TIMEFRAME = 6 // 1 day
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_W1  ENUM_QUOTE_HISTORY_TIMEFRAME = 7 //1 week
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_MN1 ENUM_QUOTE_HISTORY_TIMEFRAME = 8 // 1 month
)

// Enum value maps for ENUM_QUOTE_HISTORY_TIMEFRAME.
var (
	ENUM_QUOTE_HISTORY_TIMEFRAME_name = map[int32]string{
		0: "QH_PERIOD_M1",
		1: "QH_PERIOD_M5",
		2: "QH_PERIOD_M15",
		3: "QH_PERIOD_M30",
		4: "QH_PERIOD_H1",
		5: "QH_PERIOD_H4",
		6: "QH_PERIOD_D1",
		7: "QH_PERIOD_W1",
		8: "QH_PERIOD_MN1",
	}
	ENUM_QUOTE_HISTORY_TIMEFRAME_value = map[string]int32{
		"QH_PERIOD_M1":  0,
		"QH_PERIOD_M5":  1,
		"QH_PERIOD_M15": 2,
		"QH_PERIOD_M30": 3,
		"QH_PERIOD_H1":  4,
		"QH_PERIOD_H4":  5,
		"QH_PERIOD_D1":  6,
		"QH_PERIOD_W1":  7,
		"QH_PERIOD_MN1": 8,
	}
)

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) Enum() *ENUM_QUOTE_HISTORY_TIMEFRAME {
	p := new(ENUM_QUOTE_HISTORY_TIMEFRAME)
	*p = x
	return p
}

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_QUOTE_HISTORY_TIMEFRAME) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_market_info_proto_enumTypes[0].Descriptor()
}

func (ENUM_QUOTE_HISTORY_TIMEFRAME) Type() protoreflect.EnumType {
	return &file_mt4_term_api_market_info_proto_enumTypes[0]
}

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENUM_QUOTE_HISTORY_TIMEFRAME.Descriptor instead.
func (ENUM_QUOTE_HISTORY_TIMEFRAME) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{0}
}

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // optional int32 not_older_milliseconds = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type QuoteReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*QuoteReply_Data
	//	*QuoteReply_Error
	Response      isQuoteReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteReply) Reset() {
	*x = QuoteReply{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteReply) ProtoMessage() {}

func (x *QuoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteReply.ProtoReflect.Descriptor instead.
func (*QuoteReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteReply) GetResponse() isQuoteReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QuoteReply) GetData() *QuoteData {
	if x != nil {
		if x, ok := x.Response.(*QuoteReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *QuoteReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*QuoteReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQuoteReply_Response interface {
	isQuoteReply_Response()
}

type QuoteReply_Data struct {
	Data *QuoteData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteReply_Data) isQuoteReply_Response() {}

func (*QuoteReply_Error) isQuoteReply_Response() {}

type QuoteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,3,opt,name=ask,proto3" json:"ask,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteData) Reset() {
	*x = QuoteData{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteData) ProtoMessage() {}

func (x *QuoteData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteData.ProtoReflect.Descriptor instead.
func (*QuoteData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuoteData) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *QuoteData) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *QuoteData) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *QuoteData) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *QuoteData) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

type QuoteManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteManyRequest) Reset() {
	*x = QuoteManyRequest{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyRequest) ProtoMessage() {}

func (x *QuoteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyRequest.ProtoReflect.Descriptor instead.
func (*QuoteManyRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteManyRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type QuoteManyReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*QuoteManyReply_Data
	//	*QuoteManyReply_Error
	Response      isQuoteManyReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteManyReply) Reset() {
	*x = QuoteManyReply{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteManyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyReply) ProtoMessage() {}

func (x *QuoteManyReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyReply.ProtoReflect.Descriptor instead.
func (*QuoteManyReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteManyReply) GetResponse() isQuoteManyReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QuoteManyReply) GetData() *QuoteManyData {
	if x != nil {
		if x, ok := x.Response.(*QuoteManyReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *QuoteManyReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*QuoteManyReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQuoteManyReply_Response interface {
	isQuoteManyReply_Response()
}

type QuoteManyReply_Data struct {
	Data *QuoteManyData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteManyReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteManyReply_Data) isQuoteManyReply_Response() {}

func (*QuoteManyReply_Error) isQuoteManyReply_Response() {}

type QuoteManyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*QuoteData           `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteManyData) Reset() {
	*x = QuoteManyData{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteManyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyData) ProtoMessage() {}

func (x *QuoteManyData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyData.ProtoReflect.Descriptor instead.
func (*QuoteManyData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteManyData) GetQuotes() []*QuoteData {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type SymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolsRequest) Reset() {
	*x = SymbolsRequest{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsRequest) ProtoMessage() {}

func (x *SymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsRequest.ProtoReflect.Descriptor instead.
func (*SymbolsRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{6}
}

type SymbolsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SymbolsReply_Data
	//	*SymbolsReply_Error
	Response      isSymbolsReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolsReply) Reset() {
	*x = SymbolsReply{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsReply) ProtoMessage() {}

func (x *SymbolsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsReply.ProtoReflect.Descriptor instead.
func (*SymbolsReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{7}
}

func (x *SymbolsReply) GetResponse() isSymbolsReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SymbolsReply) GetData() *SymbolsData {
	if x != nil {
		if x, ok := x.Response.(*SymbolsReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SymbolsReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*SymbolsReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSymbolsReply_Response interface {
	isSymbolsReply_Response()
}

type SymbolsReply_Data struct {
	Data *SymbolsData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type SymbolsReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SymbolsReply_Data) isSymbolsReply_Response() {}

func (*SymbolsReply_Error) isSymbolsReply_Response() {}

type SymbolsData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SymbolNameInfos []*SymbolNameInfo      `protobuf:"bytes,1,rep,name=SymbolNameInfos,proto3" json:"SymbolNameInfos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SymbolsData) Reset() {
	*x = SymbolsData{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsData) ProtoMessage() {}

func (x *SymbolsData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsData.ProtoReflect.Descriptor instead.
func (*SymbolsData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{8}
}

func (x *SymbolsData) GetSymbolNameInfos() []*SymbolNameInfo {
	if x != nil {
		return x.SymbolNameInfos
	}
	return nil
}

type SymbolNameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolName    string                 `protobuf:"bytes,1,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	SymbolIndex   int32                  `protobuf:"varint,2,opt,name=symbol_index,json=symbolIndex,proto3" json:"symbol_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolNameInfo) Reset() {
	*x = SymbolNameInfo{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolNameInfo) ProtoMessage() {}

func (x *SymbolNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolNameInfo.ProtoReflect.Descriptor instead.
func (*SymbolNameInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{9}
}

func (x *SymbolNameInfo) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *SymbolNameInfo) GetSymbolIndex() int32 {
	if x != nil {
		return x.SymbolIndex
	}
	return 0
}

type QuoteHistoryRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Symbol        string                       `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     ENUM_QUOTE_HISTORY_TIMEFRAME `protobuf:"varint,2,opt,name=timeframe,proto3,enum=mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME" json:"timeframe,omitempty"`
	FromTime      *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime        *timestamppb.Timestamp       `protobuf:"bytes,4,opt,name=toTime,proto3" json:"toTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteHistoryRequest) Reset() {
	*x = QuoteHistoryRequest{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryRequest) ProtoMessage() {}

func (x *QuoteHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryRequest.ProtoReflect.Descriptor instead.
func (*QuoteHistoryRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{10}
}

func (x *QuoteHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuoteHistoryRequest) GetTimeframe() ENUM_QUOTE_HISTORY_TIMEFRAME {
	if x != nil {
		return x.Timeframe
	}
	return ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M1
}

func (x *QuoteHistoryRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *QuoteHistoryRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

type QuoteHistoryReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*QuoteHistoryReply_Data
	//	*QuoteHistoryReply_Error
	Response      isQuoteHistoryReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteHistoryReply) Reset() {
	*x = QuoteHistoryReply{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryReply) ProtoMessage() {}

func (x *QuoteHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryReply.ProtoReflect.Descriptor instead.
func (*QuoteHistoryReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{11}
}

func (x *QuoteHistoryReply) GetResponse() isQuoteHistoryReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QuoteHistoryReply) GetData() *QuoteHistoryData {
	if x != nil {
		if x, ok := x.Response.(*QuoteHistoryReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *QuoteHistoryReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*QuoteHistoryReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQuoteHistoryReply_Response interface {
	isQuoteHistoryReply_Response()
}

type QuoteHistoryReply_Data struct {
	Data *QuoteHistoryData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteHistoryReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteHistoryReply_Data) isQuoteHistoryReply_Response() {}

func (*QuoteHistoryReply_Error) isQuoteHistoryReply_Response() {}

type QuoteHistoryData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HistoricalQuotes []*HistoryQuote        `protobuf:"bytes,1,rep,name=historical_quotes,json=historicalQuotes,proto3" json:"historical_quotes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuoteHistoryData) Reset() {
	*x = QuoteHistoryData{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteHistoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryData) ProtoMessage() {}

func (x *QuoteHistoryData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryData.ProtoReflect.Descriptor instead.
func (*QuoteHistoryData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{12}
}

func (x *QuoteHistoryData) GetHistoricalQuotes() []*HistoryQuote {
	if x != nil {
		return x.HistoricalQuotes
	}
	return nil
}

type HistoryQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	RealVolume    int64                  `protobuf:"varint,8,opt,name=real_volume,json=realVolume,proto3" json:"real_volume,omitempty"`
	TickVolume    int64                  `protobuf:"varint,9,opt,name=tick_volume,json=tickVolume,proto3" json:"tick_volume,omitempty"`
	Spread        int32                  `protobuf:"varint,10,opt,name=spread,proto3" json:"spread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryQuote) Reset() {
	*x = HistoryQuote{}
	mi := &file_mt4_term_api_market_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryQuote) ProtoMessage() {}

func (x *HistoryQuote) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryQuote.ProtoReflect.Descriptor instead.
func (*HistoryQuote) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryQuote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HistoryQuote) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *HistoryQuote) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HistoryQuote) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *HistoryQuote) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *HistoryQuote) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *HistoryQuote) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *HistoryQuote) GetRealVolume() int64 {
	if x != nil {
		return x.RealVolume
	}
	return 0
}

func (x *HistoryQuote) GetTickVolume() int64 {
	if x != nil {
		return x.TickVolume
	}
	return 0
}

func (x *HistoryQuote) GetSpread() int32 {
	if x != nil {
		return x.Spread
	}
	return 0
}

var File_mt4_term_api_market_info_proto protoreflect.FileDescriptor

const file_mt4_term_api_market_info_proto_rawDesc = "" +
	"\n" +
	"\x1emt4-term-api-market-info.proto\x12\fmt4_term_api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14mrpc-mt4-error.proto\"&\n" +
	"\fQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"t\n" +
	"\n" +
	"QuoteReply\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x17.mt4_term_api.QuoteDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xa6\x01\n" +
	"\tQuoteData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\x01R\x03ask\x127\n" +
	"\tdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\",\n" +
	"\x10QuoteManyRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"|\n" +
	"\x0eQuoteManyReply\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.mt4_term_api.QuoteManyDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"@\n" +
	"\rQuoteManyData\x12/\n" +
	"\x06quotes\x18\x01 \x03(\v2\x17.mt4_term_api.QuoteDataR\x06quotes\"\x10\n" +
	"\x0eSymbolsRequest\"x\n" +
	"\fSymbolsReply\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x19.mt4_term_api.SymbolsDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"U\n" +
	"\vSymbolsData\x12F\n" +
	"\x0fSymbolNameInfos\x18\x01 \x03(\v2\x1c.mt4_term_api.SymbolNameInfoR\x0fSymbolNameInfos\"T\n" +
	"\x0eSymbolNameInfo\x12\x1f\n" +
	"\vsymbol_name\x18\x01 \x01(\tR\n" +
	"symbolName\x12!\n" +
	"\fsymbol_index\x18\x02 \x01(\x05R\vsymbolIndex\"\xe3\x01\n" +
	"\x13QuoteHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12H\n" +
	"\ttimeframe\x18\x02 \x01(\x0e2*.mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAMER\ttimeframe\x126\n" +
	"\bfromTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x122\n" +
	"\x06toTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\"\x82\x01\n" +
	"\x11QuoteHistoryReply\x124\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.mt4_term_api.QuoteHistoryDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"[\n" +
	"\x10QuoteHistoryData\x12G\n" +
	"\x11historical_quotes\x18\x01 \x03(\v2\x1a.mt4_term_api.HistoryQuoteR\x10historicalQuotes\"\x96\x02\n" +
	"\fHistoryQuote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x1f\n" +
	"\vreal_volume\x18\b \x01(\x03R\n" +
	"realVolume\x12\x1f\n" +
	"\vtick_volume\x18\t \x01(\x03R\n" +
	"tickVolume\x12\x16\n" +
	"\x06spread\x18\n" +
	" \x01(\x05R\x06spread*\xc3\x01\n" +
	"\x1cENUM_QUOTE_HISTORY_TIMEFRAME\x12\x10\n" +
	"\fQH_PERIOD_M1\x10\x00\x12\x10\n" +
	"\fQH_PERIOD_M5\x10\x01\x12\x11\n" +
	"\rQH_PERIOD_M15\x10\x02\x12\x11\n" +
	"\rQH_PERIOD_M30\x10\x03\x12\x10\n" +
	"\fQH_PERIOD_H1\x10\x04\x12\x10\n" +
	"\fQH_PERIOD_H4\x10\x05\x12\x10\n" +
	"\fQH_PERIOD_D1\x10\x06\x12\x10\n" +
	"\fQH_PERIOD_W1\x10\a\x12\x11\n" +
	"\rQH_PERIOD_MN1\x10\b2\xfc\x02\n" +
	"\n" +
	"MarketInfo\x12M\n" +
	"\x05Quote\x12\x1a.mt4_term_api.QuoteRequest\x1a\x18.mt4_term_api.QuoteReply\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/Quote\x12]\n" +
	"\tQuoteMany\x12\x1e.mt4_term_api.QuoteManyRequest\x1a\x1c.mt4_term_api.QuoteManyReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/QuoteMany\x12U\n" +
	"\aSymbols\x12\x1c.mt4_term_api.SymbolsRequest\x1a\x1a.mt4_term_api.SymbolsReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/Symbols\x12i\n" +
	"\fQuoteHistory\x12!.mt4_term_api.QuoteHistoryRequest\x1a\x1f.mt4_term_api.QuoteHistoryReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/QuoteHistoryB/Z\x1egithub.com/MetaRPC/GoMT4/pb;pb\xaa\x02\fmt4_term_apib\x06proto3"

var (
	file_mt4_term_api_market_info_proto_rawDescOnce sync.Once
	file_mt4_term_api_market_info_proto_rawDescData []byte
)

func file_mt4_term_api_market_info_proto_rawDescGZIP() []byte {
	file_mt4_term_api_market_info_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_market_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mt4_term_api_market_info_proto_rawDesc), len(file_mt4_term_api_market_info_proto_rawDesc)))
	})
	return file_mt4_term_api_market_info_proto_rawDescData
}

var file_mt4_term_api_market_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mt4_term_api_market_info_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mt4_term_api_market_info_proto_goTypes = []any{
	(ENUM_QUOTE_HISTORY_TIMEFRAME)(0), // 0: mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME
	(*QuoteRequest)(nil),              // 1: mt4_term_api.QuoteRequest
	(*QuoteReply)(nil),                // 2: mt4_term_api.QuoteReply
	(*QuoteData)(nil),                 // 3: mt4_term_api.QuoteData
	(*QuoteManyRequest)(nil),          // 4: mt4_term_api.QuoteManyRequest
	(*QuoteManyReply)(nil),            // 5: mt4_term_api.QuoteManyReply
	(*QuoteManyData)(nil),             // 6: mt4_term_api.QuoteManyData
	(*SymbolsRequest)(nil),            // 7: mt4_term_api.SymbolsRequest
	(*SymbolsReply)(nil),              // 8: mt4_term_api.SymbolsReply
	(*SymbolsData)(nil),               // 9: mt4_term_api.SymbolsData
	(*SymbolNameInfo)(nil),            // 10: mt4_term_api.SymbolNameInfo
	(*QuoteHistoryRequest)(nil),       // 11: mt4_term_api.QuoteHistoryRequest
	(*QuoteHistoryReply)(nil),         // 12: mt4_term_api.QuoteHistoryReply
	(*QuoteHistoryData)(nil),          // 13: mt4_term_api.QuoteHistoryData
	(*HistoryQuote)(nil),              // 14: mt4_term_api.HistoryQuote
	(*Error)(nil),                     // 15: mt4_term_api.Error
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_mt4_term_api_market_info_proto_depIdxs = []int32{
	3,  // 0: mt4_term_api.QuoteReply.data:type_name -> mt4_term_api.QuoteData
	15, // 1: mt4_term_api.QuoteReply.error:type_name -> mt4_term_api.Error
	16, // 2: mt4_term_api.QuoteData.date_time:type_name -> google.protobuf.Timestamp
	6,  // 3: mt4_term_api.QuoteManyReply.data:type_name -> mt4_term_api.QuoteManyData
	15, // 4: mt4_term_api.QuoteManyReply.error:type_name -> mt4_term_api.Error
	3,  // 5: mt4_term_api.QuoteManyData.quotes:type_name -> mt4_term_api.QuoteData
	9,  // 6: mt4_term_api.SymbolsReply.data:type_name -> mt4_term_api.SymbolsData
	15, // 7: mt4_term_api.SymbolsReply.error:type_name -> mt4_term_api.Error
	10, // 8: mt4_term_api.SymbolsData.SymbolNameInfos:type_name -> mt4_term_api.SymbolNameInfo
	0,  // 9: mt4_term_api.QuoteHistoryRequest.timeframe:type_name -> mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME
	16, // 10: mt4_term_api.QuoteHistoryRequest.fromTime:type_name -> google.protobuf.Timestamp
	16, // 11: mt4_term_api.QuoteHistoryRequest.toTime:type_name -> google.protobuf.Timestamp
	13, // 12: mt4_term_api.QuoteHistoryReply.data:type_name -> mt4_term_api.QuoteHistoryData
	15, // 13: mt4_term_api.QuoteHistoryReply.error:type_name -> mt4_term_api.Error
	14, // 14: mt4_term_api.QuoteHistoryData.historical_quotes:type_name -> mt4_term_api.HistoryQuote
	16, // 15: mt4_term_api.HistoryQuote.time:type_name -> google.protobuf.Timestamp
	1,  // 16: mt4_term_api.MarketInfo.Quote:input_type -> mt4_term_api.QuoteRequest
	4,  // 17: mt4_term_api.MarketInfo.QuoteMany:input_type -> mt4_term_api.QuoteManyRequest
	7,  // 18: mt4_term_api.MarketInfo.Symbols:input_type -> mt4_term_api.SymbolsRequest
	11, // 19: mt4_term_api.MarketInfo.QuoteHistory:input_type -> mt4_term_api.QuoteHistoryRequest
	2,  // 20: mt4_term_api.MarketInfo.Quote:output_type -> mt4_term_api.QuoteReply
	5,  // 21: mt4_term_api.MarketInfo.QuoteMany:output_type -> mt4_term_api.QuoteManyReply
	8,  // 22: mt4_term_api.MarketInfo.Symbols:output_type -> mt4_term_api.SymbolsReply
	12, // 23: mt4_term_api.MarketInfo.QuoteHistory:output_type -> mt4_term_api.QuoteHistoryReply
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mt4_term_api_market_info_proto_init() }
func file_mt4_term_api_market_info_proto_init() {
	if File_mt4_term_api_market_info_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	file_mt4_term_api_market_info_proto_msgTypes[1].OneofWrappers = []any{
		(*QuoteReply_Data)(nil),
		(*QuoteReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[4].OneofWrappers = []any{
		(*QuoteManyReply_Data)(nil),
		(*QuoteManyReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[7].OneofWrappers = []any{
		(*SymbolsReply_Data)(nil),
		(*SymbolsReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[11].OneofWrappers = []any{
		(*QuoteHistoryReply_Data)(nil),
		(*QuoteHistoryReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mt4_term_api_market_info_proto_rawDesc), len(file_mt4_term_api_market_info_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_market_info_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_market_info_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_market_info_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_market_info_proto_msgTypes,
	}.Build()
	File_mt4_term_api_market_info_proto = out.File
	file_mt4_term_api_market_info_proto_goTypes = nil
	file_mt4_term_api_market_info_proto_depIdxs = nil
}
