// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: mt4-term-api-charts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Charts_GetEaParams_FullMethodName             = "/mt4_term_api.Charts/GetEaParams"
	Charts_OpenTerminalChartWithEa_FullMethodName = "/mt4_term_api.Charts/OpenTerminalChartWithEa"
)

// ChartsClient is the client API for Charts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChartsClient interface {
	GetEaParams(ctx context.Context, in *GetEaParamsRequest, opts ...grpc.CallOption) (*GetEaParamsReply, error)
	OpenTerminalChartWithEa(ctx context.Context, in *OpenTerminalChartWithEaRequest, opts ...grpc.CallOption) (*OpenTerminalChartWithEaReply, error)
}

type chartsClient struct {
	cc grpc.ClientConnInterface
}

func NewChartsClient(cc grpc.ClientConnInterface) ChartsClient {
	return &chartsClient{cc}
}

func (c *chartsClient) GetEaParams(ctx context.Context, in *GetEaParamsRequest, opts ...grpc.CallOption) (*GetEaParamsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEaParamsReply)
	err := c.cc.Invoke(ctx, Charts_GetEaParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsClient) OpenTerminalChartWithEa(ctx context.Context, in *OpenTerminalChartWithEaRequest, opts ...grpc.CallOption) (*OpenTerminalChartWithEaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTerminalChartWithEaReply)
	err := c.cc.Invoke(ctx, Charts_OpenTerminalChartWithEa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChartsServer is the server API for Charts service.
// All implementations must embed UnimplementedChartsServer
// for forward compatibility.
type ChartsServer interface {
	GetEaParams(context.Context, *GetEaParamsRequest) (*GetEaParamsReply, error)
	OpenTerminalChartWithEa(context.Context, *OpenTerminalChartWithEaRequest) (*OpenTerminalChartWithEaReply, error)
	mustEmbedUnimplementedChartsServer()
}

// UnimplementedChartsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChartsServer struct{}

func (UnimplementedChartsServer) GetEaParams(context.Context, *GetEaParamsRequest) (*GetEaParamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEaParams not implemented")
}
func (UnimplementedChartsServer) OpenTerminalChartWithEa(context.Context, *OpenTerminalChartWithEaRequest) (*OpenTerminalChartWithEaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTerminalChartWithEa not implemented")
}
func (UnimplementedChartsServer) mustEmbedUnimplementedChartsServer() {}
func (UnimplementedChartsServer) testEmbeddedByValue()                {}

// UnsafeChartsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChartsServer will
// result in compilation errors.
type UnsafeChartsServer interface {
	mustEmbedUnimplementedChartsServer()
}

func RegisterChartsServer(s grpc.ServiceRegistrar, srv ChartsServer) {
	// If the following call pancis, it indicates UnimplementedChartsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Charts_ServiceDesc, srv)
}

func _Charts_GetEaParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEaParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServer).GetEaParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Charts_GetEaParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServer).GetEaParams(ctx, req.(*GetEaParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Charts_OpenTerminalChartWithEa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTerminalChartWithEaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServer).OpenTerminalChartWithEa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Charts_OpenTerminalChartWithEa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServer).OpenTerminalChartWithEa(ctx, req.(*OpenTerminalChartWithEaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Charts_ServiceDesc is the grpc.ServiceDesc for Charts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Charts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.Charts",
	HandlerType: (*ChartsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEaParams",
			Handler:    _Charts_GetEaParams_Handler,
		},
		{
			MethodName: "OpenTerminalChartWithEa",
			Handler:    _Charts_OpenTerminalChartWithEa_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt4-term-api-charts.proto",
}
