// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: mt4-term-api-subscriptions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SUB_ORDER_OPERATION_TYPE int32

const (
	SUB_ORDER_OPERATION_TYPE_SUB_OP_BUY       SUB_ORDER_OPERATION_TYPE = 0
	SUB_ORDER_OPERATION_TYPE_SUB_OP_SELL      SUB_ORDER_OPERATION_TYPE = 1
	SUB_ORDER_OPERATION_TYPE_SUB_OP_BUYLIMIT  SUB_ORDER_OPERATION_TYPE = 2
	SUB_ORDER_OPERATION_TYPE_SUB_OP_SELLLIMIT SUB_ORDER_OPERATION_TYPE = 3
	SUB_ORDER_OPERATION_TYPE_SUB_OP_BUYSTOP   SUB_ORDER_OPERATION_TYPE = 4
	SUB_ORDER_OPERATION_TYPE_SUB_OP_SELLSTOP  SUB_ORDER_OPERATION_TYPE = 5
)

// Enum value maps for SUB_ORDER_OPERATION_TYPE.
var (
	SUB_ORDER_OPERATION_TYPE_name = map[int32]string{
		0: "SUB_OP_BUY",
		1: "SUB_OP_SELL",
		2: "SUB_OP_BUYLIMIT",
		3: "SUB_OP_SELLLIMIT",
		4: "SUB_OP_BUYSTOP",
		5: "SUB_OP_SELLSTOP",
	}
	SUB_ORDER_OPERATION_TYPE_value = map[string]int32{
		"SUB_OP_BUY":       0,
		"SUB_OP_SELL":      1,
		"SUB_OP_BUYLIMIT":  2,
		"SUB_OP_SELLLIMIT": 3,
		"SUB_OP_BUYSTOP":   4,
		"SUB_OP_SELLSTOP":  5,
	}
)

func (x SUB_ORDER_OPERATION_TYPE) Enum() *SUB_ORDER_OPERATION_TYPE {
	p := new(SUB_ORDER_OPERATION_TYPE)
	*p = x
	return p
}

func (x SUB_ORDER_OPERATION_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SUB_ORDER_OPERATION_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_subscriptions_proto_enumTypes[0].Descriptor()
}

func (SUB_ORDER_OPERATION_TYPE) Type() protoreflect.EnumType {
	return &file_mt4_term_api_subscriptions_proto_enumTypes[0]
}

func (x SUB_ORDER_OPERATION_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SUB_ORDER_OPERATION_TYPE.Descriptor instead.
func (SUB_ORDER_OPERATION_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{0}
}

type MT4_SUB_ENUM_EVENT_GROUP_TYPE int32

const (
	MT4_SUB_ENUM_EVENT_GROUP_TYPE_OrderProfit MT4_SUB_ENUM_EVENT_GROUP_TYPE = 0
	MT4_SUB_ENUM_EVENT_GROUP_TYPE_OrderUpdate MT4_SUB_ENUM_EVENT_GROUP_TYPE = 1
)

// Enum value maps for MT4_SUB_ENUM_EVENT_GROUP_TYPE.
var (
	MT4_SUB_ENUM_EVENT_GROUP_TYPE_name = map[int32]string{
		0: "OrderProfit",
		1: "OrderUpdate",
	}
	MT4_SUB_ENUM_EVENT_GROUP_TYPE_value = map[string]int32{
		"OrderProfit": 0,
		"OrderUpdate": 1,
	}
)

func (x MT4_SUB_ENUM_EVENT_GROUP_TYPE) Enum() *MT4_SUB_ENUM_EVENT_GROUP_TYPE {
	p := new(MT4_SUB_ENUM_EVENT_GROUP_TYPE)
	*p = x
	return p
}

func (x MT4_SUB_ENUM_EVENT_GROUP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MT4_SUB_ENUM_EVENT_GROUP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_subscriptions_proto_enumTypes[1].Descriptor()
}

func (MT4_SUB_ENUM_EVENT_GROUP_TYPE) Type() protoreflect.EnumType {
	return &file_mt4_term_api_subscriptions_proto_enumTypes[1]
}

func (x MT4_SUB_ENUM_EVENT_GROUP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MT4_SUB_ENUM_EVENT_GROUP_TYPE.Descriptor instead.
func (MT4_SUB_ENUM_EVENT_GROUP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{1}
}

type OnSymbolTickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolNames   []string               `protobuf:"bytes,1,rep,name=symbol_names,json=symbolNames,proto3" json:"symbol_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSymbolTickRequest) Reset() {
	*x = OnSymbolTickRequest{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSymbolTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSymbolTickRequest) ProtoMessage() {}

func (x *OnSymbolTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSymbolTickRequest.ProtoReflect.Descriptor instead.
func (*OnSymbolTickRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *OnSymbolTickRequest) GetSymbolNames() []string {
	if x != nil {
		return x.SymbolNames
	}
	return nil
}

type OnSymbolTickReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OnSymbolTickReply_Data
	//	*OnSymbolTickReply_Error
	Response      isOnSymbolTickReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSymbolTickReply) Reset() {
	*x = OnSymbolTickReply{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSymbolTickReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSymbolTickReply) ProtoMessage() {}

func (x *OnSymbolTickReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSymbolTickReply.ProtoReflect.Descriptor instead.
func (*OnSymbolTickReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *OnSymbolTickReply) GetResponse() isOnSymbolTickReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OnSymbolTickReply) GetData() *OnSymbolTickData {
	if x != nil {
		if x, ok := x.Response.(*OnSymbolTickReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OnSymbolTickReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OnSymbolTickReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOnSymbolTickReply_Response interface {
	isOnSymbolTickReply_Response()
}

type OnSymbolTickReply_Data struct {
	Data *OnSymbolTickData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OnSymbolTickReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OnSymbolTickReply_Data) isOnSymbolTickReply_Response() {}

func (*OnSymbolTickReply_Error) isOnSymbolTickReply_Response() {}

type OnSymbolTickData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SymbolTick             *OnSymbolMqlTickInfo   `protobuf:"bytes,1,opt,name=symbol_tick,json=symbolTick,proto3" json:"symbol_tick,omitempty"`
	TerminalInstanceGuidId string                 `protobuf:"bytes,2,opt,name=terminal_instance_guid_id,json=terminalInstanceGuidId,proto3" json:"terminal_instance_guid_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OnSymbolTickData) Reset() {
	*x = OnSymbolTickData{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSymbolTickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSymbolTickData) ProtoMessage() {}

func (x *OnSymbolTickData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSymbolTickData.ProtoReflect.Descriptor instead.
func (*OnSymbolTickData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *OnSymbolTickData) GetSymbolTick() *OnSymbolMqlTickInfo {
	if x != nil {
		return x.SymbolTick
	}
	return nil
}

func (x *OnSymbolTickData) GetTerminalInstanceGuidId() string {
	if x != nil {
		return x.TerminalInstanceGuidId
	}
	return ""
}

type OnSymbolMqlTickInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`                       // Time of the last prices update (Unix timestamp)
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`                       // Current Bid price
	Ask           float64                `protobuf:"fixed64,3,opt,name=ask,proto3" json:"ask,omitempty"`                       // Current Ask price
	Last          float64                `protobuf:"fixed64,4,opt,name=last,proto3" json:"last,omitempty"`                     // Price of the last deal (Last)
	Volume        uint64                 `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`                  // Volume for the current Last price
	TimeMsc       int64                  `protobuf:"varint,6,opt,name=time_msc,json=timeMsc,proto3" json:"time_msc,omitempty"` // Time of a price last update in milliseconds
	Symbol        string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSymbolMqlTickInfo) Reset() {
	*x = OnSymbolMqlTickInfo{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSymbolMqlTickInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSymbolMqlTickInfo) ProtoMessage() {}

func (x *OnSymbolMqlTickInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSymbolMqlTickInfo.ProtoReflect.Descriptor instead.
func (*OnSymbolMqlTickInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *OnSymbolMqlTickInfo) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *OnSymbolMqlTickInfo) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *OnSymbolMqlTickInfo) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *OnSymbolMqlTickInfo) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *OnSymbolMqlTickInfo) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OnSymbolMqlTickInfo) GetTimeMsc() int64 {
	if x != nil {
		return x.TimeMsc
	}
	return 0
}

func (x *OnSymbolMqlTickInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type OnTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnTradeRequest) Reset() {
	*x = OnTradeRequest{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTradeRequest) ProtoMessage() {}

func (x *OnTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTradeRequest.ProtoReflect.Descriptor instead.
func (*OnTradeRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{4}
}

type OnTradeReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OnTradeReply_Data
	//	*OnTradeReply_Error
	Response      isOnTradeReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnTradeReply) Reset() {
	*x = OnTradeReply{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTradeReply) ProtoMessage() {}

func (x *OnTradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTradeReply.ProtoReflect.Descriptor instead.
func (*OnTradeReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *OnTradeReply) GetResponse() isOnTradeReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OnTradeReply) GetData() *OnTradeData {
	if x != nil {
		if x, ok := x.Response.(*OnTradeReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OnTradeReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OnTradeReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOnTradeReply_Response interface {
	isOnTradeReply_Response()
}

type OnTradeReply_Data struct {
	Data *OnTradeData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OnTradeReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OnTradeReply_Data) isOnTradeReply_Response() {}

func (*OnTradeReply_Error) isOnTradeReply_Response() {}

type OnTradeData struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	Type                   MT4_SUB_ENUM_EVENT_GROUP_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE" json:"type,omitempty"`
	EventData              *OnTadeEventData              `protobuf:"bytes,2,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	AccountInfo            *OnEventAccountInfo           `protobuf:"bytes,3,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	TerminalInstanceGuidId string                        `protobuf:"bytes,4,opt,name=terminal_instance_guid_id,json=terminalInstanceGuidId,proto3" json:"terminal_instance_guid_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OnTradeData) Reset() {
	*x = OnTradeData{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTradeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTradeData) ProtoMessage() {}

func (x *OnTradeData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTradeData.ProtoReflect.Descriptor instead.
func (*OnTradeData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *OnTradeData) GetType() MT4_SUB_ENUM_EVENT_GROUP_TYPE {
	if x != nil {
		return x.Type
	}
	return MT4_SUB_ENUM_EVENT_GROUP_TYPE_OrderProfit
}

func (x *OnTradeData) GetEventData() *OnTadeEventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *OnTradeData) GetAccountInfo() *OnEventAccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

func (x *OnTradeData) GetTerminalInstanceGuidId() string {
	if x != nil {
		return x.TerminalInstanceGuidId
	}
	return ""
}

type OnTadeEventData struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	NewOrders        []*OnTradeOrderInfo        `protobuf:"bytes,1,rep,name=new_orders,json=newOrders,proto3" json:"new_orders,omitempty"`
	UpdatedOrders    []*OnTradeUpdatedOrderInfo `protobuf:"bytes,2,rep,name=updated_orders,json=updatedOrders,proto3" json:"updated_orders,omitempty"`
	RemovedOrders    []*OnTradeOrderInfo        `protobuf:"bytes,3,rep,name=removed_orders,json=removedOrders,proto3" json:"removed_orders,omitempty"`
	NewHistoryOrders []*OnTradeOrderInfo        `protobuf:"bytes,4,rep,name=new_history_orders,json=newHistoryOrders,proto3" json:"new_history_orders,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnTadeEventData) Reset() {
	*x = OnTadeEventData{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTadeEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTadeEventData) ProtoMessage() {}

func (x *OnTadeEventData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTadeEventData.ProtoReflect.Descriptor instead.
func (*OnTadeEventData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *OnTadeEventData) GetNewOrders() []*OnTradeOrderInfo {
	if x != nil {
		return x.NewOrders
	}
	return nil
}

func (x *OnTadeEventData) GetUpdatedOrders() []*OnTradeUpdatedOrderInfo {
	if x != nil {
		return x.UpdatedOrders
	}
	return nil
}

func (x *OnTadeEventData) GetRemovedOrders() []*OnTradeOrderInfo {
	if x != nil {
		return x.RemovedOrders
	}
	return nil
}

func (x *OnTadeEventData) GetNewHistoryOrders() []*OnTradeOrderInfo {
	if x != nil {
		return x.NewHistoryOrders
	}
	return nil
}

type OnTradeOrderInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Index         int32                    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Ticket        int32                    `protobuf:"varint,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	IsHistory     bool                     `protobuf:"varint,3,opt,name=is_history,json=isHistory,proto3" json:"is_history,omitempty"`
	Comment       string                   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Commission    float64                  `protobuf:"fixed64,5,opt,name=commission,proto3" json:"commission,omitempty"`
	Expiration    *timestamppb.Timestamp   `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Lots          float64                  `protobuf:"fixed64,7,opt,name=lots,proto3" json:"lots,omitempty"`
	MagicNumber   int32                    `protobuf:"varint,8,opt,name=magic_number,json=magicNumber,proto3" json:"magic_number,omitempty"`
	OpenPrice     float64                  `protobuf:"fixed64,9,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	OpenTime      *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	OrderProfit   float64                  `protobuf:"fixed64,11,opt,name=order_profit,json=orderProfit,proto3" json:"order_profit,omitempty"`
	StopLoss      float64                  `protobuf:"fixed64,12,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	Swap          float64                  `protobuf:"fixed64,13,opt,name=swap,proto3" json:"swap,omitempty"`
	Symbol        string                   `protobuf:"bytes,14,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TakeProfit    float64                  `protobuf:"fixed64,15,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Type          SUB_ORDER_OPERATION_TYPE `protobuf:"varint,16,opt,name=type,proto3,enum=mt4_term_api.SUB_ORDER_OPERATION_TYPE" json:"type,omitempty"`
	ClosePrice    float64                  `protobuf:"fixed64,17,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"` // Only for closed orders (history)
	CloseTime     *timestamppb.Timestamp   `protobuf:"bytes,18,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`      // Only for closed orders (history)
	AccountLogin  int64                    `protobuf:"varint,19,opt,name=account_login,json=accountLogin,proto3" json:"account_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnTradeOrderInfo) Reset() {
	*x = OnTradeOrderInfo{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTradeOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTradeOrderInfo) ProtoMessage() {}

func (x *OnTradeOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTradeOrderInfo.ProtoReflect.Descriptor instead.
func (*OnTradeOrderInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{8}
}

func (x *OnTradeOrderInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OnTradeOrderInfo) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *OnTradeOrderInfo) GetIsHistory() bool {
	if x != nil {
		return x.IsHistory
	}
	return false
}

func (x *OnTradeOrderInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OnTradeOrderInfo) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *OnTradeOrderInfo) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *OnTradeOrderInfo) GetLots() float64 {
	if x != nil {
		return x.Lots
	}
	return 0
}

func (x *OnTradeOrderInfo) GetMagicNumber() int32 {
	if x != nil {
		return x.MagicNumber
	}
	return 0
}

func (x *OnTradeOrderInfo) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *OnTradeOrderInfo) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *OnTradeOrderInfo) GetOrderProfit() float64 {
	if x != nil {
		return x.OrderProfit
	}
	return 0
}

func (x *OnTradeOrderInfo) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *OnTradeOrderInfo) GetSwap() float64 {
	if x != nil {
		return x.Swap
	}
	return 0
}

func (x *OnTradeOrderInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OnTradeOrderInfo) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *OnTradeOrderInfo) GetType() SUB_ORDER_OPERATION_TYPE {
	if x != nil {
		return x.Type
	}
	return SUB_ORDER_OPERATION_TYPE_SUB_OP_BUY
}

func (x *OnTradeOrderInfo) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *OnTradeOrderInfo) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *OnTradeOrderInfo) GetAccountLogin() int64 {
	if x != nil {
		return x.AccountLogin
	}
	return 0
}

type OnTradeUpdatedOrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previous      *OnTradeOrderInfo      `protobuf:"bytes,1,opt,name=previous,proto3" json:"previous,omitempty"`
	Current       *OnTradeOrderInfo      `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnTradeUpdatedOrderInfo) Reset() {
	*x = OnTradeUpdatedOrderInfo{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnTradeUpdatedOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTradeUpdatedOrderInfo) ProtoMessage() {}

func (x *OnTradeUpdatedOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTradeUpdatedOrderInfo.ProtoReflect.Descriptor instead.
func (*OnTradeUpdatedOrderInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{9}
}

func (x *OnTradeUpdatedOrderInfo) GetPrevious() *OnTradeOrderInfo {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *OnTradeUpdatedOrderInfo) GetCurrent() *OnTradeOrderInfo {
	if x != nil {
		return x.Current
	}
	return nil
}

type OnOpenedOrdersTicketsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PullIntervalMilliseconds int32                  `protobuf:"varint,1,opt,name=pull_interval_milliseconds,json=pullIntervalMilliseconds,proto3" json:"pull_interval_milliseconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *OnOpenedOrdersTicketsRequest) Reset() {
	*x = OnOpenedOrdersTicketsRequest{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersTicketsRequest) ProtoMessage() {}

func (x *OnOpenedOrdersTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersTicketsRequest.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersTicketsRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{10}
}

func (x *OnOpenedOrdersTicketsRequest) GetPullIntervalMilliseconds() int32 {
	if x != nil {
		return x.PullIntervalMilliseconds
	}
	return 0
}

type OnOpenedOrdersTicketsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OnOpenedOrdersTicketsReply_Data
	//	*OnOpenedOrdersTicketsReply_Error
	Response      isOnOpenedOrdersTicketsReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOpenedOrdersTicketsReply) Reset() {
	*x = OnOpenedOrdersTicketsReply{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersTicketsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersTicketsReply) ProtoMessage() {}

func (x *OnOpenedOrdersTicketsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersTicketsReply.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersTicketsReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{11}
}

func (x *OnOpenedOrdersTicketsReply) GetResponse() isOnOpenedOrdersTicketsReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OnOpenedOrdersTicketsReply) GetData() *OnOpenedOrdersTicketsData {
	if x != nil {
		if x, ok := x.Response.(*OnOpenedOrdersTicketsReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OnOpenedOrdersTicketsReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OnOpenedOrdersTicketsReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOnOpenedOrdersTicketsReply_Response interface {
	isOnOpenedOrdersTicketsReply_Response()
}

type OnOpenedOrdersTicketsReply_Data struct {
	Data *OnOpenedOrdersTicketsData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OnOpenedOrdersTicketsReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OnOpenedOrdersTicketsReply_Data) isOnOpenedOrdersTicketsReply_Response() {}

func (*OnOpenedOrdersTicketsReply_Error) isOnOpenedOrdersTicketsReply_Response() {}

type OnOpenedOrdersTicketsData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PositionTickets        []int32                `protobuf:"varint,1,rep,packed,name=position_tickets,json=positionTickets,proto3" json:"position_tickets,omitempty"`
	PendingOrderTickets    []int32                `protobuf:"varint,2,rep,packed,name=pending_order_tickets,json=pendingOrderTickets,proto3" json:"pending_order_tickets,omitempty"`
	ServerTime             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	TerminalInstanceGuidId string                 `protobuf:"bytes,5,opt,name=terminal_instance_guid_id,json=terminalInstanceGuidId,proto3" json:"terminal_instance_guid_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OnOpenedOrdersTicketsData) Reset() {
	*x = OnOpenedOrdersTicketsData{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersTicketsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersTicketsData) ProtoMessage() {}

func (x *OnOpenedOrdersTicketsData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersTicketsData.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersTicketsData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{12}
}

func (x *OnOpenedOrdersTicketsData) GetPositionTickets() []int32 {
	if x != nil {
		return x.PositionTickets
	}
	return nil
}

func (x *OnOpenedOrdersTicketsData) GetPendingOrderTickets() []int32 {
	if x != nil {
		return x.PendingOrderTickets
	}
	return nil
}

func (x *OnOpenedOrdersTicketsData) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *OnOpenedOrdersTicketsData) GetTerminalInstanceGuidId() string {
	if x != nil {
		return x.TerminalInstanceGuidId
	}
	return ""
}

type OnOpenedOrdersProfitRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TimerPeriodMilliseconds int32                  `protobuf:"varint,1,opt,name=timer_period_milliseconds,json=timerPeriodMilliseconds,proto3" json:"timer_period_milliseconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OnOpenedOrdersProfitRequest) Reset() {
	*x = OnOpenedOrdersProfitRequest{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersProfitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersProfitRequest) ProtoMessage() {}

func (x *OnOpenedOrdersProfitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersProfitRequest.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersProfitRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{13}
}

func (x *OnOpenedOrdersProfitRequest) GetTimerPeriodMilliseconds() int32 {
	if x != nil {
		return x.TimerPeriodMilliseconds
	}
	return 0
}

type OnOpenedOrdersProfitReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*OnOpenedOrdersProfitReply_Data
	//	*OnOpenedOrdersProfitReply_Error
	Response      isOnOpenedOrdersProfitReply_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOpenedOrdersProfitReply) Reset() {
	*x = OnOpenedOrdersProfitReply{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersProfitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersProfitReply) ProtoMessage() {}

func (x *OnOpenedOrdersProfitReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersProfitReply.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersProfitReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{14}
}

func (x *OnOpenedOrdersProfitReply) GetResponse() isOnOpenedOrdersProfitReply_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OnOpenedOrdersProfitReply) GetData() *OnOpenedOrdersProfitData {
	if x != nil {
		if x, ok := x.Response.(*OnOpenedOrdersProfitReply_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *OnOpenedOrdersProfitReply) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*OnOpenedOrdersProfitReply_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOnOpenedOrdersProfitReply_Response interface {
	isOnOpenedOrdersProfitReply_Response()
}

type OnOpenedOrdersProfitReply_Data struct {
	Data *OnOpenedOrdersProfitData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OnOpenedOrdersProfitReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OnOpenedOrdersProfitReply_Data) isOnOpenedOrdersProfitReply_Response() {}

func (*OnOpenedOrdersProfitReply_Error) isOnOpenedOrdersProfitReply_Response() {}

type OnOpenedOrdersProfitData struct {
	state                         protoimpl.MessageState           `protogen:"open.v1"`
	Type                          MT4_SUB_ENUM_EVENT_GROUP_TYPE    `protobuf:"varint,1,opt,name=type,proto3,enum=mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE" json:"type,omitempty"`
	OpenedOrdersWithProfitUpdated []*OnOpenedOrdersProfitOrderInfo `protobuf:"bytes,2,rep,name=opened_orders_with_profit_updated,json=openedOrdersWithProfitUpdated,proto3" json:"opened_orders_with_profit_updated,omitempty"`
	AccountInfo                   *OnEventAccountInfo              `protobuf:"bytes,3,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	TerminalInstanceGuidId        string                           `protobuf:"bytes,4,opt,name=terminal_instance_guid_id,json=terminalInstanceGuidId,proto3" json:"terminal_instance_guid_id,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *OnOpenedOrdersProfitData) GetProfitInfo() any {
	panic("unimplemented")
}

func (x *OnOpenedOrdersProfitData) Reset() {
	*x = OnOpenedOrdersProfitData{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersProfitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersProfitData) ProtoMessage() {}

func (x *OnOpenedOrdersProfitData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersProfitData.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersProfitData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{15}
}

func (x *OnOpenedOrdersProfitData) GetType() MT4_SUB_ENUM_EVENT_GROUP_TYPE {
	if x != nil {
		return x.Type
	}
	return MT4_SUB_ENUM_EVENT_GROUP_TYPE_OrderProfit
}

func (x *OnOpenedOrdersProfitData) GetOpenedOrdersWithProfitUpdated() []*OnOpenedOrdersProfitOrderInfo {
	if x != nil {
		return x.OpenedOrdersWithProfitUpdated
	}
	return nil
}

func (x *OnOpenedOrdersProfitData) GetAccountInfo() *OnEventAccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

func (x *OnOpenedOrdersProfitData) GetTerminalInstanceGuidId() string {
	if x != nil {
		return x.TerminalInstanceGuidId
	}
	return ""
}

type OnEventAccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Credit        float64                `protobuf:"fixed64,2,opt,name=credit,proto3" json:"credit,omitempty"`
	Equity        float64                `protobuf:"fixed64,3,opt,name=equity,proto3" json:"equity,omitempty"`
	Margin        float64                `protobuf:"fixed64,4,opt,name=margin,proto3" json:"margin,omitempty"`
	FreeMargin    float64                `protobuf:"fixed64,5,opt,name=free_margin,json=freeMargin,proto3" json:"free_margin,omitempty"`
	Profit        float64                `protobuf:"fixed64,6,opt,name=profit,proto3" json:"profit,omitempty"`
	MarginLevel   float64                `protobuf:"fixed64,7,opt,name=margin_level,json=marginLevel,proto3" json:"margin_level,omitempty"`
	Login         int64                  `protobuf:"varint,8,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEventAccountInfo) Reset() {
	*x = OnEventAccountInfo{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEventAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEventAccountInfo) ProtoMessage() {}

func (x *OnEventAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEventAccountInfo.ProtoReflect.Descriptor instead.
func (*OnEventAccountInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{16}
}

func (x *OnEventAccountInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *OnEventAccountInfo) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *OnEventAccountInfo) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *OnEventAccountInfo) GetMargin() float64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *OnEventAccountInfo) GetFreeMargin() float64 {
	if x != nil {
		return x.FreeMargin
	}
	return 0
}

func (x *OnEventAccountInfo) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *OnEventAccountInfo) GetMarginLevel() float64 {
	if x != nil {
		return x.MarginLevel
	}
	return 0
}

func (x *OnEventAccountInfo) GetLogin() int64 {
	if x != nil {
		return x.Login
	}
	return 0
}

type OnOpenedOrdersProfitOrderInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Index         int32                    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Ticket        int32                    `protobuf:"varint,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Comment       string                   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Commission    float64                  `protobuf:"fixed64,4,opt,name=commission,proto3" json:"commission,omitempty"`
	Expiration    *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Lots          float64                  `protobuf:"fixed64,6,opt,name=lots,proto3" json:"lots,omitempty"`
	MagicNumber   int32                    `protobuf:"varint,7,opt,name=magic_number,json=magicNumber,proto3" json:"magic_number,omitempty"`
	OpenPrice     float64                  `protobuf:"fixed64,8,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	OpenTime      *timestamppb.Timestamp   `protobuf:"bytes,9,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	OrderProfit   float64                  `protobuf:"fixed64,10,opt,name=order_profit,json=orderProfit,proto3" json:"order_profit,omitempty"`
	StopLoss      float64                  `protobuf:"fixed64,11,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	Swap          float64                  `protobuf:"fixed64,12,opt,name=swap,proto3" json:"swap,omitempty"`
	Symbol        string                   `protobuf:"bytes,13,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TakeProfit    float64                  `protobuf:"fixed64,14,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Type          SUB_ORDER_OPERATION_TYPE `protobuf:"varint,15,opt,name=type,proto3,enum=mt4_term_api.SUB_ORDER_OPERATION_TYPE" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOpenedOrdersProfitOrderInfo) Reset() {
	*x = OnOpenedOrdersProfitOrderInfo{}
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOpenedOrdersProfitOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOpenedOrdersProfitOrderInfo) ProtoMessage() {}

func (x *OnOpenedOrdersProfitOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_subscriptions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOpenedOrdersProfitOrderInfo.ProtoReflect.Descriptor instead.
func (*OnOpenedOrdersProfitOrderInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_subscriptions_proto_rawDescGZIP(), []int{17}
}

func (x *OnOpenedOrdersProfitOrderInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetTicket() int32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OnOpenedOrdersProfitOrderInfo) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *OnOpenedOrdersProfitOrderInfo) GetLots() float64 {
	if x != nil {
		return x.Lots
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetMagicNumber() int32 {
	if x != nil {
		return x.MagicNumber
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *OnOpenedOrdersProfitOrderInfo) GetOrderProfit() float64 {
	if x != nil {
		return x.OrderProfit
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetSwap() float64 {
	if x != nil {
		return x.Swap
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OnOpenedOrdersProfitOrderInfo) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *OnOpenedOrdersProfitOrderInfo) GetType() SUB_ORDER_OPERATION_TYPE {
	if x != nil {
		return x.Type
	}
	return SUB_ORDER_OPERATION_TYPE_SUB_OP_BUY
}

var File_mt4_term_api_subscriptions_proto protoreflect.FileDescriptor

const file_mt4_term_api_subscriptions_proto_rawDesc = "" +
	"\n" +
	" mt4-term-api-subscriptions.proto\x12\fmt4_term_api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14mrpc-mt4-error.proto\"8\n" +
	"\x13OnSymbolTickRequest\x12!\n" +
	"\fsymbol_names\x18\x01 \x03(\tR\vsymbolNames\"\x82\x01\n" +
	"\x11OnSymbolTickReply\x124\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.mt4_term_api.OnSymbolTickDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x91\x01\n" +
	"\x10OnSymbolTickData\x12B\n" +
	"\vsymbol_tick\x18\x01 \x01(\v2!.mt4_term_api.OnSymbolMqlTickInfoR\n" +
	"symbolTick\x129\n" +
	"\x19terminal_instance_guid_id\x18\x02 \x01(\tR\x16terminalInstanceGuidId\"\xc8\x01\n" +
	"\x13OnSymbolMqlTickInfo\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\x01R\x03ask\x12\x12\n" +
	"\x04last\x18\x04 \x01(\x01R\x04last\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x04R\x06volume\x12\x19\n" +
	"\btime_msc\x18\x06 \x01(\x03R\atimeMsc\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\"\x10\n" +
	"\x0eOnTradeRequest\"x\n" +
	"\fOnTradeReply\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x19.mt4_term_api.OnTradeDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x8c\x02\n" +
	"\vOnTradeData\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPER\x04type\x12<\n" +
	"\n" +
	"event_data\x18\x02 \x01(\v2\x1d.mt4_term_api.OnTadeEventDataR\teventData\x12C\n" +
	"\faccount_info\x18\x03 \x01(\v2 .mt4_term_api.OnEventAccountInfoR\vaccountInfo\x129\n" +
	"\x19terminal_instance_guid_id\x18\x04 \x01(\tR\x16terminalInstanceGuidId\"\xb3\x02\n" +
	"\x0fOnTadeEventData\x12=\n" +
	"\n" +
	"new_orders\x18\x01 \x03(\v2\x1e.mt4_term_api.OnTradeOrderInfoR\tnewOrders\x12L\n" +
	"\x0eupdated_orders\x18\x02 \x03(\v2%.mt4_term_api.OnTradeUpdatedOrderInfoR\rupdatedOrders\x12E\n" +
	"\x0eremoved_orders\x18\x03 \x03(\v2\x1e.mt4_term_api.OnTradeOrderInfoR\rremovedOrders\x12L\n" +
	"\x12new_history_orders\x18\x04 \x03(\v2\x1e.mt4_term_api.OnTradeOrderInfoR\x10newHistoryOrders\"\xae\x05\n" +
	"\x10OnTradeOrderInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\x05R\x06ticket\x12\x1d\n" +
	"\n" +
	"is_history\x18\x03 \x01(\bR\tisHistory\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\x01R\n" +
	"commission\x12:\n" +
	"\n" +
	"expiration\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x12\n" +
	"\x04lots\x18\a \x01(\x01R\x04lots\x12!\n" +
	"\fmagic_number\x18\b \x01(\x05R\vmagicNumber\x12\x1d\n" +
	"\n" +
	"open_price\x18\t \x01(\x01R\topenPrice\x127\n" +
	"\topen_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x12!\n" +
	"\forder_profit\x18\v \x01(\x01R\vorderProfit\x12\x1b\n" +
	"\tstop_loss\x18\f \x01(\x01R\bstopLoss\x12\x12\n" +
	"\x04swap\x18\r \x01(\x01R\x04swap\x12\x16\n" +
	"\x06symbol\x18\x0e \x01(\tR\x06symbol\x12\x1f\n" +
	"\vtake_profit\x18\x0f \x01(\x01R\n" +
	"takeProfit\x12:\n" +
	"\x04type\x18\x10 \x01(\x0e2&.mt4_term_api.SUB_ORDER_OPERATION_TYPER\x04type\x12\x1f\n" +
	"\vclose_price\x18\x11 \x01(\x01R\n" +
	"closePrice\x129\n" +
	"\n" +
	"close_time\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12#\n" +
	"\raccount_login\x18\x13 \x01(\x03R\faccountLogin\"\x8f\x01\n" +
	"\x17OnTradeUpdatedOrderInfo\x12:\n" +
	"\bprevious\x18\x01 \x01(\v2\x1e.mt4_term_api.OnTradeOrderInfoR\bprevious\x128\n" +
	"\acurrent\x18\x02 \x01(\v2\x1e.mt4_term_api.OnTradeOrderInfoR\acurrent\"\\\n" +
	"\x1cOnOpenedOrdersTicketsRequest\x12<\n" +
	"\x1apull_interval_milliseconds\x18\x01 \x01(\x05R\x18pullIntervalMilliseconds\"\x94\x01\n" +
	"\x1aOnOpenedOrdersTicketsReply\x12=\n" +
	"\x04data\x18\x01 \x01(\v2'.mt4_term_api.OnOpenedOrdersTicketsDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xf2\x01\n" +
	"\x19OnOpenedOrdersTicketsData\x12)\n" +
	"\x10position_tickets\x18\x01 \x03(\x05R\x0fpositionTickets\x122\n" +
	"\x15pending_order_tickets\x18\x02 \x03(\x05R\x13pendingOrderTickets\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x129\n" +
	"\x19terminal_instance_guid_id\x18\x05 \x01(\tR\x16terminalInstanceGuidId\"Y\n" +
	"\x1bOnOpenedOrdersProfitRequest\x12:\n" +
	"\x19timer_period_milliseconds\x18\x01 \x01(\x05R\x17timerPeriodMilliseconds\"\x92\x01\n" +
	"\x19OnOpenedOrdersProfitReply\x12<\n" +
	"\x04data\x18\x01 \x01(\v2&.mt4_term_api.OnOpenedOrdersProfitDataH\x00R\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.mt4_term_api.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xd2\x02\n" +
	"\x18OnOpenedOrdersProfitData\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPER\x04type\x12u\n" +
	"!opened_orders_with_profit_updated\x18\x02 \x03(\v2+.mt4_term_api.OnOpenedOrdersProfitOrderInfoR\x1dopenedOrdersWithProfitUpdated\x12C\n" +
	"\faccount_info\x18\x03 \x01(\v2 .mt4_term_api.OnEventAccountInfoR\vaccountInfo\x129\n" +
	"\x19terminal_instance_guid_id\x18\x04 \x01(\tR\x16terminalInstanceGuidId\"\xe8\x01\n" +
	"\x12OnEventAccountInfo\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x16\n" +
	"\x06credit\x18\x02 \x01(\x01R\x06credit\x12\x16\n" +
	"\x06equity\x18\x03 \x01(\x01R\x06equity\x12\x16\n" +
	"\x06margin\x18\x04 \x01(\x01R\x06margin\x12\x1f\n" +
	"\vfree_margin\x18\x05 \x01(\x01R\n" +
	"freeMargin\x12\x16\n" +
	"\x06profit\x18\x06 \x01(\x01R\x06profit\x12!\n" +
	"\fmargin_level\x18\a \x01(\x01R\vmarginLevel\x12\x14\n" +
	"\x05login\x18\b \x01(\x03R\x05login\"\x9b\x04\n" +
	"\x1dOnOpenedOrdersProfitOrderInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\x05R\x06ticket\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"commission\x18\x04 \x01(\x01R\n" +
	"commission\x12:\n" +
	"\n" +
	"expiration\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x12\n" +
	"\x04lots\x18\x06 \x01(\x01R\x04lots\x12!\n" +
	"\fmagic_number\x18\a \x01(\x05R\vmagicNumber\x12\x1d\n" +
	"\n" +
	"open_price\x18\b \x01(\x01R\topenPrice\x127\n" +
	"\topen_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x12!\n" +
	"\forder_profit\x18\n" +
	" \x01(\x01R\vorderProfit\x12\x1b\n" +
	"\tstop_loss\x18\v \x01(\x01R\bstopLoss\x12\x12\n" +
	"\x04swap\x18\f \x01(\x01R\x04swap\x12\x16\n" +
	"\x06symbol\x18\r \x01(\tR\x06symbol\x12\x1f\n" +
	"\vtake_profit\x18\x0e \x01(\x01R\n" +
	"takeProfit\x12:\n" +
	"\x04type\x18\x0f \x01(\x0e2&.mt4_term_api.SUB_ORDER_OPERATION_TYPER\x04type*\x8f\x01\n" +
	"\x18SUB_ORDER_OPERATION_TYPE\x12\x0e\n" +
	"\n" +
	"SUB_OP_BUY\x10\x00\x12\x0f\n" +
	"\vSUB_OP_SELL\x10\x01\x12\x13\n" +
	"\x0fSUB_OP_BUYLIMIT\x10\x02\x12\x14\n" +
	"\x10SUB_OP_SELLLIMIT\x10\x03\x12\x12\n" +
	"\x0eSUB_OP_BUYSTOP\x10\x04\x12\x13\n" +
	"\x0fSUB_OP_SELLSTOP\x10\x05*A\n" +
	"\x1dMT4_SUB_ENUM_EVENT_GROUP_TYPE\x12\x0f\n" +
	"\vOrderProfit\x10\x00\x12\x0f\n" +
	"\vOrderUpdate\x10\x012\x91\x03\n" +
	"\x13SubscriptionService\x12E\n" +
	"\aOnTrade\x12\x1c.mt4_term_api.OnTradeRequest\x1a\x1a.mt4_term_api.OnTradeReply0\x01\x12o\n" +
	"\x15OnOpenedOrdersTickets\x12*.mt4_term_api.OnOpenedOrdersTicketsRequest\x1a(.mt4_term_api.OnOpenedOrdersTicketsReply0\x01\x12l\n" +
	"\x14OnOpenedOrdersProfit\x12).mt4_term_api.OnOpenedOrdersProfitRequest\x1a'.mt4_term_api.OnOpenedOrdersProfitReply0\x01\x12T\n" +
	"\fOnSymbolTick\x12!.mt4_term_api.OnSymbolTickRequest\x1a\x1f.mt4_term_api.OnSymbolTickReply0\x01B/Z\x1egithub.com/MetaRPC/GoMT4/pb;pb\xaa\x02\fmt4_term_apib\x06proto3"

var (
	file_mt4_term_api_subscriptions_proto_rawDescOnce sync.Once
	file_mt4_term_api_subscriptions_proto_rawDescData []byte
)

func file_mt4_term_api_subscriptions_proto_rawDescGZIP() []byte {
	file_mt4_term_api_subscriptions_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mt4_term_api_subscriptions_proto_rawDesc), len(file_mt4_term_api_subscriptions_proto_rawDesc)))
	})
	return file_mt4_term_api_subscriptions_proto_rawDescData
}

var file_mt4_term_api_subscriptions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mt4_term_api_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_mt4_term_api_subscriptions_proto_goTypes = []any{
	(SUB_ORDER_OPERATION_TYPE)(0),         // 0: mt4_term_api.SUB_ORDER_OPERATION_TYPE
	(MT4_SUB_ENUM_EVENT_GROUP_TYPE)(0),    // 1: mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE
	(*OnSymbolTickRequest)(nil),           // 2: mt4_term_api.OnSymbolTickRequest
	(*OnSymbolTickReply)(nil),             // 3: mt4_term_api.OnSymbolTickReply
	(*OnSymbolTickData)(nil),              // 4: mt4_term_api.OnSymbolTickData
	(*OnSymbolMqlTickInfo)(nil),           // 5: mt4_term_api.OnSymbolMqlTickInfo
	(*OnTradeRequest)(nil),                // 6: mt4_term_api.OnTradeRequest
	(*OnTradeReply)(nil),                  // 7: mt4_term_api.OnTradeReply
	(*OnTradeData)(nil),                   // 8: mt4_term_api.OnTradeData
	(*OnTadeEventData)(nil),               // 9: mt4_term_api.OnTadeEventData
	(*OnTradeOrderInfo)(nil),              // 10: mt4_term_api.OnTradeOrderInfo
	(*OnTradeUpdatedOrderInfo)(nil),       // 11: mt4_term_api.OnTradeUpdatedOrderInfo
	(*OnOpenedOrdersTicketsRequest)(nil),  // 12: mt4_term_api.OnOpenedOrdersTicketsRequest
	(*OnOpenedOrdersTicketsReply)(nil),    // 13: mt4_term_api.OnOpenedOrdersTicketsReply
	(*OnOpenedOrdersTicketsData)(nil),     // 14: mt4_term_api.OnOpenedOrdersTicketsData
	(*OnOpenedOrdersProfitRequest)(nil),   // 15: mt4_term_api.OnOpenedOrdersProfitRequest
	(*OnOpenedOrdersProfitReply)(nil),     // 16: mt4_term_api.OnOpenedOrdersProfitReply
	(*OnOpenedOrdersProfitData)(nil),      // 17: mt4_term_api.OnOpenedOrdersProfitData
	(*OnEventAccountInfo)(nil),            // 18: mt4_term_api.OnEventAccountInfo
	(*OnOpenedOrdersProfitOrderInfo)(nil), // 19: mt4_term_api.OnOpenedOrdersProfitOrderInfo
	(*Error)(nil),                         // 20: mt4_term_api.Error
	(*timestamppb.Timestamp)(nil),         // 21: google.protobuf.Timestamp
}
var file_mt4_term_api_subscriptions_proto_depIdxs = []int32{
	4,  // 0: mt4_term_api.OnSymbolTickReply.data:type_name -> mt4_term_api.OnSymbolTickData
	20, // 1: mt4_term_api.OnSymbolTickReply.error:type_name -> mt4_term_api.Error
	5,  // 2: mt4_term_api.OnSymbolTickData.symbol_tick:type_name -> mt4_term_api.OnSymbolMqlTickInfo
	21, // 3: mt4_term_api.OnSymbolMqlTickInfo.time:type_name -> google.protobuf.Timestamp
	8,  // 4: mt4_term_api.OnTradeReply.data:type_name -> mt4_term_api.OnTradeData
	20, // 5: mt4_term_api.OnTradeReply.error:type_name -> mt4_term_api.Error
	1,  // 6: mt4_term_api.OnTradeData.type:type_name -> mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE
	9,  // 7: mt4_term_api.OnTradeData.event_data:type_name -> mt4_term_api.OnTadeEventData
	18, // 8: mt4_term_api.OnTradeData.account_info:type_name -> mt4_term_api.OnEventAccountInfo
	10, // 9: mt4_term_api.OnTadeEventData.new_orders:type_name -> mt4_term_api.OnTradeOrderInfo
	11, // 10: mt4_term_api.OnTadeEventData.updated_orders:type_name -> mt4_term_api.OnTradeUpdatedOrderInfo
	10, // 11: mt4_term_api.OnTadeEventData.removed_orders:type_name -> mt4_term_api.OnTradeOrderInfo
	10, // 12: mt4_term_api.OnTadeEventData.new_history_orders:type_name -> mt4_term_api.OnTradeOrderInfo
	21, // 13: mt4_term_api.OnTradeOrderInfo.expiration:type_name -> google.protobuf.Timestamp
	21, // 14: mt4_term_api.OnTradeOrderInfo.open_time:type_name -> google.protobuf.Timestamp
	0,  // 15: mt4_term_api.OnTradeOrderInfo.type:type_name -> mt4_term_api.SUB_ORDER_OPERATION_TYPE
	21, // 16: mt4_term_api.OnTradeOrderInfo.close_time:type_name -> google.protobuf.Timestamp
	10, // 17: mt4_term_api.OnTradeUpdatedOrderInfo.previous:type_name -> mt4_term_api.OnTradeOrderInfo
	10, // 18: mt4_term_api.OnTradeUpdatedOrderInfo.current:type_name -> mt4_term_api.OnTradeOrderInfo
	14, // 19: mt4_term_api.OnOpenedOrdersTicketsReply.data:type_name -> mt4_term_api.OnOpenedOrdersTicketsData
	20, // 20: mt4_term_api.OnOpenedOrdersTicketsReply.error:type_name -> mt4_term_api.Error
	21, // 21: mt4_term_api.OnOpenedOrdersTicketsData.server_time:type_name -> google.protobuf.Timestamp
	17, // 22: mt4_term_api.OnOpenedOrdersProfitReply.data:type_name -> mt4_term_api.OnOpenedOrdersProfitData
	20, // 23: mt4_term_api.OnOpenedOrdersProfitReply.error:type_name -> mt4_term_api.Error
	1,  // 24: mt4_term_api.OnOpenedOrdersProfitData.type:type_name -> mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE
	19, // 25: mt4_term_api.OnOpenedOrdersProfitData.opened_orders_with_profit_updated:type_name -> mt4_term_api.OnOpenedOrdersProfitOrderInfo
	18, // 26: mt4_term_api.OnOpenedOrdersProfitData.account_info:type_name -> mt4_term_api.OnEventAccountInfo
	21, // 27: mt4_term_api.OnOpenedOrdersProfitOrderInfo.expiration:type_name -> google.protobuf.Timestamp
	21, // 28: mt4_term_api.OnOpenedOrdersProfitOrderInfo.open_time:type_name -> google.protobuf.Timestamp
	0,  // 29: mt4_term_api.OnOpenedOrdersProfitOrderInfo.type:type_name -> mt4_term_api.SUB_ORDER_OPERATION_TYPE
	6,  // 30: mt4_term_api.SubscriptionService.OnTrade:input_type -> mt4_term_api.OnTradeRequest
	12, // 31: mt4_term_api.SubscriptionService.OnOpenedOrdersTickets:input_type -> mt4_term_api.OnOpenedOrdersTicketsRequest
	15, // 32: mt4_term_api.SubscriptionService.OnOpenedOrdersProfit:input_type -> mt4_term_api.OnOpenedOrdersProfitRequest
	2,  // 33: mt4_term_api.SubscriptionService.OnSymbolTick:input_type -> mt4_term_api.OnSymbolTickRequest
	7,  // 34: mt4_term_api.SubscriptionService.OnTrade:output_type -> mt4_term_api.OnTradeReply
	13, // 35: mt4_term_api.SubscriptionService.OnOpenedOrdersTickets:output_type -> mt4_term_api.OnOpenedOrdersTicketsReply
	16, // 36: mt4_term_api.SubscriptionService.OnOpenedOrdersProfit:output_type -> mt4_term_api.OnOpenedOrdersProfitReply
	3,  // 37: mt4_term_api.SubscriptionService.OnSymbolTick:output_type -> mt4_term_api.OnSymbolTickReply
	34, // [34:38] is the sub-list for method output_type
	30, // [30:34] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_mt4_term_api_subscriptions_proto_init() }
func file_mt4_term_api_subscriptions_proto_init() {
	if File_mt4_term_api_subscriptions_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	file_mt4_term_api_subscriptions_proto_msgTypes[1].OneofWrappers = []any{
		(*OnSymbolTickReply_Data)(nil),
		(*OnSymbolTickReply_Error)(nil),
	}
	file_mt4_term_api_subscriptions_proto_msgTypes[5].OneofWrappers = []any{
		(*OnTradeReply_Data)(nil),
		(*OnTradeReply_Error)(nil),
	}
	file_mt4_term_api_subscriptions_proto_msgTypes[11].OneofWrappers = []any{
		(*OnOpenedOrdersTicketsReply_Data)(nil),
		(*OnOpenedOrdersTicketsReply_Error)(nil),
	}
	file_mt4_term_api_subscriptions_proto_msgTypes[14].OneofWrappers = []any{
		(*OnOpenedOrdersProfitReply_Data)(nil),
		(*OnOpenedOrdersProfitReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mt4_term_api_subscriptions_proto_rawDesc), len(file_mt4_term_api_subscriptions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_subscriptions_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_subscriptions_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_subscriptions_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_subscriptions_proto_msgTypes,
	}.Build()
	File_mt4_term_api_subscriptions_proto = out.File
	file_mt4_term_api_subscriptions_proto_goTypes = nil
	file_mt4_term_api_subscriptions_proto_depIdxs = nil
}
