// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt4-term-api-market-info.proto

package _go

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ENUM_QUOTE_HISTORY_TIMEFRAME int32

const (
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M1  ENUM_QUOTE_HISTORY_TIMEFRAME = 0 // 1 minute
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M5  ENUM_QUOTE_HISTORY_TIMEFRAME = 1 // 5 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M15 ENUM_QUOTE_HISTORY_TIMEFRAME = 2 //15 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M30 ENUM_QUOTE_HISTORY_TIMEFRAME = 3 //30 minutes
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_H1  ENUM_QUOTE_HISTORY_TIMEFRAME = 4 // 1 hour
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_H4  ENUM_QUOTE_HISTORY_TIMEFRAME = 5 //4 hours
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_D1  ENUM_QUOTE_HISTORY_TIMEFRAME = 6 // 1 day
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_W1  ENUM_QUOTE_HISTORY_TIMEFRAME = 7 //1 week
	ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_MN1 ENUM_QUOTE_HISTORY_TIMEFRAME = 8 // 1 month
)

// Enum value maps for ENUM_QUOTE_HISTORY_TIMEFRAME.
var (
	ENUM_QUOTE_HISTORY_TIMEFRAME_name = map[int32]string{
		0: "QH_PERIOD_M1",
		1: "QH_PERIOD_M5",
		2: "QH_PERIOD_M15",
		3: "QH_PERIOD_M30",
		4: "QH_PERIOD_H1",
		5: "QH_PERIOD_H4",
		6: "QH_PERIOD_D1",
		7: "QH_PERIOD_W1",
		8: "QH_PERIOD_MN1",
	}
	ENUM_QUOTE_HISTORY_TIMEFRAME_value = map[string]int32{
		"QH_PERIOD_M1":  0,
		"QH_PERIOD_M5":  1,
		"QH_PERIOD_M15": 2,
		"QH_PERIOD_M30": 3,
		"QH_PERIOD_H1":  4,
		"QH_PERIOD_H4":  5,
		"QH_PERIOD_D1":  6,
		"QH_PERIOD_W1":  7,
		"QH_PERIOD_MN1": 8,
	}
)

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) Enum() *ENUM_QUOTE_HISTORY_TIMEFRAME {
	p := new(ENUM_QUOTE_HISTORY_TIMEFRAME)
	*p = x
	return p
}

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_QUOTE_HISTORY_TIMEFRAME) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_market_info_proto_enumTypes[0].Descriptor()
}

func (ENUM_QUOTE_HISTORY_TIMEFRAME) Type() protoreflect.EnumType {
	return &file_mt4_term_api_market_info_proto_enumTypes[0]
}

func (x ENUM_QUOTE_HISTORY_TIMEFRAME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENUM_QUOTE_HISTORY_TIMEFRAME.Descriptor instead.
func (ENUM_QUOTE_HISTORY_TIMEFRAME) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{0}
}

type QuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // optional int32 not_older_milliseconds = 2;
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type QuoteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*QuoteReply_Data
	//	*QuoteReply_Error
	Response isQuoteReply_Response `protobuf_oneof:"response"`
}

func (x *QuoteReply) Reset() {
	*x = QuoteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteReply) ProtoMessage() {}

func (x *QuoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteReply.ProtoReflect.Descriptor instead.
func (*QuoteReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{1}
}

func (m *QuoteReply) GetResponse() isQuoteReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *QuoteReply) GetData() *QuoteData {
	if x, ok := x.GetResponse().(*QuoteReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *QuoteReply) GetError() *Error {
	if x, ok := x.GetResponse().(*QuoteReply_Error); ok {
		return x.Error
	}
	return nil
}

type isQuoteReply_Response interface {
	isQuoteReply_Response()
}

type QuoteReply_Data struct {
	Data *QuoteData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteReply_Data) isQuoteReply_Response() {}

func (*QuoteReply_Error) isQuoteReply_Response() {}

type QuoteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid      float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask      float64                `protobuf:"fixed64,3,opt,name=ask,proto3" json:"ask,omitempty"`
	DateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	High     float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low      float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *QuoteData) Reset() {
	*x = QuoteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteData) ProtoMessage() {}

func (x *QuoteData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteData.ProtoReflect.Descriptor instead.
func (*QuoteData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuoteData) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *QuoteData) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *QuoteData) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *QuoteData) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *QuoteData) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

type QuoteManyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbols []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
}

func (x *QuoteManyRequest) Reset() {
	*x = QuoteManyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyRequest) ProtoMessage() {}

func (x *QuoteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyRequest.ProtoReflect.Descriptor instead.
func (*QuoteManyRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteManyRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type QuoteManyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*QuoteManyReply_Data
	//	*QuoteManyReply_Error
	Response isQuoteManyReply_Response `protobuf_oneof:"response"`
}

func (x *QuoteManyReply) Reset() {
	*x = QuoteManyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteManyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyReply) ProtoMessage() {}

func (x *QuoteManyReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyReply.ProtoReflect.Descriptor instead.
func (*QuoteManyReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{4}
}

func (m *QuoteManyReply) GetResponse() isQuoteManyReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *QuoteManyReply) GetData() *QuoteManyData {
	if x, ok := x.GetResponse().(*QuoteManyReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *QuoteManyReply) GetError() *Error {
	if x, ok := x.GetResponse().(*QuoteManyReply_Error); ok {
		return x.Error
	}
	return nil
}

type isQuoteManyReply_Response interface {
	isQuoteManyReply_Response()
}

type QuoteManyReply_Data struct {
	Data *QuoteManyData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteManyReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteManyReply_Data) isQuoteManyReply_Response() {}

func (*QuoteManyReply_Error) isQuoteManyReply_Response() {}

type QuoteManyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quotes []*QuoteData `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *QuoteManyData) Reset() {
	*x = QuoteManyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteManyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteManyData) ProtoMessage() {}

func (x *QuoteManyData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteManyData.ProtoReflect.Descriptor instead.
func (*QuoteManyData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteManyData) GetQuotes() []*QuoteData {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type SymbolsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SymbolsRequest) Reset() {
	*x = SymbolsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsRequest) ProtoMessage() {}

func (x *SymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsRequest.ProtoReflect.Descriptor instead.
func (*SymbolsRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{6}
}

type SymbolsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*SymbolsReply_Data
	//	*SymbolsReply_Error
	Response isSymbolsReply_Response `protobuf_oneof:"response"`
}

func (x *SymbolsReply) Reset() {
	*x = SymbolsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsReply) ProtoMessage() {}

func (x *SymbolsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsReply.ProtoReflect.Descriptor instead.
func (*SymbolsReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{7}
}

func (m *SymbolsReply) GetResponse() isSymbolsReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *SymbolsReply) GetData() *SymbolsData {
	if x, ok := x.GetResponse().(*SymbolsReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *SymbolsReply) GetError() *Error {
	if x, ok := x.GetResponse().(*SymbolsReply_Error); ok {
		return x.Error
	}
	return nil
}

type isSymbolsReply_Response interface {
	isSymbolsReply_Response()
}

type SymbolsReply_Data struct {
	Data *SymbolsData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type SymbolsReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SymbolsReply_Data) isSymbolsReply_Response() {}

func (*SymbolsReply_Error) isSymbolsReply_Response() {}

type SymbolsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SymbolNameInfos []*SymbolNameInfo `protobuf:"bytes,1,rep,name=SymbolNameInfos,proto3" json:"SymbolNameInfos,omitempty"`
}

func (x *SymbolsData) Reset() {
	*x = SymbolsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsData) ProtoMessage() {}

func (x *SymbolsData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsData.ProtoReflect.Descriptor instead.
func (*SymbolsData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{8}
}

func (x *SymbolsData) GetSymbolNameInfos() []*SymbolNameInfo {
	if x != nil {
		return x.SymbolNameInfos
	}
	return nil
}

type SymbolNameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SymbolName  string `protobuf:"bytes,1,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	SymbolIndex int32  `protobuf:"varint,2,opt,name=symbol_index,json=symbolIndex,proto3" json:"symbol_index,omitempty"`
}

func (x *SymbolNameInfo) Reset() {
	*x = SymbolNameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolNameInfo) ProtoMessage() {}

func (x *SymbolNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolNameInfo.ProtoReflect.Descriptor instead.
func (*SymbolNameInfo) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{9}
}

func (x *SymbolNameInfo) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *SymbolNameInfo) GetSymbolIndex() int32 {
	if x != nil {
		return x.SymbolIndex
	}
	return 0
}

type QuoteHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string                       `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe ENUM_QUOTE_HISTORY_TIMEFRAME `protobuf:"varint,2,opt,name=timeframe,proto3,enum=mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME" json:"timeframe,omitempty"`
	FromTime  *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime    *timestamppb.Timestamp       `protobuf:"bytes,4,opt,name=toTime,proto3" json:"toTime,omitempty"`
}

func (x *QuoteHistoryRequest) Reset() {
	*x = QuoteHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryRequest) ProtoMessage() {}

func (x *QuoteHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryRequest.ProtoReflect.Descriptor instead.
func (*QuoteHistoryRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{10}
}

func (x *QuoteHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuoteHistoryRequest) GetTimeframe() ENUM_QUOTE_HISTORY_TIMEFRAME {
	if x != nil {
		return x.Timeframe
	}
	return ENUM_QUOTE_HISTORY_TIMEFRAME_QH_PERIOD_M1
}

func (x *QuoteHistoryRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *QuoteHistoryRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

type QuoteHistoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*QuoteHistoryReply_Data
	//	*QuoteHistoryReply_Error
	Response isQuoteHistoryReply_Response `protobuf_oneof:"response"`
}

func (x *QuoteHistoryReply) Reset() {
	*x = QuoteHistoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryReply) ProtoMessage() {}

func (x *QuoteHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryReply.ProtoReflect.Descriptor instead.
func (*QuoteHistoryReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{11}
}

func (m *QuoteHistoryReply) GetResponse() isQuoteHistoryReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *QuoteHistoryReply) GetData() *QuoteHistoryData {
	if x, ok := x.GetResponse().(*QuoteHistoryReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *QuoteHistoryReply) GetError() *Error {
	if x, ok := x.GetResponse().(*QuoteHistoryReply_Error); ok {
		return x.Error
	}
	return nil
}

type isQuoteHistoryReply_Response interface {
	isQuoteHistoryReply_Response()
}

type QuoteHistoryReply_Data struct {
	Data *QuoteHistoryData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type QuoteHistoryReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QuoteHistoryReply_Data) isQuoteHistoryReply_Response() {}

func (*QuoteHistoryReply_Error) isQuoteHistoryReply_Response() {}

type QuoteHistoryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoricalQuotes []*HistoryQuote `protobuf:"bytes,1,rep,name=historical_quotes,json=historicalQuotes,proto3" json:"historical_quotes,omitempty"`
}

func (x *QuoteHistoryData) Reset() {
	*x = QuoteHistoryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteHistoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteHistoryData) ProtoMessage() {}

func (x *QuoteHistoryData) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteHistoryData.ProtoReflect.Descriptor instead.
func (*QuoteHistoryData) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{12}
}

func (x *QuoteHistoryData) GetHistoricalQuotes() []*HistoryQuote {
	if x != nil {
		return x.HistoricalQuotes
	}
	return nil
}

type HistoryQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Index      int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Time       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Open       float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	Close      float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	High       float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low        float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	RealVolume int64                  `protobuf:"varint,8,opt,name=real_volume,json=realVolume,proto3" json:"real_volume,omitempty"`
	TickVolume int64                  `protobuf:"varint,9,opt,name=tick_volume,json=tickVolume,proto3" json:"tick_volume,omitempty"`
	Spread     int32                  `protobuf:"varint,10,opt,name=spread,proto3" json:"spread,omitempty"`
}

func (x *HistoryQuote) Reset() {
	*x = HistoryQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_market_info_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryQuote) ProtoMessage() {}

func (x *HistoryQuote) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_market_info_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryQuote.ProtoReflect.Descriptor instead.
func (*HistoryQuote) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_market_info_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryQuote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HistoryQuote) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *HistoryQuote) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HistoryQuote) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *HistoryQuote) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *HistoryQuote) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *HistoryQuote) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *HistoryQuote) GetRealVolume() int64 {
	if x != nil {
		return x.RealVolume
	}
	return 0
}

func (x *HistoryQuote) GetTickVolume() int64 {
	if x != nil {
		return x.TickVolume
	}
	return 0
}

func (x *HistoryQuote) GetSpread() int32 {
	if x != nil {
		return x.Spread
	}
	return 0
}

var File_mt4_term_api_market_info_proto protoreflect.FileDescriptor

var file_mt4_term_api_market_info_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x74, 0x34, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d,
	0x72, 0x70, 0x63, 0x2d, 0x6d, 0x74, 0x34, 0x2d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x74, 0x0a, 0x0a, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0xa6, 0x01, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x37, 0x0a, 0x09, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x22, 0x2c, 0x0a, 0x10, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x22, 0x7c, 0x0a, 0x0e, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x6e,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x0d, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4d,
	0x61, 0x6e, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x78, 0x0a, 0x0c, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x34,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a, 0x0b, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x46, 0x0a, 0x0f, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x54, 0x0a, 0x0e, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0xe3, 0x01, 0x0a, 0x13, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x48, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x51, 0x55, 0x4f, 0x54, 0x45, 0x5f, 0x48,
	0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x46, 0x52, 0x41, 0x4d, 0x45,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x06, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x11, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x74,
	0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x10,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x47, 0x0a, 0x11, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x74,
	0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x10, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x63, 0x61, 0x6c, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x6c,
	0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72,
	0x65, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x63,
	0x6b, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x69, 0x63, 0x6b, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x70, 0x72, 0x65,
	0x61, 0x64, 0x2a, 0xc3, 0x01, 0x0a, 0x1c, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x51, 0x55, 0x4f, 0x54,
	0x45, 0x5f, 0x48, 0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x46, 0x52,
	0x41, 0x4d, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44,
	0x5f, 0x4d, 0x31, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49,
	0x4f, 0x44, 0x5f, 0x4d, 0x35, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x48, 0x5f, 0x50, 0x45,
	0x52, 0x49, 0x4f, 0x44, 0x5f, 0x4d, 0x31, 0x35, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x48,
	0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x4d, 0x33, 0x30, 0x10, 0x03, 0x12, 0x10, 0x0a,
	0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x48, 0x31, 0x10, 0x04, 0x12,
	0x10, 0x0a, 0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x48, 0x34, 0x10,
	0x05, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x44,
	0x31, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44,
	0x5f, 0x57, 0x31, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x49,
	0x4f, 0x44, 0x5f, 0x4d, 0x4e, 0x31, 0x10, 0x08, 0x32, 0xfc, 0x02, 0x0a, 0x0a, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4d, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x12, 0x1a, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06,
	0x2f, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x5d, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4d,
	0x61, 0x6e, 0x79, 0x12, 0x1e, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x55, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73,
	0x12, 0x1c, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0a, 0x12, 0x08, 0x2f, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x12, 0x69, 0x0a, 0x0c,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e, 0x6d,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x6d, 0x72, 0x70,
	0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x6d, 0x74, 0x34, 0x2f,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0xaa, 0x02, 0x0c, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mt4_term_api_market_info_proto_rawDescOnce sync.Once
	file_mt4_term_api_market_info_proto_rawDescData = file_mt4_term_api_market_info_proto_rawDesc
)

func file_mt4_term_api_market_info_proto_rawDescGZIP() []byte {
	file_mt4_term_api_market_info_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_market_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt4_term_api_market_info_proto_rawDescData)
	})
	return file_mt4_term_api_market_info_proto_rawDescData
}

var file_mt4_term_api_market_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mt4_term_api_market_info_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mt4_term_api_market_info_proto_goTypes = []interface{}{
	(ENUM_QUOTE_HISTORY_TIMEFRAME)(0), // 0: mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME
	(*QuoteRequest)(nil),              // 1: mt4_term_api.QuoteRequest
	(*QuoteReply)(nil),                // 2: mt4_term_api.QuoteReply
	(*QuoteData)(nil),                 // 3: mt4_term_api.QuoteData
	(*QuoteManyRequest)(nil),          // 4: mt4_term_api.QuoteManyRequest
	(*QuoteManyReply)(nil),            // 5: mt4_term_api.QuoteManyReply
	(*QuoteManyData)(nil),             // 6: mt4_term_api.QuoteManyData
	(*SymbolsRequest)(nil),            // 7: mt4_term_api.SymbolsRequest
	(*SymbolsReply)(nil),              // 8: mt4_term_api.SymbolsReply
	(*SymbolsData)(nil),               // 9: mt4_term_api.SymbolsData
	(*SymbolNameInfo)(nil),            // 10: mt4_term_api.SymbolNameInfo
	(*QuoteHistoryRequest)(nil),       // 11: mt4_term_api.QuoteHistoryRequest
	(*QuoteHistoryReply)(nil),         // 12: mt4_term_api.QuoteHistoryReply
	(*QuoteHistoryData)(nil),          // 13: mt4_term_api.QuoteHistoryData
	(*HistoryQuote)(nil),              // 14: mt4_term_api.HistoryQuote
	(*Error)(nil),                     // 15: mt4_term_api.Error
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_mt4_term_api_market_info_proto_depIdxs = []int32{
	3,  // 0: mt4_term_api.QuoteReply.data:type_name -> mt4_term_api.QuoteData
	15, // 1: mt4_term_api.QuoteReply.error:type_name -> mt4_term_api.Error
	16, // 2: mt4_term_api.QuoteData.date_time:type_name -> google.protobuf.Timestamp
	6,  // 3: mt4_term_api.QuoteManyReply.data:type_name -> mt4_term_api.QuoteManyData
	15, // 4: mt4_term_api.QuoteManyReply.error:type_name -> mt4_term_api.Error
	3,  // 5: mt4_term_api.QuoteManyData.quotes:type_name -> mt4_term_api.QuoteData
	9,  // 6: mt4_term_api.SymbolsReply.data:type_name -> mt4_term_api.SymbolsData
	15, // 7: mt4_term_api.SymbolsReply.error:type_name -> mt4_term_api.Error
	10, // 8: mt4_term_api.SymbolsData.SymbolNameInfos:type_name -> mt4_term_api.SymbolNameInfo
	0,  // 9: mt4_term_api.QuoteHistoryRequest.timeframe:type_name -> mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME
	16, // 10: mt4_term_api.QuoteHistoryRequest.fromTime:type_name -> google.protobuf.Timestamp
	16, // 11: mt4_term_api.QuoteHistoryRequest.toTime:type_name -> google.protobuf.Timestamp
	13, // 12: mt4_term_api.QuoteHistoryReply.data:type_name -> mt4_term_api.QuoteHistoryData
	15, // 13: mt4_term_api.QuoteHistoryReply.error:type_name -> mt4_term_api.Error
	14, // 14: mt4_term_api.QuoteHistoryData.historical_quotes:type_name -> mt4_term_api.HistoryQuote
	16, // 15: mt4_term_api.HistoryQuote.time:type_name -> google.protobuf.Timestamp
	1,  // 16: mt4_term_api.MarketInfo.Quote:input_type -> mt4_term_api.QuoteRequest
	4,  // 17: mt4_term_api.MarketInfo.QuoteMany:input_type -> mt4_term_api.QuoteManyRequest
	7,  // 18: mt4_term_api.MarketInfo.Symbols:input_type -> mt4_term_api.SymbolsRequest
	11, // 19: mt4_term_api.MarketInfo.QuoteHistory:input_type -> mt4_term_api.QuoteHistoryRequest
	2,  // 20: mt4_term_api.MarketInfo.Quote:output_type -> mt4_term_api.QuoteReply
	5,  // 21: mt4_term_api.MarketInfo.QuoteMany:output_type -> mt4_term_api.QuoteManyReply
	8,  // 22: mt4_term_api.MarketInfo.Symbols:output_type -> mt4_term_api.SymbolsReply
	12, // 23: mt4_term_api.MarketInfo.QuoteHistory:output_type -> mt4_term_api.QuoteHistoryReply
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mt4_term_api_market_info_proto_init() }
func file_mt4_term_api_market_info_proto_init() {
	if File_mt4_term_api_market_info_proto != nil {
		return
	}
	file_mrpc_mt4_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mt4_term_api_market_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteManyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteManyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteManyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolNameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteHistoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteHistoryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_market_info_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mt4_term_api_market_info_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*QuoteReply_Data)(nil),
		(*QuoteReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*QuoteManyReply_Data)(nil),
		(*QuoteManyReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*SymbolsReply_Data)(nil),
		(*SymbolsReply_Error)(nil),
	}
	file_mt4_term_api_market_info_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*QuoteHistoryReply_Data)(nil),
		(*QuoteHistoryReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt4_term_api_market_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_market_info_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_market_info_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_market_info_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_market_info_proto_msgTypes,
	}.Build()
	File_mt4_term_api_market_info_proto = out.File
	file_mt4_term_api_market_info_proto_rawDesc = nil
	file_mt4_term_api_market_info_proto_goTypes = nil
	file_mt4_term_api_market_info_proto_depIdxs = nil
}
