// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt4-term-api-account-helper.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountHelperClient is the client API for AccountHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountHelperClient interface {
	// Some information about account
	AccountSummary(ctx context.Context, in *AccountSummaryRequest, opts ...grpc.CallOption) (*AccountSummaryReply, error)
	// List of opened orders
	OpenedOrders(ctx context.Context, in *OpenedOrdersRequest, opts ...grpc.CallOption) (*OpenedOrdersReply, error)
	// List of opened orders tickets
	OpenedOrdersTickets(ctx context.Context, in *OpenedOrdersTicketsRequest, opts ...grpc.CallOption) (*OpenedOrdersTicketsReply, error)
	// Orders history with pagination and open date filters
	OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryReply, error)
	// Full information about exact symbol, or all symbols
	SymbolParamsMany(ctx context.Context, in *SymbolParamsManyRequest, opts ...grpc.CallOption) (*SymbolParamsManyReply, error)
	TickValueWithSize(ctx context.Context, in *TickValueWithSizeRequest, opts ...grpc.CallOption) (*TickValueWithSizeReply, error)
}

type accountHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountHelperClient(cc grpc.ClientConnInterface) AccountHelperClient {
	return &accountHelperClient{cc}
}

func (c *accountHelperClient) AccountSummary(ctx context.Context, in *AccountSummaryRequest, opts ...grpc.CallOption) (*AccountSummaryReply, error) {
	out := new(AccountSummaryReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/AccountSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountHelperClient) OpenedOrders(ctx context.Context, in *OpenedOrdersRequest, opts ...grpc.CallOption) (*OpenedOrdersReply, error) {
	out := new(OpenedOrdersReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/OpenedOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountHelperClient) OpenedOrdersTickets(ctx context.Context, in *OpenedOrdersTicketsRequest, opts ...grpc.CallOption) (*OpenedOrdersTicketsReply, error) {
	out := new(OpenedOrdersTicketsReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/OpenedOrdersTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountHelperClient) OrdersHistory(ctx context.Context, in *OrdersHistoryRequest, opts ...grpc.CallOption) (*OrdersHistoryReply, error) {
	out := new(OrdersHistoryReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/OrdersHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountHelperClient) SymbolParamsMany(ctx context.Context, in *SymbolParamsManyRequest, opts ...grpc.CallOption) (*SymbolParamsManyReply, error) {
	out := new(SymbolParamsManyReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/SymbolParamsMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountHelperClient) TickValueWithSize(ctx context.Context, in *TickValueWithSizeRequest, opts ...grpc.CallOption) (*TickValueWithSizeReply, error) {
	out := new(TickValueWithSizeReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.AccountHelper/TickValueWithSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountHelperServer is the server API for AccountHelper service.
// All implementations should embed UnimplementedAccountHelperServer
// for forward compatibility
type AccountHelperServer interface {
	// Some information about account
	AccountSummary(context.Context, *AccountSummaryRequest) (*AccountSummaryReply, error)
	// List of opened orders
	OpenedOrders(context.Context, *OpenedOrdersRequest) (*OpenedOrdersReply, error)
	// List of opened orders tickets
	OpenedOrdersTickets(context.Context, *OpenedOrdersTicketsRequest) (*OpenedOrdersTicketsReply, error)
	// Orders history with pagination and open date filters
	OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryReply, error)
	// Full information about exact symbol, or all symbols
	SymbolParamsMany(context.Context, *SymbolParamsManyRequest) (*SymbolParamsManyReply, error)
	TickValueWithSize(context.Context, *TickValueWithSizeRequest) (*TickValueWithSizeReply, error)
}

// UnimplementedAccountHelperServer should be embedded to have forward compatible implementations.
type UnimplementedAccountHelperServer struct {
}

func (UnimplementedAccountHelperServer) AccountSummary(context.Context, *AccountSummaryRequest) (*AccountSummaryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountSummary not implemented")
}
func (UnimplementedAccountHelperServer) OpenedOrders(context.Context, *OpenedOrdersRequest) (*OpenedOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenedOrders not implemented")
}
func (UnimplementedAccountHelperServer) OpenedOrdersTickets(context.Context, *OpenedOrdersTicketsRequest) (*OpenedOrdersTicketsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenedOrdersTickets not implemented")
}
func (UnimplementedAccountHelperServer) OrdersHistory(context.Context, *OrdersHistoryRequest) (*OrdersHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrdersHistory not implemented")
}
func (UnimplementedAccountHelperServer) SymbolParamsMany(context.Context, *SymbolParamsManyRequest) (*SymbolParamsManyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SymbolParamsMany not implemented")
}
func (UnimplementedAccountHelperServer) TickValueWithSize(context.Context, *TickValueWithSizeRequest) (*TickValueWithSizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TickValueWithSize not implemented")
}

// UnsafeAccountHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountHelperServer will
// result in compilation errors.
type UnsafeAccountHelperServer interface {
	mustEmbedUnimplementedAccountHelperServer()
}

func RegisterAccountHelperServer(s grpc.ServiceRegistrar, srv AccountHelperServer) {
	s.RegisterService(&AccountHelper_ServiceDesc, srv)
}

func _AccountHelper_AccountSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).AccountSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/AccountSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).AccountSummary(ctx, req.(*AccountSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountHelper_OpenedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenedOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).OpenedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/OpenedOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).OpenedOrders(ctx, req.(*OpenedOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountHelper_OpenedOrdersTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenedOrdersTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).OpenedOrdersTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/OpenedOrdersTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).OpenedOrdersTickets(ctx, req.(*OpenedOrdersTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountHelper_OrdersHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).OrdersHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/OrdersHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).OrdersHistory(ctx, req.(*OrdersHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountHelper_SymbolParamsMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolParamsManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).SymbolParamsMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/SymbolParamsMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).SymbolParamsMany(ctx, req.(*SymbolParamsManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountHelper_TickValueWithSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickValueWithSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHelperServer).TickValueWithSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.AccountHelper/TickValueWithSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHelperServer).TickValueWithSize(ctx, req.(*TickValueWithSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountHelper_ServiceDesc is the grpc.ServiceDesc for AccountHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.AccountHelper",
	HandlerType: (*AccountHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountSummary",
			Handler:    _AccountHelper_AccountSummary_Handler,
		},
		{
			MethodName: "OpenedOrders",
			Handler:    _AccountHelper_OpenedOrders_Handler,
		},
		{
			MethodName: "OpenedOrdersTickets",
			Handler:    _AccountHelper_OpenedOrdersTickets_Handler,
		},
		{
			MethodName: "OrdersHistory",
			Handler:    _AccountHelper_OrdersHistory_Handler,
		},
		{
			MethodName: "SymbolParamsMany",
			Handler:    _AccountHelper_SymbolParamsMany_Handler,
		},
		{
			MethodName: "TickValueWithSize",
			Handler:    _AccountHelper_TickValueWithSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt4-term-api-account-helper.proto",
}
