// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt4-term-api-internal-charts.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChartTemplateMode int32

const (
	ChartTemplateMode_ON_TRADE                 ChartTemplateMode = 0
	ChartTemplateMode_ON_OPENED_ORDERS_TICKETS ChartTemplateMode = 1
	ChartTemplateMode_ON_ORDER_PROFIT          ChartTemplateMode = 2
	ChartTemplateMode_ON_SYMBOL_INFO_TICK      ChartTemplateMode = 3
)

// Enum value maps for ChartTemplateMode.
var (
	ChartTemplateMode_name = map[int32]string{
		0: "ON_TRADE",
		1: "ON_OPENED_ORDERS_TICKETS",
		2: "ON_ORDER_PROFIT",
		3: "ON_SYMBOL_INFO_TICK",
	}
	ChartTemplateMode_value = map[string]int32{
		"ON_TRADE":                 0,
		"ON_OPENED_ORDERS_TICKETS": 1,
		"ON_ORDER_PROFIT":          2,
		"ON_SYMBOL_INFO_TICK":      3,
	}
)

func (x ChartTemplateMode) Enum() *ChartTemplateMode {
	p := new(ChartTemplateMode)
	*p = x
	return p
}

func (x ChartTemplateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChartTemplateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mt4_term_api_internal_charts_proto_enumTypes[0].Descriptor()
}

func (ChartTemplateMode) Type() protoreflect.EnumType {
	return &file_mt4_term_api_internal_charts_proto_enumTypes[0]
}

func (x ChartTemplateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChartTemplateMode.Descriptor instead.
func (ChartTemplateMode) EnumDescriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{0}
}

type CustomChartApplyTemplateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomChartApplyTemplateReply) Reset() {
	*x = CustomChartApplyTemplateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartApplyTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartApplyTemplateReply) ProtoMessage() {}

func (x *CustomChartApplyTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartApplyTemplateReply.ProtoReflect.Descriptor instead.
func (*CustomChartApplyTemplateReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{0}
}

type CustomChartApplyTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartId          int64  `protobuf:"varint,1,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
	TemplateFileName string `protobuf:"bytes,2,opt,name=template_file_name,json=templateFileName,proto3" json:"template_file_name,omitempty"`
}

func (x *CustomChartApplyTemplateRequest) Reset() {
	*x = CustomChartApplyTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartApplyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartApplyTemplateRequest) ProtoMessage() {}

func (x *CustomChartApplyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartApplyTemplateRequest.ProtoReflect.Descriptor instead.
func (*CustomChartApplyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{1}
}

func (x *CustomChartApplyTemplateRequest) GetChartId() int64 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

func (x *CustomChartApplyTemplateRequest) GetTemplateFileName() string {
	if x != nil {
		return x.TemplateFileName
	}
	return ""
}

type CustomChartSaveTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartId int64 `protobuf:"varint,1,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
}

func (x *CustomChartSaveTemplateRequest) Reset() {
	*x = CustomChartSaveTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartSaveTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartSaveTemplateRequest) ProtoMessage() {}

func (x *CustomChartSaveTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartSaveTemplateRequest.ProtoReflect.Descriptor instead.
func (*CustomChartSaveTemplateRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{2}
}

func (x *CustomChartSaveTemplateRequest) GetChartId() int64 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

type CustomChartSaveTemplateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateFileName string `protobuf:"bytes,1,opt,name=template_file_name,json=templateFileName,proto3" json:"template_file_name,omitempty"`
}

func (x *CustomChartSaveTemplateReply) Reset() {
	*x = CustomChartSaveTemplateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartSaveTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartSaveTemplateReply) ProtoMessage() {}

func (x *CustomChartSaveTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartSaveTemplateReply.ProtoReflect.Descriptor instead.
func (*CustomChartSaveTemplateReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{3}
}

func (x *CustomChartSaveTemplateReply) GetTemplateFileName() string {
	if x != nil {
		return x.TemplateFileName
	}
	return ""
}

type CustomChartOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartSymbol    string `protobuf:"bytes,1,opt,name=chart_symbol,json=chartSymbol,proto3" json:"chart_symbol,omitempty"`
	ChartPeriodInt int32  `protobuf:"varint,2,opt,name=chart_period_int,json=chartPeriodInt,proto3" json:"chart_period_int,omitempty"`
}

func (x *CustomChartOpenRequest) Reset() {
	*x = CustomChartOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartOpenRequest) ProtoMessage() {}

func (x *CustomChartOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartOpenRequest.ProtoReflect.Descriptor instead.
func (*CustomChartOpenRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{4}
}

func (x *CustomChartOpenRequest) GetChartSymbol() string {
	if x != nil {
		return x.ChartSymbol
	}
	return ""
}

func (x *CustomChartOpenRequest) GetChartPeriodInt() int32 {
	if x != nil {
		return x.ChartPeriodInt
	}
	return 0
}

type CustomChartOpenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartId int64 `protobuf:"varint,1,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
}

func (x *CustomChartOpenReply) Reset() {
	*x = CustomChartOpenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomChartOpenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomChartOpenReply) ProtoMessage() {}

func (x *CustomChartOpenReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomChartOpenReply.ProtoReflect.Descriptor instead.
func (*CustomChartOpenReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{5}
}

func (x *CustomChartOpenReply) GetChartId() int64 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

type ChartOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartSymbol string            `protobuf:"bytes,1,opt,name=chart_symbol,json=chartSymbol,proto3" json:"chart_symbol,omitempty"`
	Mode        ChartTemplateMode `protobuf:"varint,2,opt,name=mode,proto3,enum=mt4_term_api.ChartTemplateMode" json:"mode,omitempty"`
}

func (x *ChartOpenRequest) Reset() {
	*x = ChartOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartOpenRequest) ProtoMessage() {}

func (x *ChartOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartOpenRequest.ProtoReflect.Descriptor instead.
func (*ChartOpenRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{6}
}

func (x *ChartOpenRequest) GetChartSymbol() string {
	if x != nil {
		return x.ChartSymbol
	}
	return ""
}

func (x *ChartOpenRequest) GetMode() ChartTemplateMode {
	if x != nil {
		return x.Mode
	}
	return ChartTemplateMode_ON_TRADE
}

type ChartOpenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartTerminalId int64 `protobuf:"varint,1,opt,name=chart_terminal_id,json=chartTerminalId,proto3" json:"chart_terminal_id,omitempty"`
}

func (x *ChartOpenReply) Reset() {
	*x = ChartOpenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartOpenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartOpenReply) ProtoMessage() {}

func (x *ChartOpenReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartOpenReply.ProtoReflect.Descriptor instead.
func (*ChartOpenReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{7}
}

func (x *ChartOpenReply) GetChartTerminalId() int64 {
	if x != nil {
		return x.ChartTerminalId
	}
	return 0
}

type ChartCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartTerminalId int64 `protobuf:"varint,1,opt,name=chart_terminal_id,json=chartTerminalId,proto3" json:"chart_terminal_id,omitempty"`
}

func (x *ChartCloseRequest) Reset() {
	*x = ChartCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartCloseRequest) ProtoMessage() {}

func (x *ChartCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartCloseRequest.ProtoReflect.Descriptor instead.
func (*ChartCloseRequest) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{8}
}

func (x *ChartCloseRequest) GetChartTerminalId() int64 {
	if x != nil {
		return x.ChartTerminalId
	}
	return 0
}

type ChartCloseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChartCloseReply) Reset() {
	*x = ChartCloseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt4_term_api_internal_charts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChartCloseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartCloseReply) ProtoMessage() {}

func (x *ChartCloseReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt4_term_api_internal_charts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartCloseReply.ProtoReflect.Descriptor instead.
func (*ChartCloseReply) Descriptor() ([]byte, []int) {
	return file_mt4_term_api_internal_charts_proto_rawDescGZIP(), []int{9}
}

var File_mt4_term_api_internal_charts_proto protoreflect.FileDescriptor

var file_mt4_term_api_internal_charts_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x74, 0x34, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72,
	0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x6a, 0x0a, 0x1f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x3b, 0x0a, 0x1e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x61,
	0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x1c,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x61, 0x76, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x12,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x16, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x49, 0x6e,
	0x74, 0x22, 0x31, 0x0a, 0x14, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61,
	0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x72, 0x74, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x33, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x74, 0x34, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x22, 0x3c, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x3f,
	0x0a, 0x11, 0x43, 0x68, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2a, 0x6d, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x72, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x4e, 0x5f, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x45, 0x4e,
	0x45, 0x44, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x53, 0x5f, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x54,
	0x53, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x4e, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x4e, 0x5f, 0x53,
	0x59, 0x4d, 0x42, 0x4f, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x54, 0x49, 0x43, 0x4b, 0x10,
	0x03, 0x32, 0xf3, 0x03, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x43, 0x68,
	0x61, 0x72, 0x74, 0x73, 0x12, 0x49, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x12, 0x1e, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4c, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1f, 0x2e,
	0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5b, 0x0a,
	0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x12, 0x24, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x73, 0x0a, 0x17, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6d, 0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x61,
	0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x76, 0x0a, 0x18, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x2e, 0x6d, 0x74,
	0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6d, 0x74, 0x34,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e, 0x6d,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x6d, 0x72, 0x70,
	0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x6d, 0x74, 0x34, 0x2f,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0xaa, 0x02, 0x0c, 0x6d,
	0x74, 0x34, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mt4_term_api_internal_charts_proto_rawDescOnce sync.Once
	file_mt4_term_api_internal_charts_proto_rawDescData = file_mt4_term_api_internal_charts_proto_rawDesc
)

func file_mt4_term_api_internal_charts_proto_rawDescGZIP() []byte {
	file_mt4_term_api_internal_charts_proto_rawDescOnce.Do(func() {
		file_mt4_term_api_internal_charts_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt4_term_api_internal_charts_proto_rawDescData)
	})
	return file_mt4_term_api_internal_charts_proto_rawDescData
}

var file_mt4_term_api_internal_charts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mt4_term_api_internal_charts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mt4_term_api_internal_charts_proto_goTypes = []interface{}{
	(ChartTemplateMode)(0),                  // 0: mt4_term_api.ChartTemplateMode
	(*CustomChartApplyTemplateReply)(nil),   // 1: mt4_term_api.CustomChartApplyTemplateReply
	(*CustomChartApplyTemplateRequest)(nil), // 2: mt4_term_api.CustomChartApplyTemplateRequest
	(*CustomChartSaveTemplateRequest)(nil),  // 3: mt4_term_api.CustomChartSaveTemplateRequest
	(*CustomChartSaveTemplateReply)(nil),    // 4: mt4_term_api.CustomChartSaveTemplateReply
	(*CustomChartOpenRequest)(nil),          // 5: mt4_term_api.CustomChartOpenRequest
	(*CustomChartOpenReply)(nil),            // 6: mt4_term_api.CustomChartOpenReply
	(*ChartOpenRequest)(nil),                // 7: mt4_term_api.ChartOpenRequest
	(*ChartOpenReply)(nil),                  // 8: mt4_term_api.ChartOpenReply
	(*ChartCloseRequest)(nil),               // 9: mt4_term_api.ChartCloseRequest
	(*ChartCloseReply)(nil),                 // 10: mt4_term_api.ChartCloseReply
}
var file_mt4_term_api_internal_charts_proto_depIdxs = []int32{
	0,  // 0: mt4_term_api.ChartOpenRequest.mode:type_name -> mt4_term_api.ChartTemplateMode
	7,  // 1: mt4_term_api.InternalCharts.ChartOpen:input_type -> mt4_term_api.ChartOpenRequest
	9,  // 2: mt4_term_api.InternalCharts.ChartClose:input_type -> mt4_term_api.ChartCloseRequest
	5,  // 3: mt4_term_api.InternalCharts.CustomChartOpen:input_type -> mt4_term_api.CustomChartOpenRequest
	3,  // 4: mt4_term_api.InternalCharts.CustomChartSaveTemplate:input_type -> mt4_term_api.CustomChartSaveTemplateRequest
	2,  // 5: mt4_term_api.InternalCharts.CustomChartApplyTemplate:input_type -> mt4_term_api.CustomChartApplyTemplateRequest
	8,  // 6: mt4_term_api.InternalCharts.ChartOpen:output_type -> mt4_term_api.ChartOpenReply
	10, // 7: mt4_term_api.InternalCharts.ChartClose:output_type -> mt4_term_api.ChartCloseReply
	6,  // 8: mt4_term_api.InternalCharts.CustomChartOpen:output_type -> mt4_term_api.CustomChartOpenReply
	4,  // 9: mt4_term_api.InternalCharts.CustomChartSaveTemplate:output_type -> mt4_term_api.CustomChartSaveTemplateReply
	1,  // 10: mt4_term_api.InternalCharts.CustomChartApplyTemplate:output_type -> mt4_term_api.CustomChartApplyTemplateReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_mt4_term_api_internal_charts_proto_init() }
func file_mt4_term_api_internal_charts_proto_init() {
	if File_mt4_term_api_internal_charts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mt4_term_api_internal_charts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartApplyTemplateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartApplyTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartSaveTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartSaveTemplateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomChartOpenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartOpenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt4_term_api_internal_charts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChartCloseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt4_term_api_internal_charts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt4_term_api_internal_charts_proto_goTypes,
		DependencyIndexes: file_mt4_term_api_internal_charts_proto_depIdxs,
		EnumInfos:         file_mt4_term_api_internal_charts_proto_enumTypes,
		MessageInfos:      file_mt4_term_api_internal_charts_proto_msgTypes,
	}.Build()
	File_mt4_term_api_internal_charts_proto = out.File
	file_mt4_term_api_internal_charts_proto_rawDesc = nil
	file_mt4_term_api_internal_charts_proto_goTypes = nil
	file_mt4_term_api_internal_charts_proto_depIdxs = nil
}
