// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt4-term-api-gui.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GuiClient is the client API for Gui service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuiClient interface {
	DemoOpenAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error)
	DemoOpenAccountInteractive(ctx context.Context, opts ...grpc.CallOption) (Gui_DemoOpenAccountInteractiveClient, error)
}

type guiClient struct {
	cc grpc.ClientConnInterface
}

func NewGuiClient(cc grpc.ClientConnInterface) GuiClient {
	return &guiClient{cc}
}

func (c *guiClient) DemoOpenAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error) {
	out := new(GuiDemoOpenAccountReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.Gui/DemoOpenAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoOpenAccountInteractive(ctx context.Context, opts ...grpc.CallOption) (Gui_DemoOpenAccountInteractiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gui_ServiceDesc.Streams[0], "/mt4_term_api.Gui/DemoOpenAccountInteractive", opts...)
	if err != nil {
		return nil, err
	}
	x := &guiDemoOpenAccountInteractiveClient{stream}
	return x, nil
}

type Gui_DemoOpenAccountInteractiveClient interface {
	Send(*GuiDemoInteractiveClientMessage) error
	Recv() (*GuiDemoInteractiveServerMessage, error)
	grpc.ClientStream
}

type guiDemoOpenAccountInteractiveClient struct {
	grpc.ClientStream
}

func (x *guiDemoOpenAccountInteractiveClient) Send(m *GuiDemoInteractiveClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *guiDemoOpenAccountInteractiveClient) Recv() (*GuiDemoInteractiveServerMessage, error) {
	m := new(GuiDemoInteractiveServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GuiServer is the server API for Gui service.
// All implementations should embed UnimplementedGuiServer
// for forward compatibility
type GuiServer interface {
	DemoOpenAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error)
	DemoOpenAccountInteractive(Gui_DemoOpenAccountInteractiveServer) error
}

// UnimplementedGuiServer should be embedded to have forward compatible implementations.
type UnimplementedGuiServer struct {
}

func (UnimplementedGuiServer) DemoOpenAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoOpenAccount not implemented")
}
func (UnimplementedGuiServer) DemoOpenAccountInteractive(Gui_DemoOpenAccountInteractiveServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoOpenAccountInteractive not implemented")
}

// UnsafeGuiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuiServer will
// result in compilation errors.
type UnsafeGuiServer interface {
	mustEmbedUnimplementedGuiServer()
}

func RegisterGuiServer(s grpc.ServiceRegistrar, srv GuiServer) {
	s.RegisterService(&Gui_ServiceDesc, srv)
}

func _Gui_DemoOpenAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoOpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).DemoOpenAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.Gui/DemoOpenAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).DemoOpenAccount(ctx, req.(*GuiDemoOpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoOpenAccountInteractive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuiServer).DemoOpenAccountInteractive(&guiDemoOpenAccountInteractiveServer{stream})
}

type Gui_DemoOpenAccountInteractiveServer interface {
	Send(*GuiDemoInteractiveServerMessage) error
	Recv() (*GuiDemoInteractiveClientMessage, error)
	grpc.ServerStream
}

type guiDemoOpenAccountInteractiveServer struct {
	grpc.ServerStream
}

func (x *guiDemoOpenAccountInteractiveServer) Send(m *GuiDemoInteractiveServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *guiDemoOpenAccountInteractiveServer) Recv() (*GuiDemoInteractiveClientMessage, error) {
	m := new(GuiDemoInteractiveClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Gui_ServiceDesc is the grpc.ServiceDesc for Gui service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gui_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.Gui",
	HandlerType: (*GuiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DemoOpenAccount",
			Handler:    _Gui_DemoOpenAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DemoOpenAccountInteractive",
			Handler:       _Gui_DemoOpenAccountInteractive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mt4-term-api-gui.proto",
}
