// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt4-term-api-subscriptions.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeClient, error)
	OnOpenedOrdersTickets(ctx context.Context, in *OnOpenedOrdersTicketsRequest, opts ...grpc.CallOption) (SubscriptionService_OnOpenedOrdersTicketsClient, error)
	OnOpenedOrdersProfit(ctx context.Context, in *OnOpenedOrdersProfitRequest, opts ...grpc.CallOption) (SubscriptionService_OnOpenedOrdersProfitClient, error)
	OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (SubscriptionService_OnSymbolTickClient, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], "/mt4_term_api.SubscriptionService/OnTrade", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnTradeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnTradeClient interface {
	Recv() (*OnTradeReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnTradeClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnTradeClient) Recv() (*OnTradeReply, error) {
	m := new(OnTradeReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnOpenedOrdersTickets(ctx context.Context, in *OnOpenedOrdersTicketsRequest, opts ...grpc.CallOption) (SubscriptionService_OnOpenedOrdersTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[1], "/mt4_term_api.SubscriptionService/OnOpenedOrdersTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnOpenedOrdersTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnOpenedOrdersTicketsClient interface {
	Recv() (*OnOpenedOrdersTicketsReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnOpenedOrdersTicketsClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnOpenedOrdersTicketsClient) Recv() (*OnOpenedOrdersTicketsReply, error) {
	m := new(OnOpenedOrdersTicketsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnOpenedOrdersProfit(ctx context.Context, in *OnOpenedOrdersProfitRequest, opts ...grpc.CallOption) (SubscriptionService_OnOpenedOrdersProfitClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[2], "/mt4_term_api.SubscriptionService/OnOpenedOrdersProfit", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnOpenedOrdersProfitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnOpenedOrdersProfitClient interface {
	Recv() (*OnOpenedOrdersProfitReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnOpenedOrdersProfitClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnOpenedOrdersProfitClient) Recv() (*OnOpenedOrdersProfitReply, error) {
	m := new(OnOpenedOrdersProfitReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (SubscriptionService_OnSymbolTickClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[3], "/mt4_term_api.SubscriptionService/OnSymbolTick", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnSymbolTickClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnSymbolTickClient interface {
	Recv() (*OnSymbolTickReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnSymbolTickClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnSymbolTickClient) Recv() (*OnSymbolTickReply, error) {
	m := new(OnSymbolTickReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations should embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	OnTrade(*OnTradeRequest, SubscriptionService_OnTradeServer) error
	OnOpenedOrdersTickets(*OnOpenedOrdersTicketsRequest, SubscriptionService_OnOpenedOrdersTicketsServer) error
	OnOpenedOrdersProfit(*OnOpenedOrdersProfitRequest, SubscriptionService_OnOpenedOrdersProfitServer) error
	OnSymbolTick(*OnSymbolTickRequest, SubscriptionService_OnSymbolTickServer) error
}

// UnimplementedSubscriptionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) OnTrade(*OnTradeRequest, SubscriptionService_OnTradeServer) error {
	return status.Errorf(codes.Unimplemented, "method OnTrade not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnOpenedOrdersTickets(*OnOpenedOrdersTicketsRequest, SubscriptionService_OnOpenedOrdersTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method OnOpenedOrdersTickets not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnOpenedOrdersProfit(*OnOpenedOrdersProfitRequest, SubscriptionService_OnOpenedOrdersProfitServer) error {
	return status.Errorf(codes.Unimplemented, "method OnOpenedOrdersProfit not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnSymbolTick(*OnSymbolTickRequest, SubscriptionService_OnSymbolTickServer) error {
	return status.Errorf(codes.Unimplemented, "method OnSymbolTick not implemented")
}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_OnTrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnTradeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnTrade(m, &subscriptionServiceOnTradeServer{stream})
}

type SubscriptionService_OnTradeServer interface {
	Send(*OnTradeReply) error
	grpc.ServerStream
}

type subscriptionServiceOnTradeServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnTradeServer) Send(m *OnTradeReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnOpenedOrdersTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnOpenedOrdersTicketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnOpenedOrdersTickets(m, &subscriptionServiceOnOpenedOrdersTicketsServer{stream})
}

type SubscriptionService_OnOpenedOrdersTicketsServer interface {
	Send(*OnOpenedOrdersTicketsReply) error
	grpc.ServerStream
}

type subscriptionServiceOnOpenedOrdersTicketsServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnOpenedOrdersTicketsServer) Send(m *OnOpenedOrdersTicketsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnOpenedOrdersProfit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnOpenedOrdersProfitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnOpenedOrdersProfit(m, &subscriptionServiceOnOpenedOrdersProfitServer{stream})
}

type SubscriptionService_OnOpenedOrdersProfitServer interface {
	Send(*OnOpenedOrdersProfitReply) error
	grpc.ServerStream
}

type subscriptionServiceOnOpenedOrdersProfitServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnOpenedOrdersProfitServer) Send(m *OnOpenedOrdersProfitReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnSymbolTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnSymbolTickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnSymbolTick(m, &subscriptionServiceOnSymbolTickServer{stream})
}

type SubscriptionService_OnSymbolTickServer interface {
	Send(*OnSymbolTickReply) error
	grpc.ServerStream
}

type subscriptionServiceOnSymbolTickServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnSymbolTickServer) Send(m *OnSymbolTickReply) error {
	return x.ServerStream.SendMsg(m)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnTrade",
			Handler:       _SubscriptionService_OnTrade_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnOpenedOrdersTickets",
			Handler:       _SubscriptionService_OnOpenedOrdersTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnOpenedOrdersProfit",
			Handler:       _SubscriptionService_OnOpenedOrdersProfit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnSymbolTick",
			Handler:       _SubscriptionService_OnSymbolTick_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mt4-term-api-subscriptions.proto",
}
