// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt4-term-api-market-info.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketInfoClient is the client API for MarketInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketInfoClient interface {
	// Get quote
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error)
	// Latest quote for the specified symbol
	QuoteMany(ctx context.Context, in *QuoteManyRequest, opts ...grpc.CallOption) (*QuoteManyReply, error)
	Symbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsReply, error)
	QuoteHistory(ctx context.Context, in *QuoteHistoryRequest, opts ...grpc.CallOption) (*QuoteHistoryReply, error)
}

type marketInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketInfoClient(cc grpc.ClientConnInterface) MarketInfoClient {
	return &marketInfoClient{cc}
}

func (c *marketInfoClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error) {
	out := new(QuoteReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.MarketInfo/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) QuoteMany(ctx context.Context, in *QuoteManyRequest, opts ...grpc.CallOption) (*QuoteManyReply, error) {
	out := new(QuoteManyReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.MarketInfo/QuoteMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) Symbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsReply, error) {
	out := new(SymbolsReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.MarketInfo/Symbols", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketInfoClient) QuoteHistory(ctx context.Context, in *QuoteHistoryRequest, opts ...grpc.CallOption) (*QuoteHistoryReply, error) {
	out := new(QuoteHistoryReply)
	err := c.cc.Invoke(ctx, "/mt4_term_api.MarketInfo/QuoteHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketInfoServer is the server API for MarketInfo service.
// All implementations should embed UnimplementedMarketInfoServer
// for forward compatibility
type MarketInfoServer interface {
	// Get quote
	Quote(context.Context, *QuoteRequest) (*QuoteReply, error)
	// Latest quote for the specified symbol
	QuoteMany(context.Context, *QuoteManyRequest) (*QuoteManyReply, error)
	Symbols(context.Context, *SymbolsRequest) (*SymbolsReply, error)
	QuoteHistory(context.Context, *QuoteHistoryRequest) (*QuoteHistoryReply, error)
}

// UnimplementedMarketInfoServer should be embedded to have forward compatible implementations.
type UnimplementedMarketInfoServer struct {
}

func (UnimplementedMarketInfoServer) Quote(context.Context, *QuoteRequest) (*QuoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedMarketInfoServer) QuoteMany(context.Context, *QuoteManyRequest) (*QuoteManyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteMany not implemented")
}
func (UnimplementedMarketInfoServer) Symbols(context.Context, *SymbolsRequest) (*SymbolsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Symbols not implemented")
}
func (UnimplementedMarketInfoServer) QuoteHistory(context.Context, *QuoteHistoryRequest) (*QuoteHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteHistory not implemented")
}

// UnsafeMarketInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketInfoServer will
// result in compilation errors.
type UnsafeMarketInfoServer interface {
	mustEmbedUnimplementedMarketInfoServer()
}

func RegisterMarketInfoServer(s grpc.ServiceRegistrar, srv MarketInfoServer) {
	s.RegisterService(&MarketInfo_ServiceDesc, srv)
}

func _MarketInfo_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.MarketInfo/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_QuoteMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).QuoteMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.MarketInfo/QuoteMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).QuoteMany(ctx, req.(*QuoteManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_Symbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).Symbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.MarketInfo/Symbols",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).Symbols(ctx, req.(*SymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketInfo_QuoteHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketInfoServer).QuoteHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt4_term_api.MarketInfo/QuoteHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketInfoServer).QuoteHistory(ctx, req.(*QuoteHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketInfo_ServiceDesc is the grpc.ServiceDesc for MarketInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt4_term_api.MarketInfo",
	HandlerType: (*MarketInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quote",
			Handler:    _MarketInfo_Quote_Handler,
		},
		{
			MethodName: "QuoteMany",
			Handler:    _MarketInfo_QuoteMany_Handler,
		},
		{
			MethodName: "Symbols",
			Handler:    _MarketInfo_Symbols_Handler,
		},
		{
			MethodName: "QuoteHistory",
			Handler:    _MarketInfo_QuoteHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt4-term-api-market-info.proto",
}
